'use strict';
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const { _electron }=require(process.env.CHEM_PLAYWRIGHT_PATH);
const root=path.resolve(__dirname,'..');
const outputDirectory=process.env.CHEM_ACCEPTANCE_DIR
 ?path.resolve(process.env.CHEM_ACCEPTANCE_DIR):path.join(root,'build','desktop-qa-'+Date.now());
assert.ok(outputDirectory.startsWith(path.join(root,'build')+path.sep),'Acceptance output must stay in build');
fs.mkdirSync(outputDirectory,{recursive:false});
const info=JSON.parse(fs.readFileSync(path.join(root,'build','desktop-latest.json'),'utf8'));
(async()=>{
 const app=await _electron.launch({executablePath:info.executable,args:[],timeout:60000});
 const page=await app.firstWindow({timeout:60000});
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 try{
  await page.locator('#status').getByText('Passed',{exact:true}).waitFor({timeout:30000});
  page.once('dialog',dialog=>dialog.accept());
  await page.getByRole('button',{name:'◇  fcc-copper.chem',exact:true}).click();
  await page.locator('#compile').click();
  await page.locator('#model-name').getByText(/Gemma 4/).waitFor();
  await page.locator('#model-status').getByText(/Connected/).waitFor({timeout:30000});
  await page.locator('#objective').fill('Prepare fcc_copper at scales 0.98, 1.00, 1.02 for human review. Do not execute.');
  await page.locator('#orchestrate').click();
  await page.locator('#agent-progress').getByText(/REPORTED.*1 tool call/).waitFor({timeout:120000});
  await page.locator('#prepare-compute').click();
  await page.locator('#run-state').getByText(/^(PREPARED|SUCCEEDED)$/).waitFor({timeout:60000});
  await page.locator('#execution-message').getByText(/Matching model proposal attached/).waitFor();
  assert.equal(await page.locator('#run-compute').isDisabled(),true);
  await page.locator('#approve-compute').click();
  await page.locator('#run-compute').waitFor({state:'visible'});
  await page.locator('#run-state').getByText('APPROVED',{exact:true}).waitFor({timeout:60000});
  await page.locator('#run-compute').click();
  await page.locator('#run-state').getByText('SUCCEEDED',{exact:true}).waitFor({timeout:60000});
  assert.equal(await page.locator('#computed-results tbody tr').count(),3);
  assert.equal(await page.locator('#energy-chart svg').count(),1);
  await page.locator('#project-name').fill('Desktop acceptance');
  await page.locator('#save-project').click();
  await page.locator('#save-state').getByText(/Saved/).waitFor();
  await page.screenshot({path:path.join(outputDirectory,'desktop-acceptance.png'),fullPage:true});
  await page.locator('#import-molecule').click();
  await page.locator('#structure-lab-message').getByText(/Seed 42/).waitFor({timeout:30000});
  const before=await page.locator('#geometry-hash').innerText();
  const positions=JSON.parse(await page.locator('#coordinate-edit').inputValue());positions[0][0]+=0.1;
  await page.locator('#coordinate-edit').fill(JSON.stringify(positions));
  await page.locator('#apply-coordinates').click();
  await page.locator('#structure-lab-message').getByText(/Explicit coordinate revision/).waitFor();
  assert.notEqual(await page.locator('#geometry-hash').innerText(),before);
  await page.locator('#compare-coordinates').click();
  await page.locator('#structure-comparison').getByText(/rms_displacement/).waitFor();
  await page.locator('#build-slab').click();
  await page.locator('#structure-lab-message').getByText(/Constructed Cu/).waitFor({timeout:30000});
  assert.equal(await page.locator('#atom-count').innerText(),'16');
  assert.equal(await page.locator('#energy-chart svg').count(),0);
  await page.locator('#computed-results').getByText('No computed evidence yet.',{exact:true}).waitFor();
  assert.equal(await page.locator('#download-evidence').isDisabled(),true);
  await page.screenshot({path:path.join(outputDirectory,'desktop-slab-acceptance.png'),fullPage:true});
  page.once('dialog',dialog=>dialog.accept());
  await page.locator('#project-history').selectOption({index:1});
  await page.locator('#save-state').getByText(/Opened/).waitFor();
  await page.getByRole('button',{name:'◇  water.chem',exact:true}).click();
  await page.locator('#compile').click();
  await page.locator('#status').getByText('Passed',{exact:true}).waitFor();
  await page.locator('#compute-profile').selectOption('water');
  await page.locator('#prepare-compute').click();
  await page.locator('#run-state').getByText(/^(PREPARED|SUCCEEDED)$/).waitFor({timeout:60000});
  await page.locator('#approve-compute').click();
  await page.locator('#run-state').getByText('APPROVED',{exact:true}).waitFor({timeout:60000});
  await page.locator('#run-compute').click();
  await page.locator('#run-state').getByText('SUCCEEDED',{exact:true}).waitFor({timeout:90000});
  await page.locator('#computed-results').getByText(/HF\/STO-3G.*-74/).waitFor();
  const exportDirectory=path.join(info.directory,'workspace','build','exports');
  const priorExports=new Set(fs.existsSync(exportDirectory)?fs.readdirSync(exportDirectory):[]);
  await page.locator('#download-evidence').click();
  const evidencePath=path.join(outputDirectory,'desktop-water-evidence.json');
  let savedExport;
  const exportDeadline=Date.now()+15000;
  while(Date.now()<exportDeadline){
    savedExport=fs.existsSync(exportDirectory)&&fs.readdirSync(exportDirectory).find(name=>!priorExports.has(name)&&name.endsWith('-workbench.execution-evidence.json'));
    if(savedExport)break;
    await new Promise(resolve=>setTimeout(resolve,100));
  }
  assert.ok(savedExport,'Electron must save a new evidence file');
  fs.copyFileSync(path.join(exportDirectory,savedExport),evidencePath);
  const exported=JSON.parse(fs.readFileSync(evidencePath,'utf8'));
  assert.equal(exported.state,'succeeded');
  assert.equal(exported.result.evidence_eligible,true);
  await page.locator('#save-project').click();
  await page.locator('#save-state').getByText(/Saved/).waitFor();
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.screenshot({path:path.join(outputDirectory,'desktop-final-viewport.png'),fullPage:false});
  const security=await app.evaluate(({BrowserWindow})=>{const p=BrowserWindow.getAllWindows()[0].webContents.getLastWebPreferences();return {sandbox:p.sandbox,contextIsolation:p.contextIsolation,nodeIntegration:p.nodeIntegration};});
  assert.deepEqual(security,{sandbox:true,contextIsolation:true,nodeIntegration:false});
  assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(outputDirectory,'desktop-acceptance.json'),JSON.stringify({passed:true,security,errors,package:info.directory,url:page.url(),checks:['real E4B proposal with matching provenance','real copper calculation and chart','explicit approval','saved project and reopened revision','chiral import','coordinate revision','same-composition comparison','real Cu111 construction','real water calculation','evidence export independently reopened']},null,2));
  console.log(outputDirectory);
 } finally{
  // This test-created workspace is saved before closing; no user edits are discarded.
  await page.locator('#save-project').click().catch(()=>{});
  await page.locator('#save-state').getByText(/Saved/).waitFor({timeout:5000}).catch(()=>{});
  await app.close();
 }
})().catch(error=>{console.error(error);process.exitCode=1;});
