'use strict';
// Runs the shipped event handlers with a minimal DOM and synthetic transport.
// Scientific correctness is covered by the real Python integration tests.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '..');
const elements = new Map(), listeners = new Map(), geometry = [], downloads = [], requests = [], queued = new Map();
let wallClock = 0, timerSequence = 0;
const timers = new Map();
function schedule(fn, delay, repeating) {const id=++timerSequence;timers.set(id,{fn,delay,at:wallClock+delay,repeating});return id;}
function advanceWallClock(milliseconds) {const until=wallClock+milliseconds;for(;;){const due=[...timers].filter(([,timer])=>timer.at<=until).sort((a,b)=>a[1].at-b[1].at)[0];if(!due)break;const [id,timer]=due;wallClock=timer.at;if(timer.repeating)timer.at+=timer.delay;else timers.delete(id);timer.fn();}wallClock=until;}
class Element {
  constructor(tag = 'div') {this.tagName=tag;this.children=[];this.attributes={};this.dataset={};this.style={};this.listeners=new Map();this.value='';this.disabled=false;this.hidden=false;this._text='';this._html='';this.classList={add:()=>{},remove:()=>{}};}
  set id(value){this.attributes.id=value;elements.set(value,this);} get id(){return this.attributes.id;}
  set className(value){this.attributes.class=value;} get className(){return this.attributes.class||'';}
  append(...nodes){for(const node of nodes){if(node instanceof Element)node.parent=this;this.children.push(node);}}
  prepend(node){node.parent=this;this.children.unshift(node);}
  after(node){this.parent?.append(node);}
  replaceChildren(...nodes){for(const child of this.children)if(child instanceof Element)child.parent=null;this.children=[];this._text='';this._html='';this.append(...nodes);}
  set textContent(value){this.children=[];this._text=String(value);} get textContent(){return this._text+this.children.map(node=>node.textContent??node).join('');}
  set innerHTML(value){this.replaceChildren();this._html=value;parse(value,this);} get innerHTML(){return this._html;}
  setAttribute(name,value){this.attributes[name]=String(value);if(name==='id')this.id=value;if(name==='value')this.value=String(value);if(name==='disabled')this.disabled=true;if(name==='hidden')this.hidden=true;if(name.startsWith('data-'))this.dataset[name.slice(5)]=String(value);}
  getAttribute(name){return this.attributes[name];}
  addEventListener(type,fn){if(!this.listeners.has(type))this.listeners.set(type,[]);this.listeners.get(type).push(fn);}
  removeEventListener(type,fn){this.listeners.set(type,(this.listeners.get(type)||[]).filter(item=>item!==fn));}
  remove(){if(this.parent)this.parent.children=this.parent.children.filter(item=>item!==this);this.parent=null;}
  get isConnected(){let node=this;while(node){if(node===body)return true;node=node.parent;}return false;}
  focus(){document.activeElement=this;} scrollIntoView(){}
  async fire(type){const event={type,target:this};for(const fn of this.listeners.get(type)||[])await fn(event);return this['on'+type]?.(event);}
  click(){return this.fire('click');}
  get options(){return this.querySelectorAll('option');}
  querySelector(selector){return this.querySelectorAll(selector)[0]||null;}
  querySelectorAll(selector){const found=[];const match=node=>selector.startsWith('.')?node.className.split(' ').includes(selector.slice(1)):selector==='tr[data-candidate]'?node.tagName==='tr'&&node.dataset.candidate!==undefined:node.tagName===selector;const visit=node=>{for(const child of node.children){if(!(child instanceof Element))continue;if(match(child))found.push(child);visit(child);}};visit(this);return found;}
}
function parse(html,parent){const stack=[parent];for(const token of html.match(/<[^>]+>|[^<]+/g)||[]){if(token.startsWith('</')){stack.pop();continue;}if(token.startsWith('<')){const tag=token.match(/^<([\w-]+)/)?.[1];if(!tag)continue;const node=new Element(tag);for(const match of token.matchAll(/([\w-]+)(?:="([^"]*)")?/g)){if(match.index===1)continue;node.setAttribute(match[1],match[2]??'');}stack.at(-1).append(node);if(!['input','br','hr','img'].includes(tag))stack.push(node);}else stack.at(-1).append(token);}}
const body=new Element('body');
const get=id=>{if(!elements.has(id)){const node=new Element();node.id=id;body.append(node);}return elements.get(id);};
const heading=new Element();heading.className='heading';heading.innerHTML='<p class="eyebrow"></p><h1></h1><p class="subtitle"></p>';body.append(heading);
for(const name of ['studio-grid','viewer-controls']){const node=new Element();node.className=name;body.append(node);}
for(const id of ['compile','examples','structure-select','filename','source-origin','editor-title'])get(id);
const document={body,hidden:false,getElementById:get,createElement:tag=>new Element(tag),createElementNS:(_namespace,tag)=>new Element(tag),createTextNode:value=>String(value),querySelector:selector=>body.querySelector(selector),querySelectorAll:selector=>body.querySelectorAll(selector),
 addEventListener(type,fn){if(!listeners.has(type))listeners.set(type,[]);listeners.get(type).push(fn);},removeEventListener(type,fn){listeners.set(type,(listeners.get(type)||[]).filter(item=>item!==fn));},dispatchEvent(event){for(const fn of listeners.get(event.type)||[])fn(event);}};
const study={version:'design-study/v1',name:'Complex interface fixture',organic:{scaffold_id:'catechol_amide'},inorganic:{a_elements:['Sr']},interface_parameters:{mode:'illustrative',specifications:[]},selected_candidates:null,budget:{max_candidates_per_family:24,max_interface_runs:3}};
const direct={action:'run_workflow',workflow:'interface_design',interfaces:[],message:'Synthetic action'};
function defer(url){let finish;const promise=new Promise(resolve=>{finish=resolve;});const item={promise,finishText:(text,status=200)=>finish({ok:status===200,status,json:async()=>JSON.parse(text),text:async()=>text}),finish:(value,status=200)=>finish({ok:status===200,status,json:async()=>value,text:async()=>JSON.stringify(value)})};if(!queued.has(url))queued.set(url,[]);queued.get(url).push(item);return item;}
const context=vm.createContext({document,console,structuredClone,Event:function(type){this.type=type;},clearGeometry:message=>geometry.push({kind:'clear',message}),displayGeometry:value=>geometry.push({kind:'display',value}),download:(record,name)=>downloads.push({record:structuredClone(record),name}),fetch:async(url,options)=>{const payload=options.body?JSON.parse(options.body):null;requests.push({url,payload,body:options.body});const pending=queued.get(url)?.shift();if(pending)return pending.promise;const values={'/api/design/history':{records:[],errors:[]},'/api/design/catalog':{study:structuredClone(study),direct_decision:direct},'/api/model/status':{display_name:'Synthetic model fixture'}};assert.ok(url in values,'Unexpected request '+url);return {ok:true,status:200,json:async()=>values[url],text:async()=>JSON.stringify(values[url])};}});
context.window=context;
context.performance={now:()=>wallClock};
context.setInterval=(fn,delay)=>schedule(fn,delay,true);context.clearInterval=id=>timers.delete(id);
context.setTimeout=(fn,delay)=>schedule(fn,delay,false);context.clearTimeout=id=>timers.delete(id);
context.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){}});
const app=fs.readFileSync(path.join(root,'src/chem_workbench/web_assets/app.js'),'utf8');
vm.runInContext(app.split(/\r?\n/).find(line=>line.startsWith('async function api(')),context,{filename:'app.js/api'});
vm.runInContext(fs.readFileSync(path.join(root,'src/chem_workbench/web_assets/interface-workbench.js'),'utf8'),context,{filename:'interface-workbench.js'});
vm.runInContext(fs.readFileSync(path.join(root,'src/chem_workbench/web_assets/design-studio.js'),'utf8'),context,{filename:'design-studio.js'});
const hash=n=>'sha256:'+String(n).padStart(64,'0');
const candidate=(family,n)=>({id:family+n,family,candidate_hash:hash(n),geometry:{atoms:Array.from({length:family==='organic'?33:40},()=>({element:'C',position:[0,0,0]})),geometry_hash:hash(n+500)},generation:{fragment_id:'hydroxyethyl'},formula:'Sr2ScNbO6',descriptors:{molecular_weight:285,logp:1.4,tpsa:95,tolerance_factor:.97,lattice_parameter_angstrom:8},score:.03});
function record(n=100){const organic=[candidate('organic',1),candidate('organic',2)],inorganic=[candidate('inorganic',3),candidate('inorganic',4)];const simulation=(profile,left=organic[1],right=inorganic[1])=>({profile,parameter_status:'illustrative',inputs:{organic_candidate:left,inorganic_candidate:right,spec:{parameters:{k:{value:1,unit:'s^-1'}}}},mechanism:{species:[{id:'catechol',formula:'C15H17NO5'},{id:'quinone',formula:'C15H15NO5'},{id:'H2',formula:'H2'}],steps:[{reactants:{catechol:1},products:{quinone:1,H2:1}}]},series:[{time_s:0,current_density_A_m2:0,theta_product:0,theta_adsorbed:0},{time_s:1,current_density_A_m2:-2,theta_product:.2,theta_adsorbed:.3}],balances:{passed:true},solver:{method:'Radau'}});return {version:'design-run/v1',record_hash:hash(n),request:{prompt:'A declared complex design fixture',study:structuredClone(study),mode:'direct'},decision:{...direct,workflow:'interface_design'},state:'completed',organic:{candidates:organic},inorganic:{candidates:inorganic},interfaces:['electrode_electrolyte','catalyst_reactant','solid_liquid'].map(profile=>simulation(profile)),selected_pair:{organic:hash(2),inorganic:hash(4)},trace:[{module:'organic_design',status:'succeeded',seconds:.1},{module:'inorganic_design',status:'succeeded',seconds:.1}],seconds:1.2,_simulation:simulation};}
function completeFixtureMetadata(value){for(const family of ['organic','inorganic'])if(value[family])Object.assign(value[family],{candidate_count:value[family].candidates.length,attempted_count:value[family].candidates.length,rejected:[],ranking:{objective:'synthetic renderer fixture',direction:'ascending'},limitations:['Synthetic UI transport fixture, not scientific acceptance.']});for(const simulation of value.interfaces||[]){simulation.units={time_s:'s',current_density_A_m2:'A/m^2',theta_product:'1',theta_adsorbed:'1'};simulation.success=true;for(const species of simulation.mechanism.species)Object.assign(species,{role:'Synthetic renderer fixture identity',atom_count:0,formal_charge:0,radical_electrons:0,site_count:0,graph:{atoms:[],bonds:[]}});for(const [index,step]of simulation.mechanism.steps.entries())Object.assign(step,{id:'synthetic-step-'+index,reversible:true,rate_assumption:'Synthetic UI transport fixture'});}return value;}
function fixture(n=100){const value=completeFixtureMetadata(record(n));delete value._simulation;return value;}
const settle=()=>new Promise(resolve=>setImmediate(resolve));
const checks=[];
async function scenario(name,check){try{await check();checks.push(name);}catch(error){error.message=name+': '+error.message;throw error;}}
async function show(value){completeFixtureMetadata(value);const pending=defer('/api/design/read');get('design-history').value=value.record_hash;const loading=get('design-history').onchange();pending.finish(value);await loading;}
async function exportRecord(value){const pending=defer('/api/design/export');const saving=get('export-design').onclick();assert.deepEqual(requests.at(-1).payload,{reference:value.record_hash});pending.finish({reference:value.record_hash,path:'C:/workspace/build/exports/chem-design-'+value.record_hash.slice(7)+'.json',filename:'chem-design-'+value.record_hash.slice(7)+'.json',file_sha256:hash(900)});await saving;assert.match(get('design-export-status').textContent,/Saved locally:.*build\/exports/);assert.match(get('design-export-status').textContent,/File SHA-256:/);}
async function run(value,kind='direct',status=200){const pending=defer('/api/design/run');const running=get(kind==='direct'?'run-design-direct':'run-design-model').onclick();pending.finish(value,status);await running;}
(async()=>{
 await settle();
 await scenario('pending model request displays wall time without invented numerical progress',async()=>{await show(fixture());const pending=defer('/api/design/run'),running=get('run-design-model').onclick();assert.equal(get('design-pending').hidden,false);assert.match(get('design-pending-label').textContent,/Awaiting LM Studio and workflow results/);assert.equal(get('design-pending-time').textContent,'Elapsed wall time: 0.0 s');advanceWallClock(1250);assert.equal(get('design-pending-time').textContent,'Elapsed wall time: 1.3 s');assert.equal(get('design-organic-count').textContent,'—');assert.equal(get('design-interface-count').textContent,'—');assert.equal(get('interface-tabs').children.length,0);assert.match(get('design-pending').textContent,/only after numerical samples are returned/);assert.doesNotMatch(get('design-pending').textContent,/[0-9]\s*%/);pending.finish(fixture());await running;assert.equal(get('design-pending').hidden,true);assert.equal(timers.size,0);});
 await scenario('pending direct request does not claim model or solver progress before response',async()=>{await show(fixture());const pending=defer('/api/design/run'),running=get('run-design-direct').onclick();advanceWallClock(500);assert.equal(get('design-pending-label').textContent,'Awaiting local workflow results');assert.equal(get('design-pending-time').textContent,'Elapsed wall time: 0.5 s');assert.equal(get('design-module-trace').children.length,0);assert.equal(get('interface-tabs').children.length,0);pending.finish({error:'Synthetic request failure',design_record:{...fixture(99),state:'failed'}},400);await running;assert.equal(get('design-pending').hidden,true);assert.equal(timers.size,0);assert.equal(get('design-status').dataset.state,'failed');});
 await scenario('input invalidation stops the pending clock and ignores late activity',async()=>{await show(fixture());const pending=defer('/api/design/run'),running=get('run-design-model').onclick();advanceWallClock(500);get('design-prompt').value+=' revised while pending';await get('design-prompt').fire('input');const lastClock=get('design-pending-time').textContent;assert.equal(get('design-pending').hidden,true);assert.equal(timers.size,0);advanceWallClock(2000);assert.equal(get('design-pending-time').textContent,lastClock);pending.finish(fixture(98));await running;assert.equal(get('design-interface-count').textContent,'—');assert.equal(get('design-libraries').children.length,0);assert.match(get('design-status').textContent,/Objective changed/);});
 await scenario('actual selected pair hashes choose displayed candidate',async()=>{await run(fixture());assert.equal(get('design-candidate-select').value,hash(2));assert.equal(geometry.at(-1).value.geometry_hash,hash(502));assert.equal(get('interface-tabs').children.length,3);assert.match(get('interface-view').textContent,/C15H17NO5.*C15H15NO5.*H2/);assert.equal(get('export-design').disabled,false);});
 await scenario('candidate switch cannot retain another pair curves',async()=>{get('design-candidate-select').value=hash(1);get('design-candidate-select').onchange();assert.equal(get('interface-tabs').children.length,0);assert.match(get('interface-view').textContent,/No simulation is bound/);get('design-candidate-select').value=hash(2);get('design-candidate-select').onchange();assert.equal(get('interface-tabs').children.length,3);});
 await scenario('multiple screened pairs expose only matching simulations',async()=>{const value=record(101);value.interfaces.push(value._simulation('solid_liquid',value.organic.candidates[0],value.inorganic.candidates[1]));delete value._simulation;await show(value);get('design-candidate-select').value=hash(1);get('design-candidate-select').onchange();assert.equal(get('interface-tabs').children.length,1);assert.equal(get('interface-tabs').children[0].textContent,'Solid / liquid');});
 await scenario('HTTP failure record stays inspectable and exportable',async()=>{const failed=fixture(102);failed.state='failed';failed.error={message:'Integration failed after generation'};failed.trace.push({module:'solid_liquid',status:'failed',seconds:.4,error:{message:'Bounded solver failure'}});await run({error:'Integration failed after generation',design_record:failed},'model',400);assert.match(get('design-status').textContent,/Study failed:/);assert.equal(get('design-status').dataset.state,'failed');assert.equal(get('design-module-trace').children.at(-1).dataset.status,'failed');assert.match(get('design-module-trace').children.at(-1).textContent,/Failed.*Bounded solver failure/);assert.match(get('interface-provenance').textContent,/Partial run result/);await exportRecord(failed);assert.equal(downloads.length,0);});
 await scenario('rejected raw decision does not become clarification',async()=>{const rejected={...fixture(103),state:'rejected',decision:null,organic:null,inorganic:null,interfaces:[],trace:[],error:{message:'Unsupported model action'}};await run({error:'Unsupported model action',design_record:rejected},'model',400);assert.match(get('design-status').textContent,/Study rejected:/);assert.equal(get('design-organic-count').textContent,'0');assert.equal(get('interface-tabs').children.length,0);assert.equal(get('export-design').disabled,false);assert.equal(geometry.at(-1).kind,'clear');});
 await scenario('sampled needs input retains its distinct state',async()=>{const value={...fixture(104),state:'needs_input',organic:null,inorganic:null,interfaces:[],trace:[],decision:{...direct,message:'Supply candidate-specific parameters.'}};await run(value,'model');assert.match(get('design-status').textContent,/Clarification needed:/);assert.equal(get('design-status').dataset.state,'needs_input');});
 for(const field of ['design-prompt','design-study-input','design-workflow','design-parameter-mode','design-comparison-objective'])await scenario('late result discarded after '+field,async()=>{await show(fixture());const pending=defer('/api/design/run');const running=get('run-design-model').onclick();const node=get(field);if(field==='design-comparison-objective')node.value='solid_liquid';else if(field==='design-workflow')node.value='organic_design';else if(field==='design-parameter-mode')node.value='none';else if(field==='design-study-input')node.value=JSON.stringify({...study,name:'Changed study'});else node.value+=' changed';await node.fire(['design-workflow','design-parameter-mode','design-comparison-objective'].includes(field)?'change':'input');pending.finish(fixture(105));await running;assert.equal(get('export-design').disabled,true);assert.equal(get('design-libraries').children.length,0);assert.equal(get('interface-tabs').children.length,0);assert.equal(geometry.at(-1).kind,'clear');});
 await scenario('late failed result cannot overwrite revised input',async()=>{await show(fixture());const pending=defer('/api/design/run');const running=get('run-design-model').onclick();get('design-prompt').value+=' new';await get('design-prompt').fire('input');pending.finish({error:'Late failure',design_record:{...fixture(106),state:'failed'}},400);await running;assert.match(get('design-status').textContent,/Objective changed/);assert.equal(get('export-design').disabled,true);});
 await scenario('late history cannot overwrite an edited study',async()=>{const pending=defer('/api/design/read');get('design-history').value=hash(100);const loading=get('design-history').onchange();get('design-study-input').value=JSON.stringify({...study,name:'New revision'});await get('design-study-input').fire('input');pending.finish(fixture());await loading;assert.equal(JSON.parse(get('design-study-input').value).name,'New revision');assert.equal(get('export-design').disabled,true);});
 await scenario('history restores exact workflow and prompt',async()=>{const value=fixture(107);value.decision.workflow='organic_design';value.request.prompt='Preserved prompt';await show(value);assert.equal(get('design-workflow').value,'organic_design');assert.equal(get('design-prompt').value,'Preserved prompt');});
 await scenario('prompt and parameter changes preserve selected saved references',async()=>{await show(fixture());get('design-candidate-select').value=hash(1);get('design-candidate-select').onchange();get('design-prompt').value+=' use selection';await get('design-prompt').fire('input');assert.deepEqual(JSON.parse(get('design-study-input').value).selected_candidates,{run_ref:hash(100),organic_hash:hash(1),inorganic_hash:hash(4)});await show(fixture());get('design-parameter-mode').value='supplied';await get('design-parameter-mode').fire('change');assert.equal(JSON.parse(get('design-study-input').value).selected_candidates.organic_hash,hash(2));});
 await scenario('selected pair direct run forwards saved references',async()=>{await show(fixture());get('design-workflow').value='interface_simulation';await get('design-workflow').fire('change');await run(fixture(108));assert.equal(requests.at(-1).payload.study.selected_candidates.organic_hash,hash(2));assert.equal(requests.at(-1).payload.decision.workflow,'interface_simulation');});
 await scenario('export reopens only through the host integrity check',async()=>{await show(fixture());await exportRecord(fixture());const exported=fixture(),rawDocument=JSON.stringify(exported).replace('\"value\":1,','\"value\":1.0,');assert.notEqual(rawDocument,JSON.stringify(JSON.parse(rawDocument)));const pending=defer('/api/design/import');get('import-design-file').files=[{size:rawDocument.length,text:async()=>rawDocument}];const loading=get('import-design-file').onchange();await settle();assert.deepEqual(requests.at(-1).payload,{document:rawDocument});pending.finish(exported);await loading;assert.equal(get('design-history').value,exported.record_hash);assert.equal(get('design-candidate-select').value,hash(2));assert.equal(get('import-design-file').value,'');assert.match(get('design-status').textContent,/Imported data; origin unverified/);});
 await scenario('tampered exported study cannot display unverified coordinates',async()=>{const value=fixture();value.organic.candidates[0].geometry.atoms[0].position[0]=999;const pending=defer('/api/design/import');get('import-design-file').files=[{size:100,text:async()=>JSON.stringify(value)}];const loading=get('import-design-file').onchange();await settle();pending.finish({error:'DESIGN_IMPORT_HASH_MISMATCH'},400);await loading;assert.match(get('design-status').textContent,/Cannot open study.*HASH_MISMATCH/);assert.equal(get('export-design').disabled,true);assert.equal(get('design-libraries').children.length,0);});
 await scenario('oversized files stop before transport',async()=>{const before=requests.length;get('import-design-file').files=[{size:21*1024*1024,text:async()=>JSON.stringify(fixture())}];await get('import-design-file').onchange();assert.equal(requests.length,before);assert.equal(get('export-design').disabled,true);});
 await scenario('malformed raw documents cannot become displayed evidence',async()=>{const pending=defer('/api/design/import');get('import-design-file').files=[{size:1,text:async()=>'{'}];const loading=get('import-design-file').onchange();await settle();assert.deepEqual(requests.at(-1).payload,{document:'{'});pending.finish({error:'Malformed JSON document'},400);await loading;assert.equal(get('export-design').disabled,true);assert.match(get('design-status').textContent,/Cannot open study: Malformed JSON/);});
 await scenario('late file read cannot import over a new input revision',async()=>{let finish;get('import-design-file').files=[{size:100,text:()=>new Promise(resolve=>{finish=resolve;})}];const before=requests.length,loading=get('import-design-file').onchange();get('design-prompt').value+=' changed during read';await get('design-prompt').fire('input');finish(JSON.stringify(fixture()));await loading;assert.equal(requests.length,before);assert.equal(get('export-design').disabled,true);});
 await scenario('background structure compilation preserves displayed design geometry',async()=>{await show(fixture());const before=geometry.length;document.dispatchEvent({type:'structure-compiled-background'});assert.equal(geometry.length,before);assert.equal(get('filename').textContent,study.name);});
 await scenario('an earlier running model cannot overwrite opened history',async()=>{const pending=defer('/api/design/run'),running=get('run-design-model').onclick();await show(fixture(109));pending.finish(fixture(110));await running;assert.equal(get('design-history').value,hash(109));assert.equal(get('export-design').disabled,false);});
 await scenario('screening ties do not imply a unique material winner',async()=>{const value=record(111);value.interfaces=[value._simulation('solid_liquid'),value._simulation('solid_liquid',value.organic.candidates[0],value.inorganic.candidates[0])];delete value._simulation;value.interface_screening={objective:{profile:'solid_liquid',objective:'max_adsorbed_coverage'},winner:null,rows:[{pair:{organic:hash(2),inorganic:hash(4)},value:.3,unit:'1',tied_best:true},{pair:{organic:hash(1),inorganic:hash(3)},value:.3,unit:'1',tied_best:true}]};await show(value);assert.match(get('design-comparison').textContent,/No unique best scenario/);assert.equal(get('design-comparison').querySelectorAll('button').length,2);get('design-comparison').querySelectorAll('button')[1].onclick();assert.equal(get('design-candidate-select').value,hash(1));assert.equal(get('interface-tabs').children.length,1);assert.equal(get('interface-tabs').children[0].textContent,'Solid / liquid');assert.match(get('design-comparison').textContent,/Tied best supplied scenario/);});
 await scenario('screening without objective or data gives actionable feedback',async()=>{await show(fixture());get('design-workflow').value='interface_screening';await get('design-workflow').fire('change');const before=requests.length;await get('run-design-direct').onclick();assert.equal(requests.length,before);assert.match(get('design-status').textContent,/Choose a comparison objective and supply two to four/);});
 await scenario('comparison selector writes an explicit registered objective',async()=>{await show(fixture());get('design-comparison-objective').value='solid_liquid';await get('design-comparison-objective').fire('change');const supplied=JSON.parse(get('design-study-input').value);assert.deepEqual(supplied.interface_screening,{profile:'solid_liquid',objective:'max_adsorbed_coverage'});assert.equal(supplied.selected_candidates.organic_hash,hash(2));assert.equal(supplied.interface_parameters.mode,'illustrative','Selecting an objective must not manufacture supplied parameters');});
 await scenario('both selected candidate rows retain selection highlighting',async()=>{await show(fixture());const selected=get('design-results').querySelectorAll('tr[data-candidate]').filter(row=>row.getAttribute('aria-selected')==='true').map(row=>row.dataset.candidate);assert.deepEqual(selected,[hash(2),hash(4)]);get('design-candidate-select').value=hash(3);get('design-candidate-select').onchange();assert.deepEqual(get('design-results').querySelectorAll('tr[data-candidate]').filter(row=>row.getAttribute('aria-selected')==='true').map(row=>row.dataset.candidate),[hash(2),hash(3)]);});
 await scenario('empty Design mode cannot inherit a Structure geometry',async()=>{get('design-prompt').value+=' invalidation';await get('design-prompt').fire('input');get('open-structure-studio').onclick();geometry.push({kind:'display',value:{fixture:'structure caffeine'}});get('open-design-studio').onclick();assert.equal(geometry.at(-1).kind,'clear');assert.match(geometry.at(-1).message,/design study/);});
 await scenario('a background design result preserves the Structure viewport',async()=>{let invalidations=0;document.addEventListener('structure-selection-changed',()=>{invalidations++;});const pending=defer('/api/design/run'),running=get('run-design-model').onclick();get('open-structure-studio').onclick();geometry.push({kind:'display',value:{fixture:'structure-selected'}});const before=geometry.length;pending.finish(fixture(112));await running;assert.equal(geometry.length,before);assert.equal(invalidations,0);get('open-design-studio').onclick();assert.equal(geometry.at(-1).value.geometry_hash,hash(502));});
 await scenario('bootstrap loads its source without dispatching a sidebar click',async()=>{const bootElements=new Map(),bootGet=id=>{if(!bootElements.has(id))bootElements.set(id,new Element());return bootElements.get(id);};let compiled=0;const bootstrap=vm.createContext({workspace:null,$:bootGet,window:{},document:{querySelectorAll:()=>[],createElement:()=>{const node=new Element('button');node.click=()=>{throw Error('Bootstrap must not synthesize an example click');};return node;}},attachments:{},invalidate(){},compile:async()=>{compiled++;},refreshModel(){},api:async()=>({examples:[{name:'caffeine',source:'Complex caffeine source',attachments:{}}]})});vm.runInContext(app.split(/\r?\n/).find(line=>line.startsWith('async function start(')),bootstrap);await vm.runInContext('start()',bootstrap);assert.equal(bootGet('source').value,'Complex caffeine source');assert.equal(compiled,1);assert.equal(typeof bootGet('examples').children[0].onclick,'function');});
 await scenario('late export receipt cannot describe a different visible study',async()=>{await show(fixture());const pending=defer('/api/design/export'),saving=get('export-design').onclick();get('design-prompt').value+=' changed during export';await get('design-prompt').fire('input');pending.finish({reference:hash(100),path:'C:/old-study.json',file_sha256:hash(901)});await saving;assert.equal(get('design-export-status').textContent,'');assert.equal(get('export-design').disabled,true);});
 await scenario('export failures retain current evidence and permit retry',async()=>{await show(fixture());const pending=defer('/api/design/export'),saving=get('export-design').onclick();pending.finish({error:'DESIGN_EXPORT_EXISTS_WITH_DIFFERENT_CONTENT'},400);await saving;assert.match(get('design-export-status').textContent,/Export failed:.*DIFFERENT_CONTENT/);assert.equal(get('export-design').disabled,false);assert.equal(get('design-history').value,hash(100));await exportRecord(fixture());});
 await scenario('mismatched export receipt is rejected without a saved-file claim',async()=>{await show(fixture());const pending=defer('/api/design/export'),saving=get('export-design').onclick();pending.finish({reference:hash(999),path:'C:/other-study.json',file_sha256:hash(999)});await saving;assert.match(get('design-export-status').textContent,/Export failed:.*does not match/);assert.doesNotMatch(get('design-export-status').textContent,/Saved locally:/);});
 await scenario('candidate preview change does not strand a saved-record export',async()=>{await show(fixture());const pending=defer('/api/design/export'),saving=get('export-design').onclick();get('design-candidate-select').value=hash(1);get('design-candidate-select').onchange();pending.finish({reference:hash(100),path:'C:/same-study.json',file_sha256:hash(902)});await saving;assert.match(get('design-export-status').textContent,/Saved locally: C:\/same-study.json/);assert.equal(get('export-design').disabled,false);assert.equal(get('design-candidate-select').value,hash(1));});
 for (const format of ['csv','json']) await scenario('interface '+format+' export saves exact bound samples through the host',async()=>{
  const value=fixture(120);value.interfaces[0].result_hash=hash(920);await show(value);get('interface-tabs').children[0].onclick();
  const view=get('interface-view'),buttons=view.querySelectorAll('button'),save=buttons.find(item=>item.getAttribute('aria-label')===(format==='csv'?'Export all interface samples as CSV':'Export interface result and provenance as JSON'));
  const slider=view.querySelectorAll('input').find(item=>item.getAttribute('aria-label')==='Retained time sample');slider.value='1';await slider.fire('input');
  const pending=defer('/api/design/export-interface'),saving=save.click();await settle();
  assert.deepEqual(requests.at(-1).payload,{reference:hash(120),result_hash:hash(920),format,sample_index:1});assert.equal(save.disabled,true);
  const before=requests.length;await save.click();assert.equal(requests.length,before,'Repeated clicks cannot duplicate an in-flight save');
  slider.value='0';await slider.fire('input');
  pending.finish({reference:hash(120),result_hash:hash(920),format,sample_index:1,row_count:2,path:'C:/bound-interface.'+format,file_sha256:hash(921)});await saving;
  assert.match(view.textContent,/Saved locally: C:\/bound-interface/);assert.match(view.textContent,/All 2 retained samples; selected sample 2/);assert.equal(save.disabled,false);assert.equal(downloads.length,0);
 });
 await scenario('late interface save cannot describe a newly selected candidate',async()=>{
  const value=fixture(121);value.interfaces[0].result_hash=hash(920);await show(value);get('interface-tabs').children[0].onclick();
  const view=get('interface-view'),save=view.querySelectorAll('button').find(item=>item.getAttribute('aria-label')==='Export all interface samples as CSV');
  const pending=defer('/api/design/export-interface'),saving=save.click();await settle();get('design-candidate-select').value=hash(1);get('design-candidate-select').onchange();
  pending.finish({reference:hash(121),result_hash:hash(920),format:'csv',sample_index:0,row_count:2,path:'C:/previous-pair.csv',file_sha256:hash(921)});await saving;
  assert.match(view.textContent,/No simulation is bound/);assert.doesNotMatch(view.textContent,/Saved locally|previous-pair/);
 });
 for (const mismatch of ['reference','result_hash','format','sample_index','row_count','file_sha256']) await scenario('interface export rejects a mismatched '+mismatch+' receipt',async()=>{
  const value=fixture(122);value.interfaces[0].result_hash=hash(920);await show(value);get('interface-tabs').children[0].onclick();
  const view=get('interface-view'),save=view.querySelectorAll('button').find(item=>item.getAttribute('aria-label')==='Export all interface samples as CSV');
  const pending=defer('/api/design/export-interface'),saving=save.click();await settle();
  const receipt={reference:hash(122),result_hash:hash(920),format:'csv',sample_index:0,row_count:2,path:'C:/mismatched.csv',file_sha256:hash(921)};receipt[mismatch]='mismatched';pending.finish(receipt);await saving;
  assert.match(view.textContent,/Export unavailable:.*does not match/);assert.doesNotMatch(view.textContent,/Saved locally:/);assert.equal(save.disabled,false);
 });
 await scenario('interface export server failure leaves exact response available and permits retry',async()=>{
  const value=fixture(123);value.interfaces[0].result_hash=hash(920);await show(value);get('interface-tabs').children[0].onclick();
  const view=get('interface-view'),save=view.querySelectorAll('button').find(item=>item.getAttribute('aria-label')==='Export all interface samples as CSV');
  const pending=defer('/api/design/export-interface'),saving=save.click();await settle();pending.finish({error:'DESIGN_EXPORT_WRITE_VERIFICATION_FAILED'},400);await saving;
  assert.match(view.textContent,/Export unavailable:.*WRITE_VERIFICATION_FAILED/);assert.equal(save.disabled,false);assert.match(view.textContent,/Exact sample table/);
 });
 const numericTokens='[1.0,-0.0,1e-6,9007199254740993,1.234567890123456789]';
 const exactStudyText=JSON.stringify({...study,interface_parameters:{mode:'supplied',specifications:[{sentinel:'PRESERVE_NUMERIC_TOKENS'}]}}).replace('"PRESERVE_NUMERIC_TOKENS"',numericTokens);
 const exactRecordText=value=>JSON.stringify(value).replace(JSON.stringify(value.request.study),exactStudyText);
 const assertNumericTokens=text=>assert.ok(text.replace(/\s/g,'').includes(numericTokens),text.slice(0,500));
 await scenario('saved study restoration retains original number tokens while display values remain numeric',async()=>{
  const value=fixture(124),pending=defer('/api/design/read');get('design-history').value=value.record_hash;const loading=get('design-history').onchange();pending.finishText(exactRecordText(value));await loading;
  assertNumericTokens(get('design-study-input').value);assert.equal(get('design-organic-count').textContent,'2');assert.match(get('design-interface-count').textContent,/3/);
 });
 await scenario('candidate references and metadata controls preserve opaque supplied numeric tokens',async()=>{
  get('design-candidate-select').value=hash(1);get('design-candidate-select').onchange();get('design-prompt').value+=' preserve exact supplied inputs';await get('design-prompt').fire('input');assertNumericTokens(get('design-study-input').value);assert.equal(JSON.parse(get('design-study-input').value).selected_candidates.organic_hash,hash(1));
  get('design-parameter-mode').value='supplied';await get('design-parameter-mode').fire('change');assertNumericTokens(get('design-study-input').value);
  get('design-comparison-objective').value='solid_liquid';await get('design-comparison-objective').fire('change');assertNumericTokens(get('design-study-input').value);
 });
 for(const kind of ['direct','model'])await scenario(kind+' transport preserves exact input number tokens without changing the server contract',async()=>{
  get('design-study-input').value=exactStudyText;await get('design-study-input').fire('input');get('design-workflow').value='interface_design';await get('design-workflow').fire('change');
  const pending=defer('/api/design/run'),running=get(kind==='direct'?'run-design-direct':'run-design-model').onclick();assertNumericTokens(requests.at(-1).body);assert.deepEqual(Object.keys(requests.at(-1).payload).sort(),['decision','mode','prompt','study']);pending.finish(fixture(125));await running;
 });
 await scenario('import restoration retains host-returned number text for the next submitted study',async()=>{
  const value=fixture(126),raw=exactRecordText(value),pending=defer('/api/design/import');get('import-design-file').files=[{size:raw.length,text:async()=>raw}];const loading=get('import-design-file').onchange();await settle();pending.finishText(raw);await loading;assertNumericTokens(get('design-study-input').value);assert.match(get('design-status').textContent,/origin unverified/);
 });
 console.log(`Design Studio UI: ${checks.length} lifecycle and evidence scenarios passed.`);
 console.log(JSON.stringify(checks));
})().catch(error=>{console.error(error);process.exitCode=1;});
