'use strict';
// Actual shipped handlers and projection validator; synthetic transport and
// a product-generated view of the retained 34-atom complex fixture only.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '..');
assert.ok(process.argv[2], 'Pass the pure Python-generated 34-atom projection fixture');
const fixture = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));
assert.equal(fixture.spec.geometry.atoms.length, 34);
assert.equal(fixture.view.evidence_origin, 'synthetic_validation');
const elements = new Map(), listeners = new Map(), requests = [], queued = new Map(), timers = new Map(), downloads = [];
const objectURLs = new Map(), downloadCleanups = [];
let shown = null, timerId = 0;
class Element {
  constructor(tag = 'div') { this.tagName = tag; this.children = []; this.attributes = {}; this.dataset = {}; this.style = {}; this.listeners = new Map(); this.value = ''; this.disabled = false; this.hidden = false; this._text = ''; this.classList = { add() {}, remove() {} }; }
  set id(value) { this.attributes.id = value; elements.set(value, this); } get id() { return this.attributes.id; }
  set className(value) { this.attributes.class = value; } get className() { return this.attributes.class || ''; }
  append(...nodes) { for (const item of nodes) { if (item instanceof Element) item.parent = this; this.children.push(item); } }
  prepend(item) { item.parent = this; this.children.unshift(item); }
  after(item) { if (this.parent) { const index = this.parent.children.indexOf(this); this.parent.children.splice(index + 1, 0, item); item.parent = this.parent; } }
  replaceChildren(...nodes) { this.children = []; this._text = ''; this.append(...nodes); }
  set textContent(value) { this.children = []; this._text = String(value); } get textContent() { return this._text + this.children.map(item => item.textContent ?? item).join(''); }
  set innerHTML(value) { this.replaceChildren(); parse(value, this); }
  setAttribute(name, value) { this.attributes[name] = String(value); if (name === 'id') this.id = value; if (name === 'value') this.value = String(value); if (name === 'disabled') this.disabled = true; if (name === 'hidden') this.hidden = true; if (name.startsWith('data-')) this.dataset[name.slice(5)] = String(value); }
  getAttribute(name) { return this.attributes[name]; }
  addEventListener(type, listener) { if (!this.listeners.has(type)) this.listeners.set(type, []); this.listeners.get(type).push(listener); }
  async fire(type) { const event = { type, target: this }; for (const listener of this.listeners.get(type) || []) await listener(event); return this['on' + type]?.(event); }
  click() { if (this.tagName === 'a') { assert.equal(this.parent, body); const raw = objectURLs.get(this.href).parts.join(''); downloads.push({ raw, value: JSON.parse(raw), name: this.download }); return; } return this.fire('click'); }
  remove() { if (this.parent) this.parent.children.splice(this.parent.children.indexOf(this), 1); this.parent = null; }
  get options() { return this.querySelectorAll('option'); }
  querySelector(selector) { return this.querySelectorAll(selector)[0] || null; }
  querySelectorAll(selector) { const found = []; const visit = parent => { for (const child of parent.children) { if (!(child instanceof Element)) continue; if (selector.startsWith('.') ? child.className.split(' ').includes(selector.slice(1)) : selector === 'tr[data-candidate]' ? child.tagName === 'tr' && child.dataset.candidate !== undefined : child.tagName === selector) found.push(child); visit(child); } }; visit(this); return found; }
}
function parse(html, parent) { const stack = [parent]; for (const token of html.match(/<[^>]+>|[^<]+/g) || []) { if (token.startsWith('</')) { stack.pop(); continue; } if (token.startsWith('<')) { const tag = token.match(/^<([\w-]+)/)?.[1]; if (!tag) continue; const element = new Element(tag); for (const match of token.matchAll(/([\w-]+)(?:="([^"]*)")?/g)) { if (match.index !== 1) element.setAttribute(match[1], match[2] ?? ''); } stack.at(-1).append(element); if (!['input', 'br', 'hr', 'img'].includes(tag)) stack.push(element); } else stack.at(-1).append(token); } }
const body = new Element('body');
function get(id) { if (!elements.has(id)) { const element = new Element(); element.id = id; body.append(element); } return elements.get(id); }
const document = { body, createElement: tag => new Element(tag), createElementNS: (_, tag) => new Element(tag), getElementById: get, querySelector: selector => body.querySelector(selector), querySelectorAll: selector => body.querySelectorAll(selector),
  addEventListener(type, listener) { if (!listeners.has(type)) listeners.set(type, []); listeners.get(type).push(listener); }, dispatchEvent(event) { for (const listener of listeners.get(event.type) || []) listener(event); } };
const heading = new Element(); heading.className = 'heading'; heading.innerHTML = '<p class="eyebrow"></p><h1></h1><p class="subtitle"></p>'; body.append(heading);
for (const name of ['studio-grid', 'viewer-controls']) { const element = new Element(); element.className = name; body.append(element); }
for (const id of ['compile', 'examples', 'structure-select', 'filename', 'source-origin', 'editor-title']) get(id);
const hash = number => 'sha256:' + String(number).padStart(64, '0');
const selection = { run_ref: hash(100), candidate_hash: hash(1) };
const study = { version: 'design-study/v1', name: 'Complex 34-atom UI fixture', interface_parameters: { mode: 'none', specifications: [] } };
const candidate = number => ({ family: 'organic', id: 'complex_anchor_' + number, candidate_hash: hash(number), geometry: structuredClone(fixture.view.frames[0].scene), generation: { fragment_id: 'complex_anchor_' + number }, descriptors: {}, source: 'Synthetic UI source transport only' });
const design = { record_hash: selection.run_ref, state: 'completed', request: { study, prompt: 'Inspect this complex candidate' }, decision: { workflow: 'organic_design', message: 'Synthetic transport fixture' }, seconds: 0, trace: [], interfaces: [], selected_pair: { organic: hash(1) }, organic: { candidates: [candidate(1), candidate(2)], candidate_count: 2, attempted_count: 2, rejected: [], ranking: {}, limitations: ['Synthetic UI fixture'] }, inorganic: null };
const oxide = { family: 'inorganic', id: 'synthetic_oxide', formula: 'Synthetic oxide selection', candidate_hash: hash(3), geometry: structuredClone(fixture.view.frames[0].scene), descriptors: {} };
design.inorganic = { candidates: [oxide], candidate_count: 1, attempted_count: 1, rejected: [], ranking: {}, limitations: ['Synthetic transport selection only'] };
let saved = [];
const response = (value, code = 200) => ({ ok: code === 200, status: code, text: async () => JSON.stringify(value), json: async () => value });
function defer(url) { let finish; const promise = new Promise(resolve => { finish = resolve; }); const entry = { promise, finish: (value, code) => finish(response(value, code)) }; if (!queued.has(url)) queued.set(url, []); queued.get(url).push(entry); return entry; }
const context = vm.createContext({ document, console, structuredClone, TextEncoder, Event: function (type) { this.type = type; }, performance: { now: () => 0 },
  Blob: class { constructor(parts, options) { this.parts = parts; this.type = options.type; } }, URL: { createObjectURL(blob) { const id = 'blob:synthetic-' + objectURLs.size; objectURLs.set(id, blob); return id; }, revokeObjectURL(id) { objectURLs.delete(id); } },
  setTimeout: (callback, delay) => { const id = ++timerId; if (delay === 30000) downloadCleanups.push(callback); else timers.set(id, callback); return id; }, clearTimeout: id => timers.delete(id), setInterval: () => ++timerId, clearInterval() {},
  displayGeometry: geometry => { shown = { geometry, scale: 1 }; }, clearGeometry: () => { shown = null; }, getDisplayedGeometry: () => shown,
  fetch: async (url, options) => { const payload = options.body ? JSON.parse(options.body) : null; requests.push({ url, payload }); const pending = queued.get(url)?.shift(); if (pending) return pending.promise;
    if (url === '/api/workflows') return response(saved);
    if (url === '/api/design/history') return response({ records: [], errors: [] });
    if (url === '/api/design/catalog') return response({ study, direct_decision: { action: 'run_workflow', workflow: 'organic_design', interfaces: [] } });
    if (url === '/api/model/status') return response({ display_name: 'Synthetic status; no model request' });
    throw Error('Unexpected transport: ' + url);
  } });
context.window = context;
const startupHistory = defer('/api/design/history');
for (const file of ['geometry-view-model.js', 'refinement-lab.js', 'design-studio.js']) vm.runInContext(fs.readFileSync(path.join(root, 'src/chem_workbench/web_assets', file), 'utf8'), context, { filename: file });
const settle = () => new Promise(resolve => setImmediate(resolve));
const ui = key => get('refinement-workflow-' + key);
function workflow(state = 'prepared', mode = 'gradient', selected = selection) {
  const planHash = hash(mode === 'gradient' ? 200 : 201);
  return { version: 'refinement-workflow/v1', reference: hash(mode === 'gradient' ? 300 : 301), selection: structuredClone(selected), source_hash: fixture.spec.source_binding.source_hash, resolved_plan_hash: planHash, state, refinement_view: null,
    plan: { version: 'governed-refinement-plan/v1', kind: 'molecular_refinement', mode, resolved_plan_hash: planHash, method_profile_id: fixture.spec.profile.profile_id, subject: { selection: structuredClone(selected) }, spec: structuredClone(fixture.spec), resource_ceilings: { memory_bytes: 8 * 1024 ** 3, cpu_seconds: 14400, threads: 4, wall_seconds: 7200, max_output_bytes: 20 * 1024 ** 2 }, disk_budget: { max_run_bytes: 100 * 1024 ** 3, max_entries: 10000, minimum_free_bytes: 10 * 1024 ** 3, scan_timeout_seconds: 2, interval_seconds: 1 } } };
}
function completed() { const value = workflow('succeeded'); value.result = { mode: value.plan.mode, resolved_plan_hash: value.resolved_plan_hash, execution_status: 'succeeded', evidence_eligible: true, scientific_state: 'incomplete', scientific_result: structuredClone(fixture.scientific_result), summary: 'One synthetic gradient; no optimization or minimum claim.' }; value.refinement_view = structuredClone(fixture.view); return value; }
async function showDesign(record = design) { const pending = defer('/api/design/read'); get('design-history').value = record.record_hash; const reading = get('design-history').onchange(); pending.finish(record); await reading; await settle(); }
async function action(key, value, code = 200) { const url = key === 'prepare' || key === 'approve' ? '/api/workflow/refinement/' + key : '/api/workflow/' + key; const pending = defer(url), call = ui(key).click(); pending.finish(value, code); await call; await settle(); return requests.filter(item => item.url === url).at(-1); }
async function load(value) { saved = [value]; await ui('refresh').click(); await settle(); const pending = defer('/api/workflow/read'); ui('history').value = value.reference; const reading = ui('history').fire('change'); pending.finish(value); await reading; await settle(); }
function switchCandidate(number) { get('design-candidate-select').value = hash(number); get('design-candidate-select').onchange(); }
const checks = [];
async function scenario(name, run) { try { await run(); checks.push(name); } catch (error) { error.message = name + ': ' + error.message; throw error; } }
(async () => {
  await settle();
  await scenario('no candidate cannot prepare or approve', async () => { assert.equal(ui('prepare').disabled, true); assert.equal(ui('approve').disabled, true); assert.equal(ui('submit').disabled, true); });
  await scenario('persistent index merges after a current study without replacing its selection or scene', async () => { await showDesign(); const previous = shown, selected = get('design-history').value; startupHistory.finish({ records: [{ record_hash: hash(501), name: 'Earlier complex study', state: 'completed' }, { record_hash: design.record_hash, name: study.name, state: 'completed' }], errors: [{ filename: 'damaged-study.json', error: 'HASH_MISMATCH' }] }); await settle(); assert.equal(shown, previous); assert.equal(get('design-history').value, selected); assert.equal(get('design-history').options.filter(option => option.value === design.record_hash).length, 1); assert.equal(get('design-history').options.some(option => option.value === hash(501)), true); assert.match(get('design-history-status').textContent, /damaged-study.json.*HASH_MISMATCH/); assert.equal(ui('prepare').disabled, false); });
  await scenario('persistent study opens through read with no import or generation request', async () => { const old = structuredClone(design); old.record_hash = hash(501); old.request.prompt = 'Preserved earlier complex study'; const pending = defer('/api/design/read'), before = requests.length; get('design-history').value = hash(501); const opening = get('design-history').onchange(); pending.finish(old); await opening; await settle(); assert.deepEqual(requests.filter(item => item.url === '/api/design/read').at(-1).payload, { reference: hash(501) }); assert.equal(requests.slice(before).some(item => ['/api/design/import', '/api/design/run', '/api/workflow/refinement/prepare'].includes(item.url)), false); assert.equal(get('design-prompt').value, old.request.prompt); assert.equal(get('design-history').value, hash(501)); assert.equal(shown.geometry.atoms.length, 34); });
  await scenario('late persistent read respects the existing edited-study generation', async () => { const pending = defer('/api/design/read'); get('design-history').value = hash(501); const opening = get('design-history').onchange(); get('design-prompt').value = 'New objective during historical read'; await get('design-prompt').fire('input'); pending.finish({ ...design, record_hash: hash(501) }); await opening; assert.equal(get('design-prompt').value, 'New objective during historical read'); assert.equal(ui('prepare').disabled, true); assert.equal(shown, null); });
  await scenario('actual Design selection produces only selection and mode', async () => { await showDesign(); assert.match(ui('subject').textContent, /34 atoms/); const request = await action('prepare', workflow()); assert.deepEqual(request.payload, { selection, mode: 'gradient' }); assert.equal(ui('approve').disabled, false); assert.equal(ui('submit').disabled, true); assert.match(ui('plan').textContent, /7200/); assert.equal(ui('result').querySelectorAll('svg').length, 0); });
  await scenario('approval never dispatches a worker and contains only reference', async () => { const before = requests.filter(item => item.url === '/api/workflow/submit').length; const request = await action('approve', workflow('approved')); assert.deepEqual(request.payload, { reference: hash(300) }); assert.equal(requests.filter(item => item.url === '/api/workflow/submit').length, before); assert.equal(ui('submit').disabled, false); });
  await scenario('running status uses polling without invented energies', async () => { await action('submit', workflow('running')); assert.equal(ui('cancel').disabled, false); assert.equal(ui('submit').disabled, true); assert.equal(timers.size, 1); assert.equal(ui('result').querySelectorAll('svg').length, 0); assert.match(ui('status').textContent, /only after the host commits/); });
  await scenario('cancel requests teardown and reads a retained terminal failure', async () => { const pending = defer('/api/workflow/cancel'), read = defer('/api/workflow/read'); const cancelling = ui('cancel').click(); assert.equal(ui('cancel').disabled, true); pending.finish({ requested: true }); await settle(); const value = workflow('cancelled'); value.result = { mode: value.plan.mode, resolved_plan_hash: value.resolved_plan_hash, execution_status: 'cancelled', evidence_eligible: false, scientific_state: 'incomplete', summary: 'Synthetic retained cancellation' }; read.finish(value); await cancelling; assert.match(ui('state').textContent, /cancelled/); assert.match(ui('status').textContent, /Evidence eligible: no/); assert.equal(timers.size, 0); assert.equal(ui('result').querySelectorAll('svg').length, 0); });
  await scenario('host projection uses real 34-atom product validation and single gradient remains incomplete', async () => { await showDesign(); await load(completed()); assert.match(ui('status').textContent, /Scientific state: incomplete/); assert.match(ui('result').textContent, /Synthetic validation/); assert.match(ui('result').textContent, /Minimum: not evaluated/); assert.equal(ui('result').querySelectorAll('svg').length, 1); const show = ui('result').querySelectorAll('button').find(item => item.textContent === 'Show evaluation in 3D'); await show.click(); assert.equal(shown.geometry.atoms.length, 34); assert.equal(shown.geometry.refinement_binding.result_hash, fixture.view.result_hash); await ui('export').click(); assert.equal(downloads.at(-1).value.refinement_view.view_hash, fixture.view.view_hash); });
  await scenario('candidate switch removes only the old owned scene and detaches controls', async () => { switchCandidate(2); await settle(); assert.equal(shown.geometry.refinement_binding.result_hash, fixture.view.result_hash, 'The synthetic candidate preview reuses the fixture scene only for shape'); assert.equal(ui('result').querySelectorAll('svg').length, 0); assert.equal(ui('approve').disabled, true); assert.match(ui('subject').textContent, /complex anchor 2/); });
  for (const key of ['prepare', 'approve', 'submit']) await scenario('late ' + key + ' response cannot replace another candidate', async () => { await showDesign(); if (key !== 'prepare') await action('prepare', workflow()); if (key === 'submit') await action('approve', workflow('approved')); const url = key === 'submit' ? '/api/workflow/submit' : '/api/workflow/refinement/' + key; const pending = defer(url), call = ui(key).click(); switchCandidate(2); pending.finish(workflow(key === 'prepare' ? 'prepared' : key === 'approve' ? 'approved' : 'running')); await call; await settle(); assert.match(ui('subject').textContent, /complex anchor 2/); assert.equal(ui('submit').disabled, true); assert.equal(ui('approve').disabled, true); assert.equal(timers.size, 0); });
  await scenario('mode change discards old approval and requests explicit optimization', async () => { await showDesign(); await action('prepare', workflow()); await action('approve', workflow('approved')); ui('mode').value = 'optimization'; await ui('mode').fire('change'); assert.equal(ui('submit').disabled, true); const request = await action('prepare', workflow('prepared', 'optimization')); assert.deepEqual(request.payload, { selection, mode: 'optimization' }); });
  await scenario('wrong selected candidate response is rejected before approval', async () => { await showDesign(); const value = workflow('prepared', 'gradient', { ...selection, candidate_hash: hash(2) }); ui('mode').value = 'gradient'; await ui('mode').fire('change'); await action('prepare', value); assert.match(ui('status').textContent, /does not match/); assert.equal(ui('approve').disabled, true); });
  await scenario('scientific view from a different committed result is rejected', async () => { await showDesign(); const value = completed(); value.refinement_view.result_hash = hash(987); await load(value); assert.match(ui('status').textContent, /does not match the committed result/); assert.equal(ui('result').querySelectorAll('svg').length, 0); });
  await scenario('tampered actual coordinate projection is rejected', async () => { await showDesign(); const value = completed(); value.refinement_view.frames[0].scene.atoms[0].position[0] += 1; await load(value); assert.match(ui('status').textContent, /does not match/); assert.equal(ui('result').querySelectorAll('svg').length, 0); });
  await scenario('poll response after study edit cannot restore stale evidence or timer', async () => { await showDesign(); await action('prepare', workflow('running')); const pending = defer('/api/workflow/read'); const callback = [...timers.values()][0]; timers.clear(); callback(); get('design-prompt').value += ' changed'; await get('design-prompt').fire('input'); pending.finish(completed()); await settle(); assert.equal(ui('prepare').disabled, true); assert.equal(ui('result').querySelectorAll('svg').length, 0); assert.equal(timers.size, 0); });
  await scenario('inorganic selection cannot refine the old organic candidate', async () => { await showDesign(); switchCandidate(3); assert.equal(ui('prepare').disabled, true); assert.equal(ui('approve').disabled, true); });
  await scenario('Studio switch cancels stale response rendering and restores candidate preview', async () => { await showDesign(); const pending = defer('/api/workflow/refinement/prepare'), call = ui('prepare').click(); await get('open-structure-studio').click(); const structure = { geometry_hash: hash(999), atoms: [] }; context.displayGeometry(structure); pending.finish(workflow()); await call; assert.equal(shown.geometry, structure); assert.equal(ui('approve').disabled, true); await get('open-design-studio').click(); await settle(); assert.equal(shown.geometry.atoms.length, 34); });
  await scenario('host preparation failure keeps its actual message and never enables approval', async () => { await showDesign(); await action('prepare', { error: 'MISSING_NATIVE_OBSERVATION: selected element has no bound basis observation' }, 400); assert.match(ui('status').textContent, /MISSING_NATIVE_OBSERVATION/); assert.equal(ui('approve').disabled, true); assert.equal(ui('submit').disabled, true); });
  await scenario('missing resource policy cannot receive approval', async () => { await showDesign(); const value = workflow(); delete value.plan.resource_ceilings.memory_bytes; await action('prepare', value); assert.match(ui('status').textContent, /resource policy/); assert.equal(ui('approve').disabled, true); });
  await scenario('uncommitted failed submission retains original failure without success view', async () => { await showDesign(); const value = workflow('failed'); value.failure = 'APPROVAL_EXPIRED: synthetic retained host exception'; await load(value); assert.match(ui('status').textContent, /APPROVAL_EXPIRED/); assert.match(ui('status').textContent, /No committed scientific result/); assert.equal(ui('result').querySelectorAll('svg').length, 0); });
  await scenario('mismatched execution mode cannot reuse a valid scientific projection', async () => { await showDesign(); const value = completed(); value.result.mode = 'optimization'; await load(value); assert.match(ui('status').textContent, /does not match this plan/); assert.equal(ui('export').disabled, true); });
  await scenario('a failed read cannot reuse an old approved action', async () => { await showDesign(); await action('prepare', workflow()); await action('approve', workflow('approved')); const pending = defer('/api/workflow/read'), reading = ui('refresh').click(); pending.finish({ error: 'EVIDENCE_CORRUPT: synthetic changed source' }, 400); await reading; assert.equal(ui('submit').disabled, true); assert.equal(ui('approve').disabled, true); assert.equal(ui('refresh').disabled, false); });
  await scenario('late history listing cannot leak another candidate refinements', async () => { await showDesign(); const pending = defer('/api/workflows'), refreshing = ui('refresh').click(); switchCandidate(2); pending.finish([workflow()]); await refreshing; await settle(); assert.equal(ui('history').options.some(option => option.value === hash(300)), false); });
  await scenario('disposing a view clears its exact owned viewport', async () => { const host = new Element(); body.append(host); const controller = context.ChemRefinementLab.renderRefinementView(host, structuredClone(fixture.view)); await host.querySelectorAll('button').find(item => item.textContent === 'Show evaluation in 3D').click(); const previous = shown; assert.ok(previous); controller.dispose(); assert.equal(shown, null); assert.equal(controller.selectEvaluation(0), false); });
  await scenario('disposing an old view preserves a newer scene with identical geometry hash', async () => { const host = new Element(); body.append(host); const controller = context.ChemRefinementLab.renderRefinementView(host, structuredClone(fixture.view)); await host.querySelectorAll('button').find(item => item.textContent === 'Show evaluation in 3D').click(); context.displayGeometry(structuredClone(shown.geometry)); const newer = shown; controller.dispose(); assert.equal(shown, newer); });
  console.log(`Design refinement UI: ${checks.length} scenarios passed. No native calculations or model requests.`);
})().catch(error => { console.error(error); process.exitCode = 1; });
