"""Descriptor-only adapter contracts and the package-owned static registry."""

from chem_workbench.adapters.model import (
    AdapterType,
    ComputeAdapter,
    ConversionClassification,
    DataServiceConnector,
    ExportResult,
    FetchResult,
    FormatAdapter,
    FormatDirection,
    ImportResult,
    PermissionClass,
    SemanticComparison,
)
from chem_workbench.adapters.registry import (
    AdapterRegistry,
    LossReportResolution,
    RegistryResolution,
    bundled_registry_document,
    load_bundled_registry,
    load_descriptor_bytes,
)
from chem_workbench.adapters.validation import (
    ADAPTER_MANIFEST_VERSION,
    ADAPTER_REGISTRY_VERSION,
    FORMAT_CAPABILITY_VERSION,
    LOSS_REPORT_VERSION,
    AdapterBindingError,
    AdapterContractError,
    PublicationDecision,
    assess_loss_report,
    canonical_format_capability_hash,
    canonical_manifest_hash,
    canonical_registry_hash,
    validate_adapter_manifest,
    validate_adapter_registry,
    validate_format_capability,
    validate_loss_report,
)

__all__ = [
    "ADAPTER_MANIFEST_VERSION",
    "ADAPTER_REGISTRY_VERSION",
    "FORMAT_CAPABILITY_VERSION",
    "LOSS_REPORT_VERSION",
    "AdapterBindingError",
    "AdapterContractError",
    "AdapterRegistry",
    "AdapterType",
    "ComputeAdapter",
    "ConversionClassification",
    "DataServiceConnector",
    "ExportResult",
    "FetchResult",
    "FormatAdapter",
    "FormatDirection",
    "ImportResult",
    "LossReportResolution",
    "PermissionClass",
    "PublicationDecision",
    "RegistryResolution",
    "SemanticComparison",
    "assess_loss_report",
    "bundled_registry_document",
    "canonical_format_capability_hash",
    "canonical_manifest_hash",
    "canonical_registry_hash",
    "load_bundled_registry",
    "load_descriptor_bytes",
    "validate_adapter_manifest",
    "validate_adapter_registry",
    "validate_format_capability",
    "validate_loss_report",
]
