const $ = id => document.getElementById(id);
let workspace, result, selectedTab='overview', revision=0, busy=false, attachments={}, agentBusy=false, agentRecord=null, currentPlan=null, modelReady=false,viewportGeneration=0,lastViewportFingerprint=null;
const escapeHTML = value => String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,body){const response=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const value=await response.json();if(!response.ok){const error=Error(value.error||`Request failed (${response.status})`);error.status=response.status;error.response=value;throw error;}return value;}
function displayedGeometryState(){return window.getDisplayedGeometry?.()||(typeof shownGeometry!=='undefined'?shownGeometry:null);}
function viewportBindingFingerprint(){const displayed=displayedGeometryState();return JSON.stringify(displayed?{geometry:displayed.geometry,scale:displayed.scale}:null);}
document.addEventListener('geometry-display-changed',()=>{const fingerprint=viewportBindingFingerprint();if(fingerprint!==lastViewportFingerprint){viewportGeneration++;lastViewportFingerprint=fingerprint;}});
function sourcePayload(){return {source:$('source').value,attachments};}
function lines(){const count=$('source').value.split('\n').length;$('lines').textContent=Array.from({length:count},(_,i)=>i+1).join('\n');$('line-count').textContent=`UTF-8 · ${count} lines`;$('attachments-label').textContent=`${Object.keys(attachments).length} CIF attachments`;}
function updateActions(){$('orchestrate').disabled=agentBusy||!result?.success||!modelReady;$('direct-plan').disabled=agentBusy||!result?.scene?.structures.length;}
function invalidate(){document.dispatchEvent(new Event("workspace-changed"));$('source-origin').textContent='EDITED SOURCE';revision++;result=null;agentRecord=null;currentPlan=null;$('dirty').textContent='Uncompiled edits';$('status').textContent='Needs compile';$('status-detail').textContent='Source changed · previous outputs invalidated';$('object-count').textContent=$('diagnostic-count').textContent='—';$('diagnostics').textContent='Compile to inspect diagnostics for this source.';$('diagnostics-badge').textContent='—';$('download').disabled=$('download-review').disabled=true;$('candidate-panel').hidden=true;$('download-agent').hidden=true;$('agent-output').innerHTML='<div class="agent-empty"><span>↗</span><h3>Intent, meet a bounded workflow.</h3><p>Compile the current source, then ask the local model to inspect it or prepare a candidate batch.</p></div>';$('agent-progress').textContent=agentBusy?'Source changed. The outstanding response will be discarded.':'';$('structure-select').replaceChildren();$('unavailable-geometry').textContent='';clearGeometry();updateActions();lines();render();}
function render(){
 if(selectedTab==='registry'){$('result').innerHTML=`<pre>${escapeHTML(JSON.stringify(workspace?.registry,null,2))}</pre>`;return;}
 if(!result){$('result').innerHTML='<div class="summary"><strong>Ready when you are.</strong><p>Compile the current source to create bound ChemIR and review artifacts.</p></div>';return;}
 if(selectedTab!=='overview'){$('result').innerHTML=`<pre>${escapeHTML(JSON.stringify(selectedTab==='ir'?result.document:result.review,null,2))}</pre>`;return;}
 const objects=result.document?.objects||[];
 $('result').innerHTML=`<div class="summary"><strong>${result.success?'✓ Declaration compilation passed':'Compilation rejected'}</strong><p>${result.success?'Declarations and supplied CIF imports checked. No scientific calculation was executed.':'Correct the diagnostics below. No artifacts are available.'}</p></div><div class="object-list">${objects.map(o=>`<div class="object-row"><strong>${escapeHTML(o.id)}</strong><span>${escapeHTML(o.kind)}</span></div>`).join('')}</div><p class="hash-label">SOURCE SHA-256</p><div class="hash">${escapeHTML(result.source_sha256)}</div>`;
}
function populateScene(){
 const previous=$('structure-select').value,scene=result?.scene;$('structure-select').replaceChildren();
 for(const structure of scene?.structures||[]){const option=document.createElement('option');option.value=structure.object_id;option.textContent=structure.object_id;$('structure-select').append(option);}
 $('unavailable-geometry').textContent=(scene?.unavailable||[]).map(s=>`${s.object_id}: ${s.reason}`).join(' · ');
 const geometry=scene?.structures.find(structure=>structure.object_id===previous)||scene?.structures[0];
 $('structure-select').value=geometry?.object_id||'';
 if(previous!==$('structure-select').value)document.dispatchEvent(new Event('structure-selection-changed'));
 if(document.body?.dataset?.studio==='design'){document.dispatchEvent(new Event('structure-compiled-background'));return;}
 if(geometry)restoreSelectedStructure();else{if(typeof clearLabSelection==='function')clearLabSelection();clearGeometry('No admitted coordinates. Supply a supported CIF attachment or a valid connected molecular SMILES.');}
}
async function compile(){if(busy)return;busy=true;const current=revision;$('compile').disabled=true;$('status').textContent='Compiling…';
 try{const value=await api('/api/compile',sourcePayload());if(current!==revision)return;result=value;$('status').textContent=value.success?'Passed':'Needs attention';$('status-detail').textContent=value.success?'Compiled · no calculation executed':'Current source contains errors';$('object-count').textContent=value.document?.objects?.length??0;$('diagnostic-count').textContent=$('diagnostics-badge').textContent=value.diagnostics.length;$('dirty').textContent=value.success?'Artifacts in sync':'Checked · no artifacts';$('download').disabled=$('download-review').disabled=!value.success;$('diagnostics').replaceChildren();
 if(!value.diagnostics.length)$('diagnostics').textContent='✓ No compiler diagnostics. Scientific review and execution approval remain separate.';
 for(const d of value.diagnostics){const button=document.createElement('button');button.className='diag';button.textContent=`${d.severity.toUpperCase()} · ${d.code} · ${d.line}:${d.column} — ${d.message} ${d.suggestion}`;button.onclick=()=>{const offset=$('source').value.split('\n').slice(0,d.line-1).reduce((n,s)=>n+s.length+1,0)+d.column-1;$('source').focus();$('source').setSelectionRange(offset,offset+1);};$('diagnostics').append(button);}
 $('connection').textContent='Local compiler connected';populateScene();render();
 }catch(error){if(current===revision){result=null;$('status').textContent='Request failed';$('status-detail').textContent=error.message;$('download').disabled=$('download-review').disabled=true;$('connection').textContent='Request failed · retry available';clearGeometry(error.message);render();}}
 finally{busy=false;$('compile').disabled=false;updateActions();}
}
function download(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)+'\n'],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function refreshModel(){$('model-status').textContent='Checking LM Studio…';try{const status=await api('/api/model/status');modelReady=status.available;$('model-name').textContent=status.display_name||status.key||'Local model';$('model-status').textContent=status.available?`Connected · ${status.quantization?.name||'Local model'} · local`:status.message;$('model-status').className=status.available?'model-ready':'';}catch(error){modelReady=false;$('model-status').textContent=error.message;}updateActions();}
function showPlan(plan){currentPlan=plan;$('candidate-panel').hidden=false;$('candidate-scales').replaceChildren();for(const candidate of plan.candidates){const button=document.createElement('button');button.textContent=Number(candidate.scale).toFixed(2)+'×';button.onclick=()=>{const geometry=result?.scene?.structures.find(s=>s.object_id===plan.subject_ref);if(geometry){$('structure-select').value=plan.subject_ref;if(typeof displayPlanCandidate==='function')displayPlanCandidate(plan,candidate);else displayGeometry(geometry,Number(candidate.scale));$('candidate-scales').querySelectorAll('button').forEach(b=>b.classList.toggle('selected',b===button));}};$('candidate-scales').append(button);}}
async function propose(useModel){if(agentBusy||!result?.success)return;agentBusy=true;updateActions();const current=revision,requestView=viewportBindingFingerprint(),requestGeneration=viewportGeneration,requestSelection=$('structure-select').value,requestSource=JSON.stringify(sourcePayload());const responseCurrent=()=>current===revision&&requestGeneration===viewportGeneration&&requestView===viewportBindingFingerprint()&&requestSelection===$('structure-select').value&&requestSource===JSON.stringify(sourcePayload());$('agent-progress').textContent=useModel?`PROPOSING · Waiting for ${$('model-name').textContent||'the selected local model'}. The host enforces a bounded proposal.`:'PREFLIGHT · Preparing a source-bound review proposal.';$('candidate-panel').hidden=true;$('download-agent').hidden=true;currentPlan=null;agentRecord=null;$('agent-output').replaceChildren();
 try{let record;if(useModel){record=await api('/api/orchestrate',{...sourcePayload(),objective:$('objective').value});}else{const object=result.scene.structures.find(s=>s.object_id===$('structure-select').value)||result.scene.structures[0];const tool=object.kind==='PeriodicStructure'?'plan_cu_lattice_scan':'plan_molecular_single_point';const args={object_id:object.object_id};if(tool==='plan_cu_lattice_scan')args.scale_factors=[.98,1,1.02];const output=await api('/api/tool',{...sourcePayload(),tool,arguments:args});record={state:'DRAFT_PREPARED',trace:[{action:{action:tool},output}],interpretation_draft:'',execution_authorized:false};}if(!responseCurrent()){$('agent-progress').textContent='Workspace or displayed geometry changed. The outstanding proposal was discarded.';return;}agentRecord=record;$('agent-progress').textContent=`${record.state} · ${record.trace.length} tool call(s) · No compute executed`;
 const trace=document.createElement('div');trace.className='tool-trace';for(const [index,item] of record.trace.entries()){const row=document.createElement('div');row.className='tool-step';row.innerHTML=`<span class="step-number">${index+1}</span><div><strong>${escapeHTML(item.action.action)}</strong><small>${escapeHTML(item.output.status)} · host validated</small></div>`;trace.append(row);if(item.output.error){const error=document.createElement('p');error.textContent=item.output.error;trace.append(error);}else{const details=document.createElement('details');const summary=document.createElement('summary');summary.textContent='Inspect tool output';const pre=document.createElement('pre');pre.textContent=JSON.stringify(item.output,null,2);details.append(summary,pre);trace.append(details);}if(item.action.action==='structure_preview'&&item.output.status==='succeeded')showPreviewGeometry(item.output.data);if(item.output.data?.version==='cu-scan-proposal/v1'){showPlan(item.output.data);document.dispatchEvent(new CustomEvent('copper-proposed'));}if(item.output.data?.version==='molecular-proposal/v1'){document.dispatchEvent(new CustomEvent('molecular-proposed',{detail:item.output.data}));}if(item.output.data?.version==='water-proposal/v1'){document.dispatchEvent(new CustomEvent('water-proposed',{detail:item.output.data}));}}$('agent-output').append(trace);
 if(record.host_report){const report=document.createElement('p');report.textContent='HOST REPORT · '+record.host_report.summary;$('agent-output').append(report);}
 if(record.requirements){const review=document.createElement('details');const summary=document.createElement('summary');summary.textContent='Review understood requirements';const p=document.createElement('p');p.textContent=record.requirements.request_summary;review.append(summary,p);for(const issue of record.requirements_issues||[]){const line=document.createElement('p');line.textContent=issue;review.append(line);}$('agent-output').append(review);}
 if(record.interpretation_draft){const draft=document.createElement('div');draft.className='model-draft';const label=document.createElement('span');label.textContent='MODEL INTERPRETATION · UNVERIFIED';const p=document.createElement('p');p.textContent=record.interpretation_draft;draft.append(label,p);$('agent-output').append(draft);}$('download-agent').hidden=false;
 }catch(error){if(responseCurrent()){$('agent-progress').textContent='BLOCKED · '+error.message;$('agent-output').textContent='No model result or execution has been substituted. Check the input or local model and retry.';}}
 finally{agentBusy=false;updateActions();}
}
$('compile').onclick=compile;$('source').oninput=invalidate;$('source').onscroll=()=>{$('lines').scrollTop=$('source').scrollTop;};
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();compile();}});
document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{selectedTab=button.dataset.tab;document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-selected',String(b===button)));render();});
$('download').onclick=()=>{if(result?.success)download(result.document,'workbench.chemir.json');};$('download-review').onclick=()=>{if(result?.success)download(result.review,'workbench.review.json');};
function showPreviewGeometry(preview){
 const geometry=result?.scene?.structures.find(item=>item.object_id===preview?.object_id&&item.geometry_hash===preview?.geometry_hash);
 if(geometry){$('structure-select').value=geometry.object_id;restoreSelectedStructure();return;}
 $('structure-select').value='';clearGeometry('The preview coordinate hash does not match an admitted structure in the current workspace. Compile again to review the requested geometry.');
}
function restoreSelectedStructure(){
 const selection=$('structure-select').value,lab=typeof selectedLabGeometry==='function'?selectedLabGeometry(selection):null;
 if(lab){showLabGeometry(lab,{preserveDraft:true});return;}
 const geometry=result?.scene?.structures?.find(item=>item.object_id===selection);
 if(typeof clearLabSelection==='function')clearLabSelection();
 if(geometry)displayGeometry(geometry);else clearGeometry('No coordinates are bound to this selection.');
}
$('structure-select').onchange=()=>{currentPlan=null;agentRecord=null;$('candidate-panel').hidden=true;document.dispatchEvent(new Event('structure-selection-changed'));restoreSelectedStructure();};
$('orchestrate').onclick=()=>propose(true);$('direct-plan').onclick=()=>propose(false);$('refresh-model').onclick=refreshModel;$('download-plan').onclick=()=>{if(currentPlan)download(currentPlan,'copper-scan.proposal.json');};$('download-agent').onclick=()=>{if(agentRecord)download(agentRecord,'workbench.orchestration.json');};
$('upload').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(window.confirmWorkspaceReplacement&&!window.confirmWorkspaceReplacement())return;if(file.size>200000){alert('Source files are limited to 200 KB.');return;}$('source').value=await file.text();attachments={};$('filename').textContent=$('editor-title').textContent=file.name;document.querySelectorAll('nav button').forEach(b=>b.classList.remove('active'));invalidate();};
$('cif-upload').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>200000){alert('CIF files are limited to 200 KB.');return;}const text=await file.text();attachments['structures/'+file.name]=text;attachments[file.name]=text;invalidate();$('attachments-label').textContent=`Attached ${file.name} (root + structures/)`;};
async function start(){try{workspace=await api('/api/workspace');for(const example of workspace.examples){const button=document.createElement('button');button.textContent='◇  '+example.name+'.chem';const loadExample=()=>{if(window.confirmWorkspaceReplacement&&!window.confirmWorkspaceReplacement())return;document.querySelectorAll('nav button').forEach(b=>b.classList.remove('active'));button.classList.add('active');$('source').value=example.source;attachments={...example.attachments};$('filename').textContent=$('editor-title').textContent=example.name+'.chem';invalidate();$('source-origin').textContent='BUNDLED FIXTURE';$('objective').value=['caffeine','aspirin'].includes(example.name)?`Prepare a source-generated conformer of ${example.name} for a neutral singlet HF/STO-3G single-point energy proposal in the gas phase at 0 K. Review only; do not execute.`:example.name==='fcc-copper'?'Propose a copper lattice scan at scales 0.98, 1.00 and 1.02. Explain what evidence is still needed.':'Inspect this structure and explain what review is still needed. Do not execute calculations.';};button.onclick=loadExample;$('examples').append(button);if(example.name==='caffeine')loadExample();}$('connection').textContent='Local compiler connected';await compile();}catch(error){$('status').textContent='Service unavailable';$('connection').textContent=error.message;}refreshModel();}
start();
