/* Prompt-selected design modules. Rendering always follows a saved study revision. */
(()=>{
 'use strict';
 const studyTexts=new WeakMap();
 function parseStudy(text){return JSON.parse(text,(_key,value,context)=>{if(typeof value!=='number')return value;if(typeof JSON.rawJSON!=='function'||typeof context?.source!=='string')throw Error('This browser cannot preserve exact study numbers. Open the current desktop Workbench or update the browser.');return JSON.rawJSON(context.source);});}
 // Keep numeric source tokens (including 1.0 and -0.0) across control edits and
 // requests. Parsed display values remain ordinary numbers; hashed inputs do not.
 async function api(path,body){
  const response=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});
  const text=await response.text();let value=JSON.parse(text);
  if(value?.version==='refinement-workflow/v1'){
   if(typeof window.ChemRefinementLab?.parseWorkflowResponse!=='function')throw Error('Exact refinement response support is unavailable. Reload the Workbench.');
   value=window.ChemRefinementLab.parseWorkflowResponse(text);
  }
  if(value?.request?.study||value?.study||value?.design_record?.request?.study){const exact=parseStudy(text);if(value.request?.study)studyTexts.set(value,JSON.stringify(exact.request.study,null,2));if(value.study)studyTexts.set(value,JSON.stringify(exact.study,null,2));if(value.design_record?.request?.study)studyTexts.set(value.design_record,JSON.stringify(exact.design_record.request.study,null,2));}
  if(!response.ok){const error=Error(value.error||`Request failed (${response.status})`);error.status=response.status;error.response=value;throw error;}return value;
 }
 const el=id=>document.getElementById(id);
 const objectives={electrode_electrolyte:'max_cathodic_charge',catalyst_reactant:'max_product_pool',solid_liquid:'max_adsorbed_coverage'};
 const labels={electrode_electrolyte:'Electrode / electrolyte',catalyst_reactant:'Catalyst / reactant',solid_liquid:'Solid / liquid'};
 const heading=document.querySelector('.heading'),grid=document.querySelector('.studio-grid');
 for(const node of document.querySelectorAll('.metrics,.agent-panel,.execution-panel,.structure-lab-panel,.project-panel,.workarea,.diagnostics,.scope'))node.classList.add('structure-only');
 el('compile').classList.add('structure-only');
 const switcher=document.createElement('div');switcher.className='studio-switch';switcher.setAttribute('aria-label','Workspace mode');
 switcher.innerHTML='<button id="open-design-studio" aria-pressed="true">Design Studio</button><button id="open-structure-studio" aria-pressed="false">Structure Studio</button>';
 heading.after(switcher);
 const panel=document.createElement('section');panel.className='panel design-panel design-only';panel.innerHTML=`
 <div class="agent-heading"><div class="agent-symbol">✳</div><div><h2>Design with a purpose.</h2><p><span id="design-model-name">Local model</span> <span>via LM Studio</span></p></div></div>
 <div class="agent-body"><label for="design-prompt">What should we design?</label><textarea id="design-prompt" maxlength="2000" spellcheck="false">Design catechol amide surface anchors and ordered multication oxides, then simulate electrode-electrolyte, catalyst-reactant and solid-liquid responses using the illustrative study parameters.</textarea>
 <div class="field-row"><div><label for="design-workflow">Direct workflow</label><select id="design-workflow"><option value="interface_design">Design & interface study</option><option value="organic_design">Organic candidate design</option><option value="inorganic_design">Inorganic candidate design</option><option value="interface_simulation">Simulate selected pair</option><option value="interface_screening">Compare supplied interface scenarios</option></select></div><div><label for="design-parameter-mode">Interface parameters</label><select id="design-parameter-mode"><option value="illustrative">Illustrative scenario</option><option value="supplied">Supplied, candidate-bound data</option><option value="none">No kinetic data</option></select></div></div>
 <div class="comparison-objective"><label for="design-comparison-objective">Conditional comparison objective</label><select id="design-comparison-objective"><option value="">Select for a supplied-pair comparison</option><option value="electrode_electrolyte">Electrode / electrolyte · final cathodic charge</option><option value="catalyst_reactant">Catalyst / reactant · final product pool</option><option value="solid_liquid">Solid / liquid · final adsorbed coverage</option></select></div>
 <div class="design-actions"><button id="run-design-model" class="primary">✳ Design from prompt</button><button id="run-design-direct">Run direct workflow</button></div>
 <p class="design-caption">One run activates registered local modules. Up to 24 candidates per family, three interface models or four supplied pair scenarios.</p>
 <div id="design-status" class="design-status" role="status">Generate real structural candidates and inspect the calculations behind each screen.</div>
 <div id="design-pending" class="design-pending" hidden aria-live="off"><div class="design-pending-orbit" aria-hidden="true"></div><div><strong id="design-pending-label">Awaiting result</strong><p id="design-pending-time">Elapsed wall time: 0.0 s</p><small>Reaction progress becomes available only after numerical samples are returned.</small></div></div>
 <details><summary>Study inputs & scenario provenance</summary><p class="design-caption">Illustrative kinetics are declared scenario parameters. They are not measurements of the generated chemicals. Supply candidate-bound parameter records to compare declared scenarios. Their calibration status remains unverified.</p><textarea id="design-study-input" spellcheck="false" aria-label="Design study specification"></textarea></details></div>`;
 grid.append(panel);
 const selector=document.createElement('select');selector.id='design-candidate-select';selector.setAttribute('aria-label','Design candidate in 3D');selector.innerHTML='<option value="">Candidate preview</option>';document.querySelector('.viewer-controls').prepend(selector);
 const section=document.createElement('section');section.className='design-results design-only';section.id='design-results';section.innerHTML=`
 <div class="design-results-heading"><div><p class="eyebrow">CANDIDATE LIBRARIES / INTERFACE RESPONSE</p><h2>From a design space to an inspectable result.</h2></div><div class="study-controls"><select id="design-history" aria-label="Saved design studies"><option value="">Saved design studies</option></select><button id="import-design">↑ Open study</button><input id="import-design-file" type="file" accept="application/json,.json" hidden><button id="export-design" disabled>↓ Export study</button></div></div>
 <p id="design-history-status" class="design-export-status" role="status"></p>
 <p id="design-export-status" class="design-export-status" role="status"></p>
 <div class="design-metrics"><article><strong id="design-organic-count">—</strong><span>Organic candidates</span></article><article><strong id="design-inorganic-count">—</strong><span>Oxide candidates</span></article><article><strong id="design-interface-count">—</strong><span>Interface models</span></article><article><strong id="design-elapsed">—</strong><span>Seconds / actual run</span></article></div>
 <div id="design-module-trace"></div><div id="design-libraries" class="candidate-libraries"></div><div id="design-comparison"></div>
 <div class="interface-section"><div class="interface-header"><div><p class="eyebrow">BOUND TO THE SELECTED CANDIDATE PAIR</p><h3>Interface response</h3></div><span id="interface-provenance" class="parameter-badge">Parameters required</span></div><div id="interface-tabs" class="interface-tabs"></div><div id="interface-view" class="interface-view"><p class="design-empty">Run a study to inspect coverage, charge-transfer and surface-state responses.</p></div></div>
 <details><summary>Workflow, constraints, exclusions & evidence</summary><pre id="design-evidence">No saved study yet.</pre></details>`;
 grid.after(section);
 const refinementHost=document.createElement('section');refinementHost.id='design-refinement-workflow';el('design-libraries').after(refinementHost);
 const refinementWorkflow=window.ChemRefinementLab?.createWorkflow(refinementHost,{request:api})||null;
 if(!refinementWorkflow)refinementHost.textContent='The refinement controls could not load. Reopen the Workbench to prepare an organic candidate.';
 const importedRecords=new Set();
 let interfaceWorkbench=null,pendingTimer=null;
 function disposeInterface(){interfaceWorkbench?.dispose();interfaceWorkbench=null;}
 function stopPending(){if(pendingTimer!==null)clearInterval(pendingTimer);pendingTimer=null;el('design-pending').hidden=true;}
 function startPending(kind){stopPending();const started=performance.now();el('design-pending').hidden=false;el('design-pending-label').textContent=kind==='model'?'Awaiting LM Studio and workflow results':'Awaiting local workflow results';const update=()=>{el('design-pending-time').textContent='Elapsed wall time: '+((performance.now()-started)/1000).toFixed(1)+' s';};update();pendingTimer=setInterval(update,250);}
 const ui=(tag,className,text)=>{const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=String(text);return node;};
 const exactValue=value=>typeof value==='number'&&Number.isFinite(value)?Object.is(value,-0)?'-0':String(value):typeof value==='boolean'?String(value):typeof value==='string'?value:'Unavailable';
 function jsonDetails(title,value){const box=ui('details','candidate-details'),summary=ui('summary','',title),pre=ui('pre','',JSON.stringify(value,null,2));box.append(summary,pre);return box;}
 function renderCandidateInspector(candidate){
  const box=el('design-'+candidate.family+'-inspector');if(!box)return;box.replaceChildren();
  box.append(ui('p','eyebrow','SELECTED CANDIDATE / STORED VALUES'),ui('h4','',candidate.family==='organic'?'Molecular descriptor card':candidate.formula+' · geometric screen'));
  const units={molecular_weight:'g/mol',mw:'g/mol',logp:'1',tpsa:'Å²',h_bond_donors:'count',h_bond_acceptors:'count',rotatable_bonds:'count',formal_charge:'e',tolerance_factor:'1',octahedral_radius_ratio:'1',b_radius_mismatch_angstrom:'Å',lattice_parameter_angstrom:'Å'};
  const metrics=ui('dl','candidate-descriptor-grid');for(const [key,value] of Object.entries(candidate.descriptors||{})){const item=ui('div');item.append(ui('dt','',key.replaceAll('_',' ')),ui('dd','',exactValue(value)+' '+(units[key]||'unit not declared')));metrics.append(item);}box.append(metrics);
  const score=ui('p','candidate-score');score.append(ui('strong','','Ranking score: '+exactValue(candidate.score)),ui('span','',candidate.score_scope||'Score scope not supplied'));box.append(score);
  if(candidate.canonical_smiles)box.append(ui('code','candidate-smiles',candidate.canonical_smiles));
  box.append(ui('p','design-caption','Values preserve the stored numerical precision. They do not imply matching experimental accuracy.'));
  if(candidate.complexity){const complexity=ui('div','candidate-complexity');complexity.append(ui('p','',String(candidate.complexity.heavy_atoms)+' heavy atoms'),ui('p','',(candidate.complexity.structural_feature_classes||[]).join(' · ')),ui('p','',(candidate.complexity.substantive_functional_groups||[]).join(' · ')));box.append(complexity);}
  if(candidate.validation){const validations=ui('dl','candidate-descriptor-grid');for(const [key,value] of Object.entries(candidate.validation)){if(typeof value==='object')continue;const item=ui('div');item.append(ui('dt','',key.replaceAll('_',' ')),ui('dd','',exactValue(value)+(key.endsWith('_angstrom')?' Å':'')));validations.append(item);}box.append(validations);}
  box.append(jsonDetails('Generation, identity & complete validation',{candidate_hash:candidate.candidate_hash,identity_hash:candidate.identity_hash,request_hash:candidate.request_hash,geometry_hash:candidate.geometry?.geometry_hash,generation:candidate.generation,complexity:candidate.complexity,structure:candidate.structure,validation:candidate.validation}));
 }

 let catalog=null,current=null,generation=0,busy=false,exporting=false,selectedOrganic=null,selectedInorganic=null,selectedProfile=null,displayedCandidate=null;
 const setText=(id,text)=>{el(id).textContent=text;};
 function mode(name){refinementWorkflow?.setVisible(name==='design');if(name!=='design')interfaceWorkbench?.pause();document.body.dataset.studio=name;el('open-design-studio').setAttribute('aria-pressed',String(name==='design'));el('open-structure-studio').setAttribute('aria-pressed',String(name==='structure'));heading.querySelector('h1').innerHTML=name==='design'?'Make room for discovery<span>.</span>':'A closer look at chemistry<span>.</span>';heading.querySelector('.subtitle').textContent=name==='design'?'Generate compounds. Explore interfaces. Follow the evidence.':'Real coordinates. Inspectable proposals. One local workspace.';heading.querySelector('.eyebrow').textContent=name==='design'?'DESIGN STUDIO / 01':'STRUCTURE STUDIO / 01';if(name==='design'){if(displayedCandidate){displayGeometry(displayedCandidate.geometry);setText('structure-title',candidateLabel(displayedCandidate));}else clearGeometry('Run a design study to inspect its generated candidate coordinates.');}else if(name==='structure'){if(typeof restoreSelectedStructure==='function')restoreSelectedStructure();else{const geometry=typeof result!=='undefined'?result?.scene?.structures.find(item=>item.object_id===el('structure-select').value):null;if(geometry)displayGeometry(geometry);else clearGeometry('No coordinates are bound to the selected Structure workspace revision.');}}if(name==='design'){el('filename').textContent=current?.request.study.name||'Design study';el('source-origin').textContent='DESIGN WORKSPACE';}else{el('filename').textContent=el('editor-title').textContent;el('source-origin').textContent='STRUCTURE WORKSPACE';}}
 el('open-design-studio').onclick=()=>mode('design');el('open-structure-studio').onclick=()=>mode('structure');mode('design');
 el('examples').addEventListener('click',()=>mode('structure'),true);
 document.addEventListener('structure-compiled-background',()=>{if(document.body.dataset.studio!=='design')return;setText('filename',current?.request.study.name||'Design study');setText('source-origin','DESIGN WORKSPACE');if(!displayedCandidate)clearGeometry('Run a design study to inspect its generated candidate coordinates.');});
 function clearResults(message){refinementWorkflow?.setCandidate(null);stopPending();disposeInterface();generation++;setText('design-export-status','');el('design-status').dataset.state='idle';current=null;selectedOrganic=null;selectedInorganic=null;displayedCandidate=null;el('export-design').disabled=true;el('design-libraries').replaceChildren();el('design-module-trace').replaceChildren();el('design-comparison').replaceChildren();selector.innerHTML='<option value="">Candidate preview</option>';for(const id of ['design-organic-count','design-inorganic-count','design-interface-count','design-elapsed'])setText(id,'—');el('interface-tabs').replaceChildren();el('interface-view').innerHTML='<p class="design-empty">The current inputs have no saved simulation result.</p>';setText('design-evidence','No result for the current inputs.');setText('design-status',message);if(document.body.dataset.studio==='design')clearGeometry('Run the current study to inspect candidate coordinates.');}
 function rememberSelectedPair(){if(current&&selectedOrganic&&selectedInorganic){try{const study=parseStudy(el('design-study-input').value);study.selected_candidates={run_ref:current.record_hash,organic_hash:selectedOrganic.candidate_hash,inorganic_hash:selectedInorganic.candidate_hash};el('design-study-input').value=JSON.stringify(study,null,2);}catch{}}}
 el('design-prompt').addEventListener('input',()=>{rememberSelectedPair();clearResults('Objective changed. Saved candidate references remain available in the study inputs.');});
 el('design-workflow').onchange=()=>{rememberSelectedPair();clearResults('Workflow changed. Saved candidate references remain available; run the selected workflow.');};
 el('design-study-input').addEventListener('input',()=>{try{const study=parseStudy(el('design-study-input').value);el('design-parameter-mode').value=study.interface_parameters.mode;el('design-comparison-objective').value=study.interface_screening?.profile||'';}catch{}clearResults('Study inputs changed. Run a new study to update candidates and response curves.');});
 el('design-parameter-mode').onchange=()=>{rememberSelectedPair();try{const study=parseStudy(el('design-study-input').value);study.interface_parameters.mode=el('design-parameter-mode').value;if(study.interface_parameters.mode!=='supplied')study.interface_parameters.specifications=[];el('design-study-input').value=JSON.stringify(study,null,2);clearResults('Parameter mode changed. Previous simulations no longer describe these inputs.');}catch(error){setText('design-status',error.message);}};
 el('design-comparison-objective').onchange=()=>{rememberSelectedPair();try{const study=parseStudy(el('design-study-input').value),profile=el('design-comparison-objective').value;if(profile)study.interface_screening={profile,objective:objectives[profile]};else delete study.interface_screening;el('design-study-input').value=JSON.stringify(study,null,2);clearResults('Comparison objective changed. Supply two to four candidate-bound parameter sets under matched conditions.');}catch(error){setText('design-status',error.message);}};
 function fingerprint(){return JSON.stringify([el('design-prompt').value,el('design-study-input').value,el('design-parameter-mode').value,el('design-workflow').value,el('design-comparison-objective').value]);}
 function candidateLabel(candidate){return candidate.family==='organic'?'Surface anchor · '+(candidate.generation?.fragment_id||candidate.id).replaceAll('_',' '):candidate.formula+' · ordered oxide';}
 function selectCandidate(candidate){refinementWorkflow?.setCandidate(candidate.family==='organic'?{selection:{run_ref:current.record_hash,candidate_hash:candidate.candidate_hash},label:candidateLabel(candidate),atom_count:candidate.geometry.atoms.length}:null);displayedCandidate=candidate;if(candidate.family==='organic')selectedOrganic=candidate;else selectedInorganic=candidate;selector.value=candidate.candidate_hash;if(document.body.dataset.studio==='design'){document.dispatchEvent(new Event('structure-selection-changed'));displayGeometry(candidate.geometry);setText('structure-title',candidateLabel(candidate));setText('filename',current.request.study.name);setText('source-origin','DERIVED CANDIDATE');}for(const row of section.querySelectorAll('tr[data-candidate]'))row.setAttribute('aria-selected',String([selectedOrganic?.candidate_hash,selectedInorganic?.candidate_hash].includes(row.dataset.candidate)));for(const selected of [selectedOrganic,selectedInorganic])if(selected)renderCandidateInspector(selected);renderInterfaces();}
 function number(value,digits=3){return typeof value==='number'&&Number.isFinite(value)?value.toFixed(digits):'—';}
 function library(family){const result=current[family];if(!result)return;const box=document.createElement('article');box.className='candidate-library';const title=document.createElement('h3');title.textContent=family==='organic'?'Organic surface-anchor candidates':'Ordered multication oxide candidates';box.append(title);const caption=document.createElement('p');caption.className='design-caption';caption.textContent=family==='organic'?'Real molecular graphs. Ranked by the requested calculated descriptors.':'40-atom ordered cells. Ranked by ionic geometry; no stability claim.';box.append(caption);const wrap=document.createElement('div');wrap.className='candidate-table-wrap';const table=document.createElement('table');table.innerHTML=family==='organic'?'<thead><tr><th>Candidate</th><th>MW / g mol⁻¹</th><th>logP</th><th>TPSA / Å²</th></tr></thead>':'<thead><tr><th>Candidate</th><th>Tolerance</th><th>Cell / Å</th><th>Screen score</th></tr></thead>';const body=document.createElement('tbody');for(const [index,candidate]of result.candidates.entries()){const row=document.createElement('tr');row.dataset.candidate=candidate.candidate_hash;row.setAttribute('aria-selected','false');const first=document.createElement('td'),button=document.createElement('button');button.textContent=family==='organic'?`${String(index+1).padStart(2,'0')} · ${candidate.source?.fragment_id||candidate.generation?.fragment_id||candidate.id.slice(-8)}`:candidate.formula;button.onclick=()=>{generation++;selectCandidate(candidate);};const small=document.createElement('small');small.textContent=family==='organic'?`${candidate.geometry.atoms.length} display atoms`:'A / B / B′ / O site ordering';first.append(button,small);row.append(first);const d=candidate.descriptors;const values=family==='organic'?[d.molecular_weight??d.mw,d.logp,d.tpsa]:[d.tolerance_factor,d.lattice_parameter_angstrom,candidate.score];for(const value of values){const cell=document.createElement('td');cell.textContent=number(value);cell.title=exactValue(value);row.append(cell);}body.append(row);const option=document.createElement('option');option.value=candidate.candidate_hash;option.textContent=family==='organic'?`Organic · ${index+1}`:`Oxide · ${candidate.formula}`;selector.append(option);}table.append(body);wrap.append(table);box.append(wrap);const inspector=ui('div','candidate-inspector');inspector.id='design-'+family+'-inspector';box.append(inspector);const counts=ui('p','design-caption',`${result.candidate_count} retained · ${result.attempted_count} attempted · ${result.rejected.length} excluded`);box.append(counts,jsonDetails('Generation, ranking & excluded candidates',{profile:result.profile,request:result.request,ranking:result.ranking,rejected:result.rejected,limitations:result.limitations,result_hash:result.result_hash}));el('design-libraries').append(box);}
 selector.onchange=()=>{for(const family of ['organic','inorganic']){const candidate=current?.[family]?.candidates.find(item=>item.candidate_hash===selector.value);if(candidate){generation++;selectCandidate(candidate);return;}}};
 function simulationPair(simulation){return {organic:simulation.inputs?.organic_candidate?.candidate_hash,inorganic:simulation.inputs?.inorganic_candidate?.candidate_hash};}
 function renderInterfaces(){
  disposeInterface();
  el('interface-tabs').replaceChildren();el('interface-view').replaceChildren();
  if(!current)return;
  const simulations=(current.interfaces||[]).filter(simulation=>{const pair=simulationPair(simulation);return pair.organic&&pair.inorganic&&selectedOrganic?.candidate_hash===pair.organic&&selectedInorganic?.candidate_hash===pair.inorganic;});
  if(!simulations.length){el('interface-view').innerHTML='<p class="design-empty">No simulation is bound to this candidate pair. Select a simulated pair or run a direct interface study for this selection.</p>';setText('interface-provenance','Parameters required');return;}
  if(!simulations.some(item=>item.profile===selectedProfile))selectedProfile=simulations[0].profile;
  for(const simulation of simulations){const tab=document.createElement('button');tab.textContent=labels[simulation.profile]||simulation.profile;tab.setAttribute('aria-selected',String(simulation.profile===selectedProfile));tab.onclick=()=>{selectedProfile=simulation.profile;renderInterfaces();};el('interface-tabs').append(tab);}
  const simulation=simulations.find(item=>item.profile===selectedProfile);
  if(window.ChemInterfaceWorkbench){interfaceWorkbench=window.ChemInterfaceWorkbench.create(el('interface-view'),simulation,{studyHash:current.record_hash,imported:importedRecords.has(current.record_hash),saveExport:payload=>api('/api/design/export-interface',payload)});}
  else{const message=document.createElement('p');message.className='design-empty';message.textContent='The interface view could not load. The complete numerical result remains available in the saved evidence record.';el('interface-view').append(message);}
  const provenance=simulation.parameter_status==='illustrative'?'Illustrative parameter scenario':'User-supplied parameters · unverified';
  setText('interface-provenance',(current.state==='completed'?'':'Partial run result · ')+provenance);
 }
 function renderComparison(){
  const box=el('design-comparison');box.replaceChildren();const comparison=current?.interface_screening;if(!comparison)return;
  box.className='candidate-library comparison-library';const heading=document.createElement('h3');heading.textContent='Conditional pair comparison · '+(labels[comparison.objective.profile]||comparison.objective.profile);
  const scope=document.createElement('p');scope.className='design-caption';scope.textContent=(comparison.winner?'Best scenario under the supplied conditions.':'No unique best scenario within numerical tolerance.')+' These results compare the supplied parameters; they do not establish measured material performance.';box.append(heading,scope);
  const table=document.createElement('table');table.innerHTML='<thead><tr><th>Candidate pair</th><th>Final-time response</th><th>Comparison status</th></tr></thead>';const body=document.createElement('tbody');
  for(const row of comparison.rows){const organic=current.organic?.candidates.find(candidate=>candidate.candidate_hash===row.pair.organic),inorganic=current.inorganic?.candidates.find(candidate=>candidate.candidate_hash===row.pair.inorganic);const tr=document.createElement('tr'),pair=document.createElement('td'),button=document.createElement('button'),value=document.createElement('td'),status=document.createElement('td');button.textContent=(organic?.generation?.fragment_id||row.pair.organic.slice(7,15))+' / '+(inorganic?.formula||row.pair.inorganic.slice(7,15));button.disabled=!organic||!inorganic;button.onclick=()=>{generation++;selectedInorganic=inorganic;selectCandidate(organic);};pair.append(button);value.textContent=Number.isFinite(row.value)?exactValue(row.value)+' '+row.unit:'Unavailable';status.textContent=row.tied_best?(comparison.winner?'Best supplied scenario':'Tied best supplied scenario'):'Compared scenario';tr.append(pair,value,status);body.append(tr);}
  table.append(body);const wrap=document.createElement('div');wrap.className='candidate-table-wrap';wrap.append(table);box.append(wrap);box.append(ui('p','design-caption','Tie tolerance: '+exactValue(comparison.tie_tolerance)+' '+(comparison.rows[0]?.unit||'unit unavailable')+' · '+comparison.comparison_scope),jsonDetails('Matched conditions, ranking tolerance & evidence',{objective:comparison.objective,tie_tolerance:comparison.tie_tolerance,conditions:comparison.conditions,conditions_hash:comparison.conditions_hash,winner:comparison.winner,result_hash:comparison.result_hash,scientifically_calibrated:comparison.scientifically_calibrated,measured_performance_claim:comparison.measured_performance_claim,limitations:comparison.limitations}));
 }
 function render(record){
  refinementWorkflow?.setCandidate(null);
  setText('design-export-status','');current=record;displayedCandidate=null;selector.innerHTML='<option value="">Candidate preview</option>';el('design-libraries').replaceChildren();el('design-module-trace').replaceChildren();el('design-comparison').replaceChildren();
  setText('design-organic-count',record.organic?.candidates.length??0);setText('design-inorganic-count',record.inorganic?.candidates.length??0);setText('design-interface-count',record.interfaces.length);setText('design-elapsed',number(record.seconds,1));
  for(const item of record.trace){const span=document.createElement('span'),failed=item.status==='failed';span.dataset.status=failed?'failed':'succeeded';span.textContent=`${failed?'Failed':'Completed'} · ${labels[item.module]||item.module.replaceAll('_',' ')} · ${number(item.seconds,2)} s${failed?' · '+(item.error?.message||'Module failed'):''}`;el('design-module-trace').append(span);}
  library('organic');library('inorganic');
  const selectFamily=family=>{const candidates=record[family]?.candidates||[],hash=record.selected_pair?.[family];return hash?candidates.find(candidate=>candidate.candidate_hash===hash)||null:candidates[0]||null;};
  selectedOrganic=selectFamily('organic');selectedInorganic=selectFamily('inorganic');
  if(selectedOrganic)selectCandidate(selectedOrganic);else if(selectedInorganic)selectCandidate(selectedInorganic);else if(document.body.dataset.studio==='design')clearGeometry(record.state==='needs_input'?'Clarify the study inputs to generate candidate coordinates.':'This run produced no displayable candidate coordinates.');
  renderInterfaces();renderComparison();setText('design-evidence',JSON.stringify(record,null,2));
  const message=record.error?.message||record.decision?.message||record.orchestration?.error?.message||'Inspect the retained evidence record.';
  const status=record.state==='completed'?`Completed ${record.trace.length} ${record.trace.length===1?'module':'modules'}. ${message}`:record.state==='needs_input'?`Clarification needed: ${message}`:record.state==='rejected'?`Study rejected: ${message}`:`Study failed: ${message}`;
  setText('design-status',status+(importedRecords.has(record.record_hash)?' Imported data; origin unverified.':''));el('design-status').dataset.state=record.state;el('export-design').disabled=false;
  if(![...el('design-history').options].some(option=>option.value===record.record_hash)){const option=document.createElement('option');option.value=record.record_hash;option.textContent=`${record.request.study.name} · ${record.state} · ${record.record_hash.slice(7,15)}`;el('design-history').append(option);}
  el('design-history').value=record.record_hash;
 }
 function restore(record){const text=studyTexts.get(record);if(typeof text!=='string')throw Error('Exact study input text is unavailable. Reopen the saved study.');el('design-study-input').value=text;el('design-prompt').value=record.request.prompt;el('design-parameter-mode').value=record.request.study.interface_parameters.mode;el('design-comparison-objective').value=record.request.study.interface_screening?.profile||'';if(record.decision?.workflow)el('design-workflow').value=record.decision.workflow;render(record);}
 async function run(kind){
  if(busy||!catalog)return;
  let study,decision=null;
  try{study=parseStudy(el('design-study-input').value);if(kind==='direct'){decision=structuredClone(catalog.direct_decision);decision.workflow=el('design-workflow').value;decision.interfaces=['interface_design','interface_simulation'].includes(decision.workflow)?Object.keys(labels):decision.workflow==='interface_screening'?[study.interface_screening?.profile].filter(Boolean):[];
   if(decision.workflow==='interface_screening'&&(!study.interface_screening||study.interface_parameters.mode!=='supplied'||study.interface_parameters.specifications.length<2))throw Error('Choose a comparison objective and supply two to four candidate-bound parameter sets for pairs from a saved study.');
   if(['interface_simulation','interface_screening'].includes(decision.workflow)){if(current&&selectedOrganic&&selectedInorganic)study.selected_candidates={run_ref:current.record_hash,organic_hash:selectedOrganic.candidate_hash,inorganic_hash:selectedInorganic.candidate_hash};else if(!study.selected_candidates)throw Error('Select both candidates from a saved design first.');}
  }}catch(error){setText('design-status',error.message);return;}
  clearResults('Starting the requested study.');const token=++generation,identity=fingerprint();busy=true;el('run-design-model').disabled=el('run-design-direct').disabled=true;el('design-status').dataset.state='running';startPending(kind);
  setText('design-status',kind==='model'?'LM Studio is selecting a bounded workflow. The host will generate, screen and simulate the requested modules.':'Running the selected first-party workflow with the current study inputs.');
  try{const response=await api('/api/design/run',{prompt:el('design-prompt').value,study,mode:kind,decision});if(token!==generation||identity!==fingerprint())return;render(response);}
  catch(error){if(token!==generation||identity!==fingerprint())return;if(error.response?.design_record)render(error.response.design_record);else{setText('design-status','Study stopped: '+error.message);el('design-status').dataset.state='failed';}}
  finally{stopPending();busy=false;el('run-design-model').disabled=el('run-design-direct').disabled=false;}
 }
 el('run-design-model').onclick=()=>run('model');el('run-design-direct').onclick=()=>run('direct');
 el('export-design').onclick=async()=>{
  if(!current||exporting)return;
  const reference=current.record_hash,identity=fingerprint();exporting=true;el('export-design').disabled=true;setText('design-export-status','Saving the verified study to the local workspace.');
  try{const receipt=await api('/api/design/export',{reference});if(identity!==fingerprint()||current?.record_hash!==reference)return;if(receipt.reference!==reference)throw Error('The saved artifact does not match this study.');setText('design-export-status',`Saved locally: ${receipt.path}\nFile SHA-256: ${receipt.file_sha256}\nUse Open study to reopen this file.`);}
  catch(error){if(identity===fingerprint()&&current?.record_hash===reference)setText('design-export-status','Export failed: '+error.message);}
  finally{exporting=false;if(identity===fingerprint()&&current?.record_hash===reference)el('export-design').disabled=false;}
 };
 el('design-history').onchange=async()=>{const reference=el('design-history').value;if(!reference)return;clearResults('Opening a saved study.');const token=++generation,identity=fingerprint();try{const record=await api('/api/design/read',{reference});if(token!==generation||identity!==fingerprint())return;restore(record);}catch(error){if(token===generation&&identity===fingerprint())setText('design-status','Cannot open study: '+error.message);}};
 el('import-design').onclick=()=>el('import-design-file').click();
 el('import-design-file').onchange=async()=>{
  const file=el('import-design-file').files?.[0];if(!file)return;
  clearResults('Checking the exported study and its evidence hashes.');const token=++generation,identity=fingerprint();
  try{if(file.size>20*1024*1024)throw Error('Study files must be 20 MiB or smaller.');const documentText=await file.text();if(token!==generation||identity!==fingerprint())return;const imported=await api('/api/design/import',{document:documentText});if(token!==generation||identity!==fingerprint())return;importedRecords.add(imported.record_hash);restore(imported);}
  catch(error){if(token===generation&&identity===fingerprint()){setText('design-status','Cannot open study: '+error.message);el('design-status').dataset.state='failed';}}
  finally{el('import-design-file').value='';}
 };
 let historyLoad=0;
 async function loadSavedStudies(){
  const token=++historyLoad;setText('design-history-status','Reading saved design studies…');
  try{
   const listing=await api('/api/design/history');if(token!==historyLoad)return;
   if(!Array.isArray(listing?.records)||!Array.isArray(listing.errors))throw Error('The saved study index is malformed.');
   for(const record of listing.records)if(!/^sha256:[0-9a-f]{64}$/.test(record?.record_hash||'')||typeof record.name!=='string'||typeof record.state!=='string')throw Error('A saved study index entry is malformed.');
   // The index is workspace metadata, independent of the input generation. Merge
   // it without choosing a record or interrupting a generation-bound /read.
   const selected=el('design-history').value;
   for(const record of listing.records){if([...el('design-history').options].some(option=>option.value===record.record_hash))continue;const option=document.createElement('option');option.value=record.record_hash;option.textContent=`${record.name} · ${record.state} · ${record.record_hash.slice(7,15)}`;el('design-history').append(option);}
   el('design-history').value=selected;
   setText('design-history-status',listing.errors.length?'Some saved studies could not be indexed: '+listing.errors.map(item=>String(item.filename||'Unknown record')+' · '+String(item.error||'Unreadable record')).join('; '):`${listing.records.length} saved ${listing.records.length===1?'study':'studies'} available. Select one to open its original record.`);
  }catch(error){if(token===historyLoad)setText('design-history-status','Saved study history unavailable: '+error.message);}
 }
 loadSavedStudies();
 document.addEventListener('keydown',event=>{if(document.body.dataset.studio==='design'&&(event.ctrlKey||event.metaKey)&&event.key==='Enter'){event.preventDefault();event.stopImmediatePropagation();run('model');}},true);
 api('/api/design/catalog').then(value=>{catalog=value;if(!el('design-study-input').value)el('design-study-input').value=studyTexts.get(value);}).catch(error=>setText('design-status',error.message));
 api('/api/model/status').then(value=>setText('design-model-name',value.display_name||'Local model')).catch(()=>{});
})();
