let labGeometry=null,labRequestGeneration=0;
const labRevisions=new Map();
function selectedLabGeometry(selection){return selection?.startsWith('geometry-revision:')?labRevisions.get(selection.slice('geometry-revision:'.length))||null:null;}
function labInputFingerprint(){return JSON.stringify({molecule:$('molecule-input').value,format:$('molecule-format').value,coordinates:$('coordinate-edit').value,site:$('slab-site').value});}
function labSnapshot(){return {generation:++labRequestGeneration,revision,viewportGeneration,inputs:labInputFingerprint(),source:canonicalJSON(sourcePayload()),view:viewportBindingFingerprint()};}
function labCurrent(token){return token.generation===labRequestGeneration&&token.revision===revision&&token.viewportGeneration===viewportGeneration&&token.inputs===labInputFingerprint()&&token.source===canonicalJSON(sourcePayload())&&token.view===viewportBindingFingerprint();}
function showLabGeometry(value,{preserveDraft=false}={}){
 const coordinates=preserveDraft&&labGeometry?.geometry_hash===value.geometry_hash?$('coordinate-edit').value:JSON.stringify(value.atoms.map(a=>a.position),null,2);
 labGeometry=value;labRevisions.set(value.geometry_hash,value);currentPlan=null;agentRecord=null;resetExecution();
 const selection='geometry-revision:'+value.geometry_hash,selector=$('structure-select');
 if(!Array.from(selector.children).some(option=>option.value===selection))selector.append(new Option(value.object_id+' · Lab revision '+value.geometry_hash.slice(-8),selection));
 selector.value=selection;displayGeometry(value);
 $('coordinate-edit').value=coordinates;$('apply-coordinates').disabled=false;$('compare-coordinates').disabled=!value.parent_geometry_hash;$('geometry-to-water').disabled=value.atoms.map(a=>a.element).sort().join(',')!=='H,H,O';
 $('structure-lab-message').textContent=value.description+' This Lab revision is separate from compiled-source calculation inputs.';$('structure-comparison').textContent='Revision '+value.geometry_hash;syncLabEditorBinding();
}
function labEditorMatchesViewport(){return !!labGeometry&&$('structure-select').value==='geometry-revision:'+labGeometry.geometry_hash&&displayedGeometryState()?.geometry.geometry_hash===labGeometry.geometry_hash&&displayedGeometryState()?.scale===1;}
function syncLabEditorBinding(){const matches=labEditorMatchesViewport();$('coordinate-edit').disabled=$('apply-coordinates').disabled=!matches;$('compare-coordinates').disabled=!matches||!labGeometry?.parent_geometry_hash;$('geometry-to-water').disabled=!matches||labGeometry.atoms.map(atom=>atom.element).sort().join(',')!=='H,H,O';}
function clearLabSelection(){labGeometry=null;$('coordinate-edit').value='';$('structure-comparison').textContent='Select a Lab revision to compare coordinates.';$('structure-lab-message').textContent='The viewport shows compiled or recorded calculation inputs. Select or import a Lab revision before editing coordinates.';syncLabEditorBinding();}
function requireLabEditorBinding(){if(!labEditorMatchesViewport())throw Error('Select the matching Lab revision before editing or comparing coordinates. The editor is not bound to the current viewport.');}
document.addEventListener('geometry-display-changed',syncLabEditorBinding);
$('import-molecule').onclick=async()=>{const token=labSnapshot();try{const value=await api('/api/structure/import',{content:$('molecule-input').value,format:$('molecule-format').value});if(labCurrent(token))showLabGeometry(value);}catch(error){if(labCurrent(token))$('structure-lab-message').textContent=error.message;}};
$('build-slab').onclick=async()=>{const token=labSnapshot();try{if(!result?.success)throw Error('Compile the FCC copper parent first.');const object=result.document.objects.find(o=>o.kind==='PeriodicStructure'&&o.id===$('structure-select').value);if(!object)throw Error('Select an explicit conventional FCC copper structure.');const value=await api('/api/structure/build',{...sourcePayload(),object_id:object.id,site:$('slab-site').value});if(labCurrent(token))showLabGeometry(value);}catch(error){if(labCurrent(token))$('structure-lab-message').textContent=error.message;}};
$('apply-coordinates').onclick=async()=>{const token=labSnapshot();try{requireLabEditorBinding();if(labGeometry){const value=await api('/api/structure/edit',{reference:labGeometry.geometry_hash,positions:JSON.parse($('coordinate-edit').value)});if(labCurrent(token))showLabGeometry(value);}}catch(error){if(labCurrent(token))$('structure-lab-message').textContent=error.message;}};
function renderStructureComparison(report){
 const host=$('structure-comparison');host.replaceChildren();
 const title=document.createElement('h4');title.textContent='Revision displacement';host.append(title);
 const summary=document.createElement('p');summary.textContent=`RMS ${report.rms_displacement_angstrom} Å · Maximum ${report.maximum_displacement_angstrom} Å`;host.append(summary);
 const scope=document.createElement('p');scope.textContent=report.scope;host.append(scope);
 const left=labRevisions.get(report.left),right=labRevisions.get(report.right);
 if(left&&right&&left.atoms.length===right.atoms.length&&left.atoms.every((atom,index)=>atom.id===right.atoms[index].id&&atom.element===right.atoms[index].element)){
  const rows=left.atoms.map((atom,index)=>{const other=right.atoms[index],delta=other.position.map((value,axis)=>value-atom.position[axis]);return {id:atom.id,element:atom.element,delta,distance:Math.hypot(...delta)};});
  const table=document.createElement('table'),caption=document.createElement('caption');caption.textContent='Client-derived Cartesian displacement from retained revisions / Å';table.append(caption);
  const header=document.createElement('tr');for(const label of ['Atom','Element','Δx / Å','Δy / Å','Δz / Å','Distance / Å']){const cell=document.createElement('th');cell.textContent=label;header.append(cell);}const thead=document.createElement('thead');thead.append(header);table.append(thead);
  const tbody=document.createElement('tbody');for(const row of rows){const tr=document.createElement('tr');for(const value of [row.id,row.element,...row.delta,row.distance]){const td=document.createElement('td');td.textContent=String(value);tr.append(td);}tbody.append(tr);}table.append(tbody);host.append(table);
  const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg'),maximum=Math.max(...rows.map(row=>row.distance),0);svg.setAttribute('viewBox',`0 0 440 ${Math.max(80,rows.length*20+42)}`);svg.setAttribute('role','img');svg.setAttribute('aria-label','Per-atom Cartesian displacement in angstrom; the accompanying table contains full numeric values.');const axis=document.createElementNS(ns,'text');axis.setAttribute('x','105');axis.setAttribute('y','12');axis.textContent=`0 to ${maximum} Å`;svg.append(axis);
  rows.forEach((row,index)=>{const y=28+index*20,label=document.createElementNS(ns,'text');label.setAttribute('x','8');label.setAttribute('y',String(y));label.textContent=row.id;svg.append(label);const bar=document.createElementNS(ns,'rect');bar.setAttribute('x','105');bar.setAttribute('y',String(y-11));bar.setAttribute('width',String(maximum?270*row.distance/maximum:0));bar.setAttribute('height','12');bar.setAttribute('fill','#087f73');const title=document.createElementNS(ns,'title');title.textContent=`${row.id}: ${row.distance} Å`;bar.append(title);svg.append(bar);});host.append(svg);
 }else{const unavailable=document.createElement('p');unavailable.textContent='Per-atom comparison is unavailable because both exact revisions are not loaded. The server aggregate metrics remain available.';host.append(unavailable);}
 const raw=document.createElement('details'),label=document.createElement('summary'),pre=document.createElement('pre');label.textContent='Exact comparison record';pre.textContent=JSON.stringify(report,null,2);raw.append(label,pre);host.append(raw);
}
$('compare-coordinates').onclick=async()=>{const token=labSnapshot();try{requireLabEditorBinding();if(labGeometry?.parent_geometry_hash){const report=await api('/api/structure/compare',{left:labGeometry.parent_geometry_hash,right:labGeometry.geometry_hash});if(labCurrent(token))renderStructureComparison(report);}}catch(error){if(labCurrent(token))$('structure-lab-message').textContent=error.message;}};
$('geometry-to-water').onclick=()=>{if(!labEditorMatchesViewport())return;const explicit={atoms:labGeometry.atoms.map(a=>[a.element,...a.position.map(String)]),charge:0,multiplicity:1,description:'Explicit structure revision '+labGeometry.geometry_hash};$('source').value='chem 0.1\nmolecule water { structure smiles "O" }\n';attachments={};invalidate();$('compute-profile').value='water';$('water-input').hidden=false;$('water-geometry').value=JSON.stringify(explicit,null,2);compile();};
