import { Activity, ArrowRight, ChevronDown, Clock3, Code2, Download, FlaskConical, LoaderCircle, Pause, Play, Plus, RefreshCw, Settings2, SkipBack, SkipForward, Square, Trash2 } from 'lucide-react';
import { useCallback, useEffect, useRef, useState } from 'react';
import type { ChemScienceCatalog, ChemScienceOperator, ChemScienceRequest, ChemScienceResponse, ChemScienceRun } from '../shared/chem-science-api.ts';
import type { ChemMolecule, ChemReactionNetwork, ChemSimulationInput, ChemSimulationResult } from '../shared/chem-science.ts';
import { ChemReactionScene, type ChemTrajectoryView } from './ChemReactionScene.tsx';
import { ChemKineticsChart } from './ChemKineticsChart.tsx';
import { CHEM_SERIES_COLORS, downloadChemFile, isReactionResult, reactionCsv, restoreSimulationInput, scientificNumber } from './chem-reaction-view.ts';
import { ChemOperatorForm, type ChemFieldDraft } from './ChemOperatorForm.tsx';
import { ChemDataChart } from './ChemDataChart.tsx';
import { ChemToolLibrary, ChemToolDesk } from './ChemToolLibrary.tsx';
import { CHEM_SECTION_COPY, chemicalTableCsv, isChemDataVisualization, operatorWorkspace, selectSectionOperators } from './chem-analysis-input.ts';
import {ChemInterfaceResult} from './ChemInterfaceResult.tsx';
import {isInterfaceResult} from './chem-interface-view.ts';
import {ChemReactionStudyResult} from './ChemReactionStudyResult.tsx';
import {isReactionStudy,reactionStudyFamily,reactionStudyInputFromNetwork,REACTION_FAMILIES,type ReactionFamily} from './chem-reaction-studies.ts';
import './chem-computation.css';

export type ChemComputationSection='analysis'|'statistics'|'chemical-data'|'simulator'|'operators'|'history';
const initialNetwork:ChemReactionNetwork={label:'Illustrative reversible reaction',provenance:'Toy mass-action model with user-supplied rate constants. No experimentally validated reaction mechanism is implied.',species:[{id:'A',label:'Species A',initial_concentration:1},{id:'B',label:'Species B',initial_concentration:0}],reactions:[{id:'forward',reactants:{A:1},products:{B:1},rate_constant:.12},{id:'reverse',reactants:{B:1},products:{A:1},rate_constant:.04}]};
const errorText=(error:unknown)=>error instanceof Error?error.message:String(error);
const stoichiometry=(value:Record<string,number>)=>Object.entries(value).map(([id,n])=>`${n===1?'':`${n} `}${id}`).join(' + ')||'∅';
function parseNetworkDraft(source:string):ChemReactionNetwork {
  const value=JSON.parse(source) as ChemReactionNetwork;
  if(!value||!Array.isArray(value.species)||!Array.isArray(value.reactions))throw new Error('A network needs species and reactions arrays.');
  if(value.label!==undefined&&typeof value.label!=='string')throw new Error('The model label must be text.');
  const ids=new Set<string>();
  for(const species of value.species){if(!species||typeof species.id!=='string'||!species.id||ids.has(species.id)||typeof species.initial_concentration!=='number'||!Number.isFinite(species.initial_concentration))throw new Error('Species need unique text IDs and finite initial concentrations.');if(species.label!==undefined&&typeof species.label!=='string'||species.smiles!==undefined&&typeof species.smiles!=='string')throw new Error('Species labels and SMILES must be text.');ids.add(species.id);}
  const reactionIds=new Set<string>();
  for(const reaction of value.reactions){if(!reaction||typeof reaction.id!=='string'||!reaction.id||reactionIds.has(reaction.id)||typeof reaction.rate_constant!=='number'||!Number.isFinite(reaction.rate_constant))throw new Error('Reactions need unique text IDs and finite rate constants.');reactionIds.add(reaction.id);for(const side of [reaction.reactants,reaction.products])if(!side||typeof side!=='object'||Array.isArray(side)||Object.entries(side).some(([id,n])=>!ids.has(id)||typeof n!=='number'||!Number.isFinite(n)))throw new Error('Reactants and products must map existing species IDs to numeric coefficients.');}
  return value;
}
async function requestChem<T>(request:ChemScienceRequest):Promise<ChemScienceResponse<T>>{
  if(window.workbench?.chemScience)return await window.workbench.chemScience.request(request) as ChemScienceResponse<T>;
  const response=await fetch('/__proto/chem-science',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(request),cache:'no-store'});
  const payload=await response.json() as ChemScienceResponse<T>;
  if(!response.ok&&!payload.error)throw new Error(`Chemistry service returned HTTP ${response.status}.`);
  return payload;
}
function isMolecule(value:unknown):value is ChemMolecule{return !!value&&typeof value==='object'&&Array.isArray((value as ChemMolecule).atoms)&&Array.isArray((value as ChemMolecule).bonds);}
function OutputDetails({run,title,active=true}:{run:ChemScienceRun;title?:string;active?:boolean}){
  const result=run.result;
  const molecule=result&&[result.molecule,result].find(isMolecule);
  const tableRows=Array.isArray(result?.tables)?result.tables.flatMap((table:any)=>table&&Array.isArray(table.rows)?[JSON.stringify(table.rows)]:[]):[];
  const primaryResult=result&&Object.fromEntries(Object.entries(result).filter(([,value])=>!Array.isArray(value)||!tableRows.includes(JSON.stringify(value))));
  return <div className="chem-operator-output">
    {molecule&&<ChemReactionScene molecule={molecule as ChemMolecule} index={0}/>}
    {molecule&&<StructuredResult value={(molecule as ChemMolecule).descriptors}/>}
    {result&&(isReactionStudy(result)?<ChemReactionStudyResult result={result} active={active}/>:isInterfaceResult(result)?<ChemInterfaceResult result={result} active={active}/>:<OperatorVisuals result={result} operator={run.operator} title={title}/>)}
    {result&&['residual_visualization','scree_visualization'].map(key=>isChemDataVisualization(result[key])?<ChemDataChart key={key} data={result[key]} title={key==='scree_visualization'?'Explained variance':'Fit residuals'}/>:null)}
    {Array.isArray(result?.supplementary_visualizations)&&result.supplementary_visualizations.map((plot:any,i)=>isChemDataVisualization(plot)?<ChemDataChart key={`supplement-${i}`} data={plot} title={'title' in plot&&typeof plot.title==='string'?plot.title:'Additional result'}/>:null)}
    {primaryResult&&<StructuredResult value={primaryResult}/>}
    {result&&['summary','diagnostics','method'].map(key=>result[key]&&typeof result[key]==='object'&&!Array.isArray(result[key])?<section className="chem-result-section" key={key}><h3>{key}</h3><StructuredResult value={result[key] as Record<string,unknown>}/></section>:null)}
    {(isInterfaceResult(result)||isReactionStudy(result))&&<details className="chem-code-details"><summary>Model equations & resolved parameters</summary><pre>{JSON.stringify(run.result?.method,null,2)}</pre></details>}
    {Array.isArray(result?.tables)&&result.tables.map((table:any,i)=>table&&Array.isArray(table.rows)?<StructuredResult key={table.id||i} value={{[String(table.title||table.id||'Data')]:table.rows}}/>:null)}
    {Array.isArray(result?.warnings)&&result.warnings.map((warning,i)=><p className="chem-result-note" key={i}>{String(warning)}</p>)}
    <details className="chem-code-details"><summary><Code2 size={14}/> Full result JSON</summary><pre>{JSON.stringify(result||run.error,null,2)}</pre></details>
    <RunEvidence run={run}/>
  </div>;
}
function OperatorVisuals({result,operator,title}:{result:Record<string,unknown>;operator:string;title?:string}){
  if(isChemDataVisualization(result.visualization))return <ChemDataChart data={result.visualization} title={String(title||result.title||operator.replaceAll('_',' '))}/>;
  if(operator==='scan_reaction_temperature'&&Array.isArray(result.runs))return <TemperatureScan result={result}/>;
  if(operator==='fit_reaction_rates'&&Array.isArray(result.time_s))return <KineticFit result={result}/>;
  if(result.kind==='provided-xyz-trajectory'&&Array.isArray(result.frames))return <TrajectoryResult result={result as unknown as ChemTrajectoryView}/>;
  if(operator==='compare_molecules'&&isMolecule(result.original)&&isMolecule(result.proposed)){
    const before=result.original,after=result.proposed;
    return <section className="chem-result-table"><h3>Descriptor comparison</h3><div className="chem-table-scroll"><table><thead><tr><th>Descriptor</th><th>Original</th><th>Proposed</th><th>Change</th></tr></thead><tbody>{Object.entries(before.descriptors).map(([key,value])=><tr key={key}><td>{key.replaceAll('_',' ')}</td><td>{scientificNumber(value)}</td><td>{scientificNumber(after.descriptors[key])}</td><td>{scientificNumber(after.descriptors[key]-value)}</td></tr>)}</tbody></table></div></section>;
  }
  if(operator==='inspect_reaction_smiles')return <div className="chem-reaction-sides">{['reactants','products'].map(side=><ReactionSide key={side} side={side} molecules={Array.isArray(result[side])?(result[side] as unknown[]).filter(isMolecule):[]}/>)}</div>;
  return null;
}
function ReactionSide({side,molecules}:{side:string;molecules:ChemMolecule[]}){
  const [index,setIndex]=useState(0);const molecule=molecules[index];
  return <section><h3>{side}</h3>{molecules.length>1&&<select aria-label={`${side} molecule`} value={index} onChange={e=>setIndex(Number(e.target.value))}>{molecules.map((m,i)=><option key={i} value={i}>{i+1}. {m.formula} · {m.smiles}</option>)}</select>}{molecule&&<><ChemReactionScene molecule={molecule} index={0}/><p className="chem-result-note">{molecule.formula} · {molecule.smiles}</p></>}</section>;
}
function TemperatureScan({result}:{result:Record<string,unknown>}){
  const runs=result.runs as {temperature_k:number;time_s:number[];series:{id:string;concentration:number[]}[]}[];
  const [species,setSpecies]=useState(runs[0]?.series[0]?.id||'');const [frame,setFrame]=useState(0);
  if(!runs.length)return null;
  return <div className="chem-special-chart"><label className="chem-field">Compare species<select aria-label="Temperature sweep species" value={species} onChange={e=>setSpecies(e.target.value)}>{runs[0].series.map(s=><option value={s.id} key={s.id}>{s.id}</option>)}</select></label><ChemKineticsChart title="Temperature-dependent concentration" unit="mol L⁻¹" time={runs[0].time_s} series={runs.map(run=>({id:String(run.temperature_k),label:`${run.temperature_k} K`,values:run.series.find(s=>s.id===species)?.concentration||[]}))} index={frame} onIndex={setFrame}/></div>;
}
function KineticFit({result}:{result:Record<string,unknown>}){
  const time=result.time_s as number[],predicted=result.predicted as Record<string,number[]>,observations=result.observations as {concentrations:Record<string,number[]>};const [frame,setFrame]=useState(0);
  return <div className="chem-special-chart">{Object.entries(predicted).map(([id,values])=><ChemKineticsChart key={id} title={`${id} · fitted and observed`} unit="mol L⁻¹" time={time} series={[{id:`${id}-fit`,label:'Fitted',values},{id:`${id}-observed`,label:'Observed',values:observations.concentrations[id],pointsOnly:true}]} index={frame} onIndex={setFrame}/>)}<h3>Fit diagnostics</h3><StructuredResult value={result.diagnostics as Record<string,unknown>}/></div>;
}
function TrajectoryResult({result}:{result:ChemTrajectoryView}){
  const [frame,setFrame]=useState(0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState('1');
  useEffect(()=>{if(!playing)return;const interval=window.setInterval(()=>setFrame(index=>{if(index>=result.frames.length-1){setPlaying(false);return index;}return index+1;}),200/Number(speed));return()=>window.clearInterval(interval);},[playing,result,speed]);
  return <div className="chem-trajectory-result"><ChemReactionScene trajectory={result} index={frame}/><div className="chem-playback"><button aria-label={playing?'Pause XYZ trajectory':'Play XYZ trajectory'} onClick={()=>{if(frame>=result.frames.length-1)setFrame(0);setPlaying(v=>!v);}}>{playing?<Pause size={14}/>:<Play size={14}/>}</button><button aria-label="Next XYZ frame" onClick={()=>{setPlaying(false);setFrame(index=>Math.min(result.frames.length-1,index+1));}}><SkipForward size={14}/></button><input type="range" aria-label="XYZ trajectory timeline" min="0" max={result.frames.length-1} value={frame} onChange={e=>{setPlaying(false);setFrame(Number(e.target.value));}}/><output>{scientificNumber(result.frames[frame]?.time_fs)} fs</output><select aria-label="XYZ trajectory playback speed" value={speed} onChange={e=>setSpeed(e.target.value)}><option value=".5">0.5×</option><option value="1">1×</option><option value="2">2×</option></select></div><p className="chem-result-note">Frame {frame+1} / {result.frames.length} · {result.atom_count} atoms · {result.frames[frame]?.comment}</p></div>;
}
function StructuredResult({value}:{value:Record<string,unknown>}){
  const scalar=Object.entries(value).filter(([,v])=>v===null||['string','number','boolean'].includes(typeof v));
  const arrays=Object.entries(value).filter(([,v])=>Array.isArray(v)&&v.length>0&&v[0]&&typeof v[0]==='object'&&!Array.isArray(v[0])) as [string,Record<string,unknown>[]][];
  return <>
    {!!scalar.length&&<dl className="chem-scalar-results">{scalar.map(([key,v])=><div key={key}><dt>{key.replaceAll('_',' ')}</dt><dd>{typeof v==='number'?scientificNumber(v):String(v??'—')}</dd></div>)}</dl>}
    {arrays.filter(([key])=>!['atoms','bonds','frames','series','reaction_rates','tables','charts','supplementary_visualizations','sampled_trajectories'].includes(key)).map(([key,rows])=>{const columns=Array.from(new Set(rows.flatMap(row=>Object.keys(row).filter(k=>row[k]===null||['number','string','boolean'].includes(typeof row[k])))));return columns.length?<section className="chem-result-table" key={key}><div className="chem-result-table-heading"><h3>{key.replaceAll('_',' ')}</h3><button title="Export complete result table as CSV" onClick={()=>downloadChemFile(`chem-${key.toLowerCase().replace(/[^a-z0-9]+/g,'-')}.csv`,chemicalTableCsv(rows,columns),'text/csv;charset=utf-8')}><Download size={12}/>CSV · {rows.length} rows</button></div><div className="chem-table-scroll"><table><thead><tr>{columns.map(column=><th key={column}>{column.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.slice(0,100).map((row,i)=><tr key={i}>{columns.map(column=><td key={column}>{typeof row[column]==='number'?scientificNumber(row[column] as number):String(row[column]??'—')}</td>)}</tr>)}</tbody></table></div>{rows.length>100&&<p className="chem-result-note">Showing 100 of {rows.length} rows. Export CSV or JSON for the complete result.</p>}</section>:null;})}
  </>;
}
function RunEvidence({run}:{run:ChemScienceRun}){
  return <details className="chem-code-details"><summary>Run evidence <span>{run.runId.slice(0,8)}</span></summary><dl className="chem-run-evidence"><dt>Status</dt><dd>{run.status}</dd><dt>Data origin</dt><dd>{run.evidenceStanding?.dataOrigin??"unknown"}</dd><dt>Method maturity</dt><dd>{run.evidenceStanding?.methodMaturity??"not-established"}</dd><dt>Human review</dt><dd>{run.evidenceStanding?.humanReview??"required"}</dd><dt>Operator</dt><dd>{run.operator}</dd><dt>Created</dt><dd>{new Date(run.createdAt).toLocaleString()}</dd><dt>Input artifact</dt><dd>{run.artifacts.input}</dd><dt>Result artifact</dt><dd>{run.artifacts.result}</dd><dt>Manifest</dt><dd>{run.artifacts.manifest}</dd></dl><pre>{JSON.stringify(run.provenance||{},null,2)}</pre></details>;
}
function RunButtons({run,onCsv}:{run:ChemScienceRun;onCsv?:()=>void}){return <div className="chem-result-actions"><span className="chem-run-badge">{run.status} · {run.runId.slice(0,8)}</span><button type="button" onClick={()=>downloadChemFile(`chem-${run.operator}-${run.runId.slice(0,8)}.json`,JSON.stringify(run,null,2))}><Download size={14}/>JSON</button>{onCsv&&<button type="button" onClick={onCsv}><Download size={14}/>CSV</button>}</div>;}

export function ChemComputationWorkspace({active,section:controlledSection,onSection,workspacePath=''}:{active:boolean;section?:ChemComputationSection;onSection?:(section:ChemComputationSection)=>void;workspacePath?:string}){
  const [localSection,setLocalSection]=useState<ChemComputationSection>('analysis');const section=controlledSection||localSection;
  const navigate=(value:ChemComputationSection)=>{setLocalSection(value);onSection?.(value);};
  const [catalog,setCatalog]=useState<ChemScienceCatalog>(),[catalogLoading,setCatalogLoading]=useState(false),[error,setError]=useState('');
  const [network,setNetwork]=useState<ChemReactionNetwork>(initialNetwork),[networkText,setNetworkText]=useState(JSON.stringify(initialNetwork,null,2));
  const [duration,setDuration]=useState('60'),[temperature,setTemperature]=useState('298.15'),[points,setPoints]=useState('181'),[preset,setPreset]=useState('');
  const [editorOpen,setEditorOpen]=useState(true),[edited,setEdited]=useState(false),[simulationRun,setSimulationRun]=useState<ChemScienceRun>();
  const [index,setIndex]=useState(0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState('1');
  const [selectedOperator,setSelectedOperator]=useState('analyze_molecule'),[operatorInput,setOperatorInput]=useState(''),[operatorRun,setOperatorRun]=useState<ChemScienceRun>(),[operatorSearch,setOperatorSearch]=useState('');
  const [formIssue,setFormIssue]=useState(''),[formRevision,setFormRevision]=useState(0);
  const [openSection,setOpenSection]=useState<string>();
  const [simulatorFamily,setSimulatorFamily]=useState<ReactionFamily>('network');
  const operatorSection=section!=='history'&&(section!=='simulator'||simulatorFamily!=='network');
  const sectionOperators=section==='simulator'?(catalog?.operators||[]).filter(item=>reactionStudyFamily(item)===simulatorFamily):selectSectionOperators(catalog?.operators||[],section);
  const [history,setHistory]=useState<ChemScienceRun[]>([]),[historyLoading,setHistoryLoading]=useState(false),[pendingId,setPendingId]=useState(''),[pendingOperator,setPendingOperator]=useState('');
  const generation=useRef(0),initialized=useRef(false);
  const operatorDrafts=useRef(new Map<string,string>()),operatorResults=useRef(new Map<string,ChemScienceRun>()),fieldDrafts=useRef(new Map<string,ChemFieldDraft>());
  const clearFieldDrafts=(id:string)=>{for(const key of fieldDrafts.current.keys())if(key.startsWith(`${id}:`))fieldDrafts.current.delete(key);};
  const simulation=isReactionResult(simulationRun?.result)?simulationRun.result:undefined;
  const operator=catalog?.operators.find(item=>item.id===selectedOperator);
  const changeNetwork=(value:ChemReactionNetwork)=>{setNetwork(value);setNetworkText(JSON.stringify(value,null,2));setEdited(true);};
  const applyExample=useCallback((input:ChemSimulationInput,id:string)=>{if(input.network){setNetwork(input.network);setNetworkText(JSON.stringify(input.network,null,2));}setPreset(id);setDuration(String(input.duration_s??60));setTemperature(String(input.temperature_k??298.15));setPoints(String(input.points??181));setEdited(true);},[]);
  const refreshCatalog=useCallback(async()=>{const current=generation.current;setCatalogLoading(true);try{const response=await requestChem<ChemScienceCatalog>({action:'catalog'});if(current!==generation.current)return;if(!response.ok||!response.data)throw new Error(response.error?.message||'The chemistry catalog is unavailable.');setCatalog(response.data);if(!initialized.current){initialized.current=true;const example=response.data.examples[0];if(example)applyExample(example.input,example.id);}const first=response.data.operators.find(item=>item.id==='analyze_molecule')||response.data.operators[0];if(first)setOperatorInput(previous=>previous||JSON.stringify(first.example_input,null,2));}catch(reason){if(current===generation.current)setError(errorText(reason));}finally{if(current===generation.current)setCatalogLoading(false);}},[applyExample]);
  const refreshHistory=useCallback(async()=>{const current=generation.current;setHistoryLoading(true);try{const response=await requestChem<{runs:ChemScienceRun[]}>({action:'history',limit:80});if(current!==generation.current)return;if(!response.ok||!response.data)throw new Error(response.error?.message||'Run history is unavailable.');setHistory(response.data.runs);}catch(reason){if(current===generation.current)setError(errorText(reason));}finally{if(current===generation.current)setHistoryLoading(false);}},[]);
  useEffect(()=>{generation.current++;setSimulationRun(undefined);setOperatorRun(undefined);setPlaying(false);setPendingId('');setPendingOperator('');setError('');initialized.current=false;setOpenSection(undefined);setCatalog(undefined);setHistory([]);operatorDrafts.current.clear();operatorResults.current.clear();fieldDrafts.current.clear();},[workspacePath]);
  useEffect(()=>{if(active)void refreshCatalog();},[active,workspacePath,refreshCatalog]);
  useEffect(()=>{if(active&&section==='history')void refreshHistory();},[active,section,workspacePath,refreshHistory]);
  useEffect(()=>{if(!active)setPlaying(false);},[active]);
  useEffect(()=>{
    if(!playing||!simulation)return;
    const started=performance.now(),initialTime=simulation.time_s[index]||0;
    const timer=window.setInterval(()=>{const target=initialTime+(performance.now()-started)/1000*Number(speed);let low=0,high=simulation.time_s.length-1;while(low<high){const middle=Math.ceil((low+high)/2);if(simulation.time_s[middle]<=target)low=middle;else high=middle-1;}setIndex(low);if(target>=simulation.time_s.at(-1)!)setPlaying(false);},50);
    return()=>window.clearInterval(timer);
  },[playing,speed,simulation]);
  const selectOperator=(item:ChemScienceOperator)=>{if(operatorInput)operatorDrafts.current.set(selectedOperator,operatorInput);setSelectedOperator(item.id);setOperatorInput(operatorDrafts.current.get(item.id)||JSON.stringify(item.example_input,null,2));setOperatorRun(operatorResults.current.get(item.id));setFormIssue('');setFormRevision(value=>value+1);setError('');};
  useEffect(()=>{setOperatorSearch('');setError('');},[section]);
  useEffect(()=>{if(!operatorSection||!sectionOperators.length)return;if(!sectionOperators.some(item=>item.id===selectedOperator))selectOperator(sectionOperators[0]);},[section,catalog,selectedOperator,simulatorFamily]);
  async function execute(name:string,input:Record<string,unknown>){
    if(pendingId)return;
    const runId=crypto.randomUUID(),current=generation.current;setPendingId(runId);setPendingOperator(name);setError('');setPlaying(false);
    try{
      const response=await requestChem<ChemScienceRun>({action:'run',operator:name,input,runId,timeoutMs:120000});if(current!==generation.current)return;
      if(response.data){if(name==='simulate_reaction_network'){setSimulationRun(response.data);setIndex(0);setEdited(false);}else{operatorResults.current.set(name,response.data);setOperatorRun(response.data);}}
      if(!response.ok)throw new Error(response.error?.message||response.data?.error?.message||'The operator could not complete.');
      void refreshHistory();
    }catch(reason){if(current===generation.current)setError(errorText(reason));}finally{if(current===generation.current){setPendingId('');setPendingOperator('');}}
  }
  function runSimulation(){try{const parsed=parseNetworkDraft(networkText);if(!Number.isFinite(Number(duration))||Number(duration)<=0||!Number.isFinite(Number(temperature))||Number(temperature)<=0||!Number.isInteger(Number(points)))throw new Error('Duration and temperature must be positive; samples must be an integer.');setNetwork(parsed);void execute('simulate_reaction_network',{network:parsed,duration_s:Number(duration),temperature_k:Number(temperature),points:Number(points)});}catch(reason){setError(errorText(reason));}}
  async function readRun(run:ChemScienceRun){setError('');try{const response=await requestChem<ChemScienceRun>({action:'read',runId:run.runId});if(!response.ok||!response.data)throw new Error(response.error?.message||'The run could not be read.');if(response.data.operator==='simulate_reaction_network'){const restored=restoreSimulationInput(response.data.input,response.data.result);parseNetworkDraft(JSON.stringify(restored.network));initialized.current=true;applyExample(restored,restored.example||'');setSimulationRun(response.data);setIndex(0);setPlaying(false);setEdited(false);setSimulatorFamily('network');navigate('simulator');}else{if(operatorInput)operatorDrafts.current.set(selectedOperator,operatorInput);operatorDrafts.current.set(response.data.operator,JSON.stringify(response.data.input,null,2));operatorResults.current.set(response.data.operator,response.data);clearFieldDrafts(response.data.operator);setOperatorRun(response.data);setSelectedOperator(response.data.operator);setOperatorInput(JSON.stringify(response.data.input,null,2));setFormRevision(value=>value+1);setFormIssue('');const item=catalog?.operators.find(operator=>operator.id===response.data!.operator);const family=item?reactionStudyFamily(item):undefined;const destination=family?'simulator':item?operatorWorkspace(item):'operators';if(family)setSimulatorFamily(family);setOpenSection(destination);navigate(destination);}}catch(reason){setError(errorText(reason));}}
  function useNetworkEditor(){try{if(!operator)return;const input=JSON.parse(operatorInput);const settings={duration_s:Number(duration),points:Number(points),temperature_k:Number(temperature)};if(Object.values(settings).some(value=>!Number.isFinite(value)||value<=0)||!Number.isInteger(settings.points))throw new Error('Network editor settings must be positive finite numbers with an integer sample count.');const copied=reactionStudyInputFromNetwork(operator.id,parseNetworkDraft(networkText),input,settings);clearFieldDrafts(operator.id);setOperatorInput(JSON.stringify(copied,null,2));setFormRevision(value=>value+1);setFormIssue('');setError('');}catch(reason){setError(errorText(reason));}}
  const {title,description}=CHEM_SECTION_COPY[section];
  const currentOperatorRun=operatorRun?.operator===selectedOperator?operatorRun:undefined;
  const operatorEdited=!!currentOperatorRun&&JSON.stringify(currentOperatorRun.input)!==(()=>{try{return JSON.stringify(JSON.parse(operatorInput));}catch{return operatorInput;}})();
  return <section id="chem-compute-workspace" className="chem-computation-workspace" role="tabpanel" aria-labelledby="mode-compute" hidden={!active} aria-label="Chem computation workspace">
    {(!operatorSection||openSection!==section)&&<header className="chem-computation-heading"><div><p className="chem-eyebrow">CHEM · COMPUTATION</p><h1>{title}</h1><p>{description}</p></div><div className="chem-heading-actions">{catalogLoading&&<LoaderCircle size={17} className="spin"/>}<button type="button" title="Refresh chemistry runtime and catalog" aria-label="Refresh chemistry runtime" onClick={()=>{setError('');void refreshCatalog();}}><RefreshCw size={15}/></button>{section==='simulator'&&simulatorFamily==='network'&&<button type="button" aria-pressed={editorOpen} onClick={()=>setEditorOpen(value=>!value)}><Settings2 size={15}/>Model</button>}</div></header>}
    {error&&<div className="chem-error-banner" role="alert"><strong>Calculation needs attention</strong><span>{error}</span><button aria-label="Dismiss chemistry error" onClick={()=>setError('')}>×</button></div>}
    {pendingId&&<div className="chem-running-banner" role="status"><LoaderCircle className="spin" size={15}/><span>Running {catalog?.operators.find(item=>item.id===pendingOperator)?.title||pendingOperator} locally. Saving inputs and execution evidence.</span><button type="button" onClick={()=>{void requestChem<ChemScienceRun>({action:'cancel',runId:pendingId}).then(response=>{if(!response.ok)setError(response.error?.message||'Cancellation could not be requested.');}).catch(reason=>setError(errorText(reason)));}}><Square size={12}/>Cancel</button></div>}
    {section==='simulator'&&<div className="analysis-collection-tabs chem-simulation-families" role="group" aria-label="Reaction simulation family">{REACTION_FAMILIES.map(family=><button key={family.id} type="button" aria-pressed={simulatorFamily===family.id} onClick={()=>{setSimulatorFamily(family.id);setOpenSection(undefined);setPlaying(false);}}>{family.label}</button>)}<span>One catalog · Saved inputs & results</span></div>}
    {section==='simulator'&&simulatorFamily==='network'&&<>
      <div className="chem-simulation-toolbar"><label>Example<select aria-label="Reaction example" value={preset} onChange={event=>{const example=catalog?.examples.find(item=>item.id===event.target.value);if(example)applyExample(example.input,example.id);}}><option value="">Custom reaction network</option>{catalog?.examples.map(example=><option value={example.id} key={example.id}>{example.title}</option>)}</select></label><label>Temperature <span>K</span><input aria-label="Temperature K" type="number" min="1" step=".1" value={temperature} onChange={e=>{setTemperature(e.target.value);setEdited(true);}}/></label><label>Duration <span>s</span><input aria-label="Duration seconds" type="number" min=".001" value={duration} onChange={e=>{setDuration(e.target.value);setEdited(true);}}/></label><label>Samples<input aria-label="Simulation samples" type="number" min="2" max="1001" value={points} onChange={e=>{setPoints(e.target.value);setEdited(true);}}/></label><button type="button" className="chem-primary primary-button" disabled={!!pendingId||!catalog?.operators.find(item=>item.id==='simulate_reaction_network')?.available} onClick={runSimulation}><Play size={15}/>{pendingOperator==='simulate_reaction_network'?'Calculating…':'Run simulation'}</button></div>
      <div className={`chem-simulator-layout${editorOpen?' has-editor':''}`}>
        {editorOpen&&<aside className="chem-network-editor" aria-label="Reaction model editor"><div className="chem-panel-title"><h2>Reaction model</h2><span>{network.species.length} species · {network.reactions.length} steps</span></div><label className="chem-field">Model name<input value={network.label||''} aria-label="Reaction model name" onChange={e=>changeNetwork({...network,label:e.target.value})}/></label><div className="chem-editor-section-title"><h3>Species</h3><button type="button" title="Add species" aria-label="Add reaction species" onClick={()=>{let id=`S${network.species.length+1}`;while(network.species.some(s=>s.id===id))id+='x';changeNetwork({...network,species:[...network.species,{id,label:id,initial_concentration:0}]});}}><Plus size={13}/></button></div>
          {network.species.map((species,i)=><div className="chem-species-row" key={species.id}><div><i style={{background:CHEM_SERIES_COLORS[i%CHEM_SERIES_COLORS.length]}}/><code>{species.id}</code><input aria-label={`Label for ${species.id}`} value={species.label||species.id} onChange={e=>changeNetwork({...network,species:network.species.map((s,j)=>j===i?{...s,label:e.target.value}:s)})}/><button type="button" aria-label={`Remove species ${species.id}`} onClick={()=>changeNetwork({...network,species:network.species.filter((_,j)=>j!==i),reactions:network.reactions.filter(r=>!(species.id in r.reactants)&&!(species.id in r.products))})}><Trash2 size={12}/></button></div><label>Initial concentration / M<input type="number" min="0" step="any" aria-label={`Initial concentration ${species.id}`} value={species.initial_concentration} onChange={e=>changeNetwork({...network,species:network.species.map((s,j)=>j===i?{...s,initial_concentration:Number(e.target.value)}:s)})}/></label><input className="chem-smiles-input" aria-label={`SMILES for ${species.id}`} placeholder="SMILES · optional molecular geometry" value={species.smiles||''} onChange={e=>changeNetwork({...network,species:network.species.map((s,j)=>j===i?{...s,smiles:e.target.value||undefined}:s)})}/></div>)}
          <div className="chem-editor-section-title"><h3>Elementary steps</h3><button type="button" aria-label="Add reaction step" disabled={network.species.length<2} onClick={()=>{let id=`r${network.reactions.length+1}`;while(network.reactions.some(r=>r.id===id))id+='x';changeNetwork({...network,reactions:[...network.reactions,{id,reactants:{[network.species[0].id]:1},products:{[network.species[1].id]:1},rate_constant:.1}]});}}><Plus size={13}/></button></div>
          {network.reactions.map((reaction,i)=><div className="chem-reaction-row" key={reaction.id}><div><code>{stoichiometry(reaction.reactants)} <ArrowRight size={12}/> {stoichiometry(reaction.products)}</code><button type="button" aria-label={`Remove reaction ${reaction.id}`} onClick={()=>changeNetwork({...network,reactions:network.reactions.filter((_,j)=>j!==i)})}><Trash2 size={12}/></button></div><label>k at reference temperature<input type="number" min="0" step="any" aria-label={`Rate constant ${reaction.id}`} value={reaction.rate_constant} onChange={e=>changeNetwork({...network,reactions:network.reactions.map((r,j)=>j===i?{...r,rate_constant:Number(e.target.value)}:r)})}/></label><small>{Object.values(reaction.reactants).reduce((a,b)=>a+b,0)===1?'s⁻¹':`M^${1-Object.values(reaction.reactants).reduce((a,b)=>a+b,0)} s⁻¹`} · {reaction.id}</small><details><summary>Arrhenius parameters</summary><label>Activation energy / J mol⁻¹<input type="number" step="any" aria-label={`Activation energy ${reaction.id}`} value={reaction.activation_energy_j_mol??0} onChange={e=>changeNetwork({...network,reactions:network.reactions.map((r,j)=>j===i?{...r,activation_energy_j_mol:Number(e.target.value)}:r)})}/></label><label>Reference temperature / K<input type="number" min="1" step="any" aria-label={`Reference temperature ${reaction.id}`} value={reaction.reference_temperature_k??298.15} onChange={e=>changeNetwork({...network,reactions:network.reactions.map((r,j)=>j===i?{...r,reference_temperature_k:Number(e.target.value)}:r)})}/></label></details></div>)}
          <details className="chem-code-details"><summary><Code2 size={13}/>Edit complete network</summary><p>Change species IDs, stoichiometry, composition and reaction steps in JSON. Run simulation applies this document.</p><textarea spellCheck={false} aria-label="Reaction network JSON" value={networkText} onChange={e=>{setNetworkText(e.target.value);setEdited(true);}}/><button type="button" onClick={()=>{try{const value=parseNetworkDraft(networkText);changeNetwork(value);setError('');}catch(reason){setError(errorText(reason));}}}>Apply to form</button></details><p className="chem-result-note">Mass-action rate constants and the reaction mechanism are supplied inputs. Molecular geometry does not establish a reaction pathway.</p>
        </aside>}
        <div className="chem-simulator-canvas">{simulation&&simulationRun&&<div className="chem-saved-result-context" role="status"><span>Saved result · <code>{simulationRun.runId.slice(0,8)}</code> · {scientificNumber(simulation.time_s.at(-1))} s · {simulation.time_s.length} samples · {scientificNumber(simulation.temperature_k)} K</span>{edited&&<strong>Inputs changed. The scene and charts still show this previous run; run the edited model to update them.</strong>}</div>}<ChemReactionScene result={simulation} index={index} active={active}/>
          <div className="chem-playback"><button aria-label="First simulation frame" disabled={!simulation} onClick={()=>{setPlaying(false);setIndex(0);}}><SkipBack size={15}/></button><button aria-label={playing?'Pause reaction playback':'Play reaction playback'} disabled={!simulation} onClick={()=>{if(simulation&&index>=simulation.time_s.length-1)setIndex(0);setPlaying(value=>!value);}}>{playing?<Pause size={16}/>:<Play size={16}/>}</button><button aria-label="Next simulation frame" disabled={!simulation||index>=(simulation?.time_s.length||1)-1} onClick={()=>{setPlaying(false);setIndex(value=>Math.min((simulation?.time_s.length||1)-1,value+1));}}><SkipForward size={15}/></button><input type="range" aria-label="Reaction timeline" min="0" max={(simulation?.time_s.length||1)-1} value={index} disabled={!simulation} onChange={e=>{setPlaying(false);setIndex(Number(e.target.value));}}/><output>{scientificNumber(simulation?.time_s[index])} s</output><select aria-label="Reaction playback speed" value={speed} onChange={e=>setSpeed(e.target.value)}><option value=".5">0.5×</option><option value="1">1×</option><option value="2">2×</option><option value="4">4×</option></select></div>
          {simulation?<><div className="chem-live-species">{simulation.series.map((species,i)=><div key={species.id}><i style={{background:CHEM_SERIES_COLORS[i%CHEM_SERIES_COLORS.length]}}/><span>{species.label||species.id}</span><strong>{scientificNumber(species.concentration[index])}<small>M</small></strong></div>)}</div>{simulationRun&&<RunButtons run={simulationRun} onCsv={()=>downloadChemFile(`chem-kinetics-${simulationRun.runId.slice(0,8)}.csv`,reactionCsv(simulation),'text/csv;charset=utf-8')}/>}<div className="chem-kinetic-charts"><ChemKineticsChart title="Concentration" unit="mol L⁻¹" time={simulation.time_s} series={simulation.series.map((s,i)=>({id:s.id,label:s.label,values:s.concentration,color:CHEM_SERIES_COLORS[i%CHEM_SERIES_COLORS.length]}))} index={index} onIndex={i=>{setPlaying(false);setIndex(i);}}/><ChemKineticsChart title="Reaction rate" unit="mol L⁻¹ s⁻¹" time={simulation.time_s} series={simulation.reaction_rates.map(s=>({id:s.id,values:s.rate}))} index={index} onIndex={i=>{setPlaying(false);setIndex(i);}}/><ChemKineticsChart title="Conversion" unit="fraction of initial concentration" time={simulation.time_s} series={simulation.series.map((s,i)=>({id:s.id,label:s.label,values:s.conversion,color:CHEM_SERIES_COLORS[i%CHEM_SERIES_COLORS.length]}))} index={index} onIndex={i=>{setPlaying(false);setIndex(i);}}/></div><div className="chem-simulation-evidence"><h3>Method & consistency</h3><p>{simulation.method.solver} · {simulation.method.model} · {simulation.method.nfev} function evaluations</p><p>{simulation.conservation.chemically_balanced===true?'Element balance verified for the declared compositions.':simulation.conservation.chemically_balanced===false?'The declared network is not element-balanced.':'Element balance cannot be established without species compositions.'}</p>{simulation.conservation.element_balance.map(item=><span key={item.element}>{item.element}: max drift <code>{scientificNumber(item.max_absolute_drift)}</code></span>)}{simulation.warnings?.map((warning,i)=><p className="chem-result-note" key={i}>{warning}</p>)}</div>{simulationRun&&<RunEvidence run={simulationRun}/>}</>:<div className="chem-simulator-intro"><Activity size={20}/><h2>From a model to a moving picture.</h2><p>Choose an illustrative network or define your own species and elementary steps. The local solver generates concentration, reaction-rate and conversion curves; the timeline keeps every view on the same sample.</p><div><span>1. Define the model</span><span>2. Calculate kinetics</span><span>3. Inspect & export</span></div></div>}
        </div>
      </div>
    </>}
    {operatorSection&&(openSection!==section||!operator?<ChemToolLibrary key={`${section}:${simulatorFamily}`} operators={sectionOperators} loading={catalogLoading} search={operatorSearch} onSearch={setOperatorSearch} onSelect={item=>{if(item.id==='simulate_reaction_network'){setSimulatorFamily('network');navigate('simulator');return;}selectOperator(item);setOpenSection(section);}}/>:<ChemToolDesk key={operator.id} operator={operator} onBack={()=>setOpenSection(undefined)} hasResult={!!currentOperatorRun}
      inputs={<><div className="analysis-panel-title"><h2>Inputs & method</h2><button onClick={()=>{clearFieldDrafts(operator.id);setOperatorInput(JSON.stringify(operator.example_input,null,2));setFormRevision(v=>v+1);setFormIssue('');setError('');}}>Load example</button></div><p className="analysis-description">{operator.description}</p>{operator.input_schema.properties&&'network' in (operator.input_schema.properties as Record<string,unknown>)&&operator.id!=='fit_reaction_rates'&&operator.id!=='scan_reaction_temperature'&&<button type="button" className="quiet-button" onClick={useNetworkEditor}>Use network editor<ArrowRight size={14}/></button>}{reactionStudyFamily(operator)&&section!=='simulator'&&<button type="button" className="quiet-button" onClick={()=>{setSimulatorFamily(reactionStudyFamily(operator)!);setOpenSection('simulator');navigate('simulator');}}>Open in Reaction Sim<ArrowRight size={14}/></button>}{!operator.available&&<div className="chem-error-banner">{operator.unavailable_reason}</div>}<ChemOperatorForm key={`${selectedOperator}:${formRevision}`} operator={operator} source={operatorInput} onChange={setOperatorInput} onIssue={setFormIssue} fieldDrafts={fieldDrafts.current}/><details className="chem-code-details"><summary>Complete input JSON</summary><textarea aria-label="Chemistry operator input JSON" spellCheck={false} value={operatorInput} onChange={e=>{clearFieldDrafts(selectedOperator);setOperatorInput(e.target.value);setFormRevision(v=>v+1);setFormIssue('');}}/></details><details className="chem-code-details"><summary>Input schema</summary><pre>{JSON.stringify(operator.input_schema,null,2)}</pre></details><button className="chem-primary primary-button analysis-run" disabled={!!pendingId||!operator.available||!!formIssue} onClick={()=>{try{const input=JSON.parse(operatorInput);if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('Operator input must be a JSON object.');void execute(operator.id,input);}catch(reason){setError(errorText(reason));}}}><Play size={14}/>{section==='simulator'?'Run simulation':'Run analysis'}</button>{formIssue&&<p className="chem-input-error" role="alert">Correct the marked input before running: {formIssue}</p>}</>}
      result={currentOperatorRun&&<>{operatorEdited&&<p className="chem-saved-result-context" role="status">Inputs changed. This result belongs to the saved run; run the edited analysis to update it.</p>}<RunButtons run={currentOperatorRun}/><OutputDetails key={currentOperatorRun.runId} run={currentOperatorRun} title={operator.title} active={active}/></>}
      inputRecord={currentOperatorRun&&<><p className="analysis-description">Exact input snapshot for this result. Editing the form does not change this record.</p><pre className="analysis-json">{JSON.stringify(currentOperatorRun.input,null,2)}</pre></>}
      provenance={currentOperatorRun&&<><h2>Every result has a history.</h2><p className="analysis-description">{operator.source}</p><RunEvidence run={currentOperatorRun}/><pre className="analysis-json">{JSON.stringify(currentOperatorRun.provenance,null,2)}</pre></>}
    />)}
    {section==='history'&&<div className="chem-history"><div className="chem-history-toolbar"><span>{history.length} saved runs</span><button onClick={()=>void refreshHistory()} disabled={historyLoading}><RefreshCw size={14} className={historyLoading?'spin':''}/>Refresh history</button></div>{history.length?<div className="chem-history-list">{history.map(run=><button className="chem-history-row" key={run.runId} onClick={()=>void readRun(run)}><Clock3 size={17}/><div><strong>{catalog?.operators.find(item=>item.id===run.operator)?.title||run.operator}</strong><span>{new Date(run.createdAt).toLocaleString()} · {run.runId.slice(0,8)}</span>{run.error&&<span>{run.error.message}</span>}</div><span className="chem-run-badge">{run.status}</span><ArrowRight size={16}/></button>)}</div>:<div className="chem-empty-state"><Clock3 size={27}/><h2>{historyLoading?'Reading saved runs…':'Your calculations will live here.'}</h2><p>Each run keeps its original input, result and provenance. Calculations started from Chat use this same history.</p><button onClick={()=>navigate('simulator')}>Open reaction simulator</button></div>}</div>}
  </section>;
}
