import { createContext, useContext, useEffect, useMemo, useState, useRef } from 'react';
import { Upload } from 'lucide-react';
import type { ChemScienceOperator } from '../shared/chem-science-api.ts';
import { molecularRecords, mapChemTable, numericValues, replicateValues, parseChemTable, type ParsedChemTable, type ChemImportField } from './chem-analysis-input.ts';

type Schema={anyOf?:Schema[];type?:string;title?:string;description?:string;enum?:unknown[];properties?:Record<string,Schema>;items?:Schema;required?:string[];minimum?:number;maximum?:number;default?:unknown};
type ImportField=ChemImportField;
export type ChemFieldDraft={draft:string;error:string;serialized:string|undefined};
const FieldDraftContext=createContext<{operator:string;drafts:Map<string,ChemFieldDraft>}>({operator:'',drafts:new Map()});
const label=(value:string)=>({ph_values:'pH values',pka_values:'pKa values',frequencies_hz:'Frequencies / Hz',z_real_ohm:'Re(Z) / Ω',z_imag_ohm:'Im(Z) / Ω'}[value]||value.replaceAll('_',' ').replace(/^./,char=>char.toUpperCase()));
const record=(value:unknown):value is Record<string,unknown>=>!!value&&typeof value==='object'&&!Array.isArray(value);
const message=(error:unknown)=>error instanceof Error?error.message:String(error);

function DraftInput({value,convert,onChange,onIssue,caption,format,path}:{path:string;value:unknown;convert:(value:string)=>unknown;onChange:(value:unknown)=>void;onIssue:(value:string)=>void;caption:string;format:(value:unknown)=>string}){
  const context=useContext(FieldDraftContext),cacheKey=`${context.operator}:${path}`,saved=context.drafts.get(cacheKey);
  const serialized=JSON.stringify(value),[draft,setDraft]=useState(()=>saved?.serialized===JSON.stringify(value)?saved.draft:format(value)),[error,setError]=useState(()=>saved?.serialized===JSON.stringify(value)?saved.error:'');
  useEffect(()=>{const cached=context.drafts.get(cacheKey);if(cached&&cached.serialized===serialized){setDraft(cached.draft);setError(cached.error);onIssue(cached.error);}else{setDraft(format(value));setError('');onIssue('');}},[serialized]);
  useEffect(()=>()=>onIssue(''),[]);
  return <><textarea aria-label={caption} spellCheck={false} value={draft} onChange={event=>{const next=event.target.value;setDraft(next);try{const parsed=convert(next);context.drafts.set(cacheKey,{draft:next,error:'',serialized:JSON.stringify(parsed)});setError('');onIssue('');onChange(parsed);}catch(reason){const text=message(reason);context.drafts.set(cacheKey,{draft:next,error:text,serialized});setError(text);onIssue(text);}}}/>{error&&<span className="chem-input-error" role="alert">{error}</span>}</>;
}
function SchemaField({name,schema,value,onChange,path,onIssue,depth=0}:{name:string;schema:Schema;value:unknown;onChange:(value:unknown)=>void;path:string;onIssue:(path:string,error:string)=>void;depth?:number}){
  value=value??schema.default;
  const type=schema.type||(Array.isArray(value)?'array':record(value)?'object':typeof value),caption=schema.title||label(name),issue=(error:string)=>onIssue(path,error);
  const help=schema.description&&<small>{schema.description}</small>;
  if(type==='object'&&(depth>=3||name==='feed_mol_l'||name==='reaction_enthalpy_j_mol'))return <label className="chem-schema-field chem-schema-wide"><span>{caption}</span><DraftInput path={path} value={value??{}} caption={caption+' JSON'} format={raw=>JSON.stringify(raw,null,2)} convert={text=>{const parsed=JSON.parse(text);if(!record(parsed))throw new Error('Enter a JSON object.');return parsed;}} onChange={onChange} onIssue={issue}/>{help}</label>;
  if(type==='object'&&depth<3&&(schema.properties||record(value))){const object=record(value)?value:{},properties=schema.properties||Object.fromEntries(Object.keys(object).map(key=>[key,{}]));return <fieldset className="chem-form-group"><legend>{caption}</legend>{help}<div className="chem-schema-fields">{Object.entries(properties).map(([key,child])=><SchemaField key={key} name={key} path={`${path}.${key}`} schema={child} value={object[key]} depth={depth+1} onIssue={onIssue} onChange={next=>onChange({...object,[key]:next})}/>)}</div></fieldset>;}
  if(type==='boolean')return <label className="chem-schema-checkbox"><input type="checkbox" checked={value===true} onChange={event=>onChange(event.target.checked)}/><span>{caption}{help}</span></label>;
  if(schema.enum)return <label className="chem-schema-field"><span>{caption}</span><select aria-label={caption} value={String(value??'')} onChange={event=>onChange(schema.enum!.find(item=>String(item)===event.target.value))}>{value===undefined&&<option value="">Default</option>}{schema.enum.map(item=><option key={String(item)} value={String(item)}>{String(item).replaceAll('_',' ')}</option>)}</select>{help}</label>;
  if(type==='array'){
    const array=Array.isArray(value)?value:[],item=schema.items||{};
    if(name==='samples')return <label className="chem-schema-field chem-schema-wide"><span>Sample matrix</span><DraftInput path={path} value={array} caption="PCA sample matrix" format={raw=>(raw as {id:string;values:number[]}[]||[]).map(row=>[row.id,...row.values].join('\t')).join('\n')} convert={text=>text.split(/\r?\n/).filter(line=>line.trim()).map((line,i)=>{const [id,...values]=line.split('\t');if(!id.trim()||!values.length)throw new Error(`Sample ${i+1}: enter an ID, then numeric features separated by tabs.`);return{id:id.trim(),values:numericValues(values.join(' '))};})} onChange={onChange} onIssue={issue}/><small>One sample per line: ID → tab → one numeric value per feature in the column order above. CSV / TSV import also builds this matrix.</small></label>;
    if(name==='records')return <label className="chem-schema-field chem-schema-wide"><span>Molecular records</span><DraftInput path={path} value={array} caption="Molecular records SMILES" format={raw=>(raw as {id?:string;smiles:string}[]||[]).map(row=>`${row.id?`${row.id}\t`:''}${row.smiles}`).join('\n')} convert={molecularRecords} onChange={onChange} onIssue={issue}/><small>One SMILES per line, or ID → tab → SMILES. Molecules are validated by the chemistry runtime.</small></label>;
    if(item.type==='object'||array.some(record))return <fieldset className="chem-form-group chem-schema-wide"><legend>{caption}</legend>{help}{array.map((entry,i)=><div className="chem-array-row" key={i}><SchemaField name={`${name} ${i+1}`} path={`${path}.${i}`} schema={{...item,type:'object'}} value={entry} onChange={next=>onChange(array.map((old,j)=>j===i?next:old))} onIssue={onIssue} depth={depth+1}/><button type="button" aria-label={`Remove ${caption} ${i+1}`} onClick={()=>onChange(array.filter((_,j)=>j!==i))}>Remove</button></div>)}<button type="button" onClick={()=>onChange([...array,Object.fromEntries(Object.entries(item.properties||{}).map(([key,child])=>[key,child.default??(child.type==='array'?[]:child.type==='number'||child.type==='integer'?0:'')]))])}>Add {caption.toLowerCase().replace(/s$/,'')}</button></fieldset>;
    const nullable=item.anyOf?.some(choice=>choice.type==='null')===true;
    const numbers=item.type==='number'||item.type==='integer'||array.some(v=>typeof v==='number')||name==='values',matrix=item.type==='array'||array.some(Array.isArray);
    return <label className="chem-schema-field chem-schema-wide"><span>{caption}</span><DraftInput path={path} value={array} caption={caption} onIssue={issue} format={raw=>matrix?(raw as unknown[][]||[]).map(row=>row.join('\t')).join('\n'):(raw as unknown[]||[]).map(value=>value===null?'null':value).join(numbers?', ':'\n')} convert={text=>matrix?text.trim().split(/\r?\n/).filter(Boolean).map(numericValues):numbers?(nullable?replicateValues(text):numericValues(text)):text.split(/\r?\n/).map(value=>value.trim()).filter(Boolean)} onChange={onChange}/>{help||<small>{matrix?'One sample per row; numeric features separated by tabs or commas.':numbers?`Separate numeric measurements with spaces, commas or new lines.${nullable?' Use null for an explicitly missing replicate.':''}`:'One value per line.'}</small>}</label>;
  }
  const numeric=type==='number'||type==='integer';
  return <label className={`chem-schema-field${name==='xyz'?' chem-schema-wide':''}`}><span>{caption}</span>{name==='xyz'?<textarea aria-label={caption} value={String(value??'')} spellCheck={false} onChange={event=>onChange(event.target.value)}/>:<input aria-label={caption} type={numeric?'number':'text'} step={type==='integer'?1:'any'} min={schema.minimum} max={schema.maximum} value={value===null||value===undefined?'':String(value)} onChange={event=>onChange(numeric?(event.target.value===''?undefined:Number(event.target.value)):event.target.value)}/>}{help}</label>;
}

function TableImport({fields,onApply}:{fields:Array<{key:string;title:string;kind:'number'|'text'|'matrix'|'records'}>;onApply:(patch:Record<string,unknown>)=>void}){
  const [text,setText]=useState(''),[delimiter,setDelimiter]=useState<','|'\t'>(','),[hasHeader,setHasHeader]=useState(true),[table,setTable]=useState<ParsedChemTable>(),[error,setError]=useState(''),[mappings,setMappings]=useState<Record<string,string>>({}),[matrixColumns,setMatrixColumns]=useState<number[]>([]),[applied,setApplied]=useState(false);
  const reset=()=>{setTable(undefined);setMappings({});setMatrixColumns([]);setApplied(false);setError('');};
  const preview=()=>{try{const parsed=parseChemTable(text,delimiter,hasHeader);setTable(parsed);setMappings({});setMatrixColumns([]);setApplied(false);setError('');}catch(reason){setError(message(reason));setTable(undefined);}};
  return <details className="chem-table-import"><summary><Upload size={13}/>Import measured data · CSV / TSV</summary><p>Preview the table, choose each column, then apply it to the form. Existing values change only when you apply the mapping.</p><div className="chem-import-toolbar"><label className="chem-file-button">Choose CSV / TSV<input type="file" accept=".csv,.tsv,.txt,text/csv,text/tab-separated-values,text/plain" onChange={async event=>{const file=event.target.files?.[0];if(!file)return;reset();try{if(file.size>2_000_000)throw new Error('Choose a file smaller than 2 MB.');setText(await file.text());setDelimiter(file.name.toLowerCase().endsWith('.tsv')?'\t':',');}catch(reason){setError(message(reason));}event.target.value='';}}/></label><label>Separator<select aria-label="Data separator" value={delimiter} onChange={event=>{setDelimiter(event.target.value as ','|'\t');reset();}}><option value=",">Comma</option><option value={'\t'}>Tab</option></select></label><label><input type="checkbox" checked={hasHeader} onChange={event=>{setHasHeader(event.target.checked);reset();}}/>First row is a header</label></div><textarea aria-label="Paste chemistry CSV or TSV" placeholder={'wavelength_nm,signal\n400,0.12\n450,0.36'} spellCheck={false} value={text} onChange={event=>{setText(event.target.value);reset();}}/><button type="button" onClick={preview}>Preview columns</button>{error&&<p className="chem-input-error" role="alert">{error}</p>}
    {table&&<><p className="chem-import-count">{table.rows.length} rows · {table.columns.length} columns. Previewing the first 5 rows.</p><div className="chem-table-scroll"><table><thead><tr>{table.columns.map(column=><th key={column}>{column}</th>)}</tr></thead><tbody>{table.rows.slice(0,5).map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell}</td>)}</tr>)}</tbody></table></div><div className="chem-column-mapping">{fields.map(field=>field.kind==='matrix'?<fieldset key={field.key}><legend>{field.title} · select numeric features in column order</legend>{table.columns.map((column,i)=><label key={column}><input type="checkbox" checked={matrixColumns.includes(i)} onChange={event=>setMatrixColumns(previous=>event.target.checked?[...previous,i].sort((a,b)=>a-b):previous.filter(value=>value!==i))}/>{column}</label>)}</fieldset>:<label key={field.key}>{field.title}<select aria-label={`Column for ${field.title}`} value={mappings[field.key]??''} onChange={event=>setMappings(previous=>({...previous,[field.key]:event.target.value}))}><option value="">Keep current values</option>{table.columns.map((column,i)=><option key={column} value={i}>{column}</option>)}</select></label>)}</div><button type="button" onClick={()=>{try{const patch=mapChemTable(table,fields,mappings,matrixColumns);onApply(patch);setApplied(true);setError('');}catch(reason){setError(message(reason));setApplied(false);}}}>Apply selected columns</button>{applied&&<p role="status" className="chem-result-note">Columns applied. Review the form and units before running.</p>}</>}
  </details>;
}

export function ChemOperatorForm({operator,source,onChange,onIssue,fieldDrafts}:{fieldDrafts:Map<string,ChemFieldDraft>;operator:ChemScienceOperator;source:string;onChange:(source:string)=>void;onIssue:(error:string)=>void}){
  const [issues,setIssues]=useState<Record<string,string>>({});
  const customNetwork=useRef<unknown>(undefined),exampleChoice=useRef<unknown>(undefined);
  const parsed=useMemo(()=>{try{const result=JSON.parse(source);return record(result)?result:undefined;}catch{return undefined;}},[source]);
  useEffect(()=>onIssue(Object.values(issues).find(Boolean)||''),[issues,onIssue]);
  const schema=operator.input_schema as Schema,properties=schema.properties||{};
  const guidance:Record<string,string>={compare_assay_groups:'Paired comparisons match measurements by row, so both groups must describe the same specimens in the same order. Welch comparisons treat groups as independent.',fit_calibration_curve:'Concentrations and responses must align by row. Optional weights are inverse variances. The dilution factor scales a calculated unknown back to its original concentration.',analyze_spectrum:'Supply the axis and its units explicitly. A smoothing window of 0 disables smoothing; another window must be odd and requires uniformly spaced axis values. Integration limits use the same axis units.',chemical_pca:'Each sample needs one finite value per feature in the declared column order. Components cannot exceed the smaller of sample count minus one and the number of nonconstant features.',summarize_replicates:'Use one group per assay or condition. Missing values must be written as null and require the explicit omit policy. RSD is undefined when the mean is zero.'};
  const fields=Object.entries(properties).filter(([,field])=>field.type==='array').flatMap<ImportField>(([key,field])=>{
    if(key==='reaction_ids')return [];
    if(key==='samples')return [{key,title:'Numeric sample features',kind:'matrix' as const},{key:'__sample_id',title:'Sample ID (optional)',kind:'text' as const}];
    if(key==='groups')return [{key,title:'Replicate group columns',kind:'matrix' as const}];
    if(key==='columns'&&operator.id==='chemical_pca')return [];
    if(key==='records')return [{key,title:'SMILES',kind:'records' as const},{key:'__record_id',title:'Molecular record ID (optional)',kind:'text' as const}];
    const kind:'number'|'text'|'matrix'|undefined=field.items?.type==='number'||field.items?.type==='integer'?'number':field.items?.type==='array'?'matrix':field.items?.type==='string'?'text':undefined;
    return kind?[{key,title:field.title||label(key),kind}]:[];
  });
  if(!parsed)return <p className="chem-input-error">The input JSON is not an object. Correct the advanced JSON or load the example to use the form.</p>;
  const change=(patch:Record<string,unknown>)=>onChange(JSON.stringify({...parsed,...patch},null,2));
  let visibleProperties=properties;
  const networkChoice=!!properties.network&&!!properties.example;
  if(networkChoice)visibleProperties=Object.fromEntries(Object.entries(properties).filter(([key])=>key!==(parsed.network!==undefined?'example':'network')));
  if(operator.id==='solution_calculator'){const dilution=parsed.mode==='dilution',quantity=['mass','moles','concentration'].find(key=>parsed[key]!==undefined)||'mass';visibleProperties=Object.fromEntries(Object.entries(properties).filter(([key])=>dilution?['mode','stock_concentration','target_concentration','final_volume'].includes(key):['mode','formula',quantity,'volume'].includes(key)));}
  return <FieldDraftContext.Provider value={{operator:operator.id,drafts:fieldDrafts}}><div className="chem-operator-form">{guidance[operator.id]&&<p className="chem-input-guidance">{guidance[operator.id]}</p>}{!!fields.length&&<TableImport fields={fields} onApply={change}/>}{networkChoice&&<label className="chem-schema-field"><span>Network source</span><select aria-label="Reaction network source" value={parsed.network!==undefined?'custom':'example'} onChange={event=>{const next={...parsed};if(event.target.value==='custom'){exampleChoice.current=parsed.example;delete next.example;next.network=customNetwork.current??{species:[],reactions:[]};}else{customNetwork.current=parsed.network;delete next.network;next.example=exampleChoice.current??operator.example_input.example??'reversible';}setIssues({});onChange(JSON.stringify(next,null,2));}}><option value="example">Illustrative example</option><option value="custom">Custom network</option></select><small>Use a supplied mechanism or an illustrative example. The network editor can copy a complete custom model into this study.</small></label>}{operator.id==='solution_calculator'&&parsed.mode!=='dilution'&&<label className="chem-schema-field chem-quantity-choice"><span>Known quantity</span><select aria-label="Known solution quantity" value={['mass','moles','concentration'].find(key=>parsed[key]!==undefined)||'mass'} onChange={event=>{const next={...parsed};for(const key of ['mass','moles','concentration'])delete next[key];next[event.target.value]={value:1,unit:event.target.value==='mass'?'g':event.target.value==='moles'?'mol':'mol/L'};onChange(JSON.stringify(next,null,2));}}><option value="mass">Mass</option><option value="moles">Amount of substance</option><option value="concentration">Molar concentration</option></select></label>}<div className="chem-schema-fields">{Object.entries(visibleProperties).map(([key,field])=><SchemaField key={key} name={key} path={key} schema={field} value={parsed[key]} onChange={value=>{if(operator.id==='solution_calculator'&&key==='mode'){onChange(JSON.stringify(value==='dilution'?{mode:'dilution',stock_concentration:{value:1,unit:'mol/L'},target_concentration:{value:100,unit:'mmol/L'},final_volume:{value:50,unit:'mL'}}:{mode:'amount',formula:'NaCl',mass:{value:5.844,unit:'g'},volume:{value:1,unit:'L'}},null,2));}else change({[key]:value});}} onIssue={(path,error)=>setIssues(previous=>previous[path]===error?previous:{...previous,[path]:error})}/>)}</div>{!Object.keys(properties).length&&<p className="chem-result-note">Use the complete input JSON below for this operator.</p>}</div></FieldDraftContext.Provider>;
}
