import {useEffect,useRef,useState} from "react";
import {useStore} from "zustand";
import type {StoreApi} from "zustand/vanilla";
import {ArrowDown,ArrowUp,Play,Plus,RefreshCw,Square,Trash2} from "lucide-react";
import type {ComputeStudy} from "../shared/compute-studies.ts";
import {RESEARCH_WORKFLOW_LIMITS,type WorkflowBinding,type WorkflowStep,type WorkflowStepExecution,type WorkflowValueType} from "../shared/research-workflows.ts";
import {selectedWorkflow,workflowDraft,workflowExecutionActive,workflowScopeReady,type ResearchWorkflowState} from "./research-workflow-state.ts";
import "./research-workflow.css";

type Props={store:StoreApi<ResearchWorkflowState>;workspace:string;study?:ComputeStudy;onOpenResult:(step:WorkflowStepExecution)=>Promise<void>};
const time=(at?:string)=>at?new Date(at).toLocaleString():"Not recorded";
const stepStatus=(status:WorkflowStepExecution["status"])=>status==="reused"?"Cache reused":status.replace(/^./,character=>character.toUpperCase());
const types:WorkflowValueType[]=["number","integer","string","boolean","array","object"];

export function ResearchWorkflowPanel({store,workspace,study,onOpenResult}:Props){
  const state=useStore(store),editor=selectedWorkflow(state),[newTool,setNewTool]=useState(""),[forceSteps,setForceSteps]=useState<string[]>([]),[acknowledge,setAcknowledge]=useState(false),[openingResult,setOpeningResult]=useState<string>(),[resultError,setResultError]=useState<string>(),[branchName,setBranchName]=useState(""),[sourceExecutionId,setSourceExecutionId]=useState(""),[branchExecutionId,setBranchExecutionId]=useState(""),openGeneration=useRef(0);
  useEffect(()=>{let live=true;store.getState().activate(workspace,study);void(async()=>{const current=selectedWorkflow(store.getState());if(current?.baseline)await store.getState().select(current.key);if(!live||!study||!workflowScopeReady(store.getState(),workspace,study))return;void store.getState().list();void store.getState().loadCatalog();})();return()=>{live=false;};},[store,workspace,study?.id,study?.revision]);
  useEffect(()=>()=>store.getState().suspend(),[store]);
  useEffect(()=>{if(study&&workflowScopeReady(store.getState(),workspace,study)&&!store.getState().catalog&&!store.getState().catalogBusy)void store.getState().loadCatalog();},[store,workspace,study?.id,state.selectedKey]);
  useEffect(()=>{openGeneration.current++;setNewTool("");setForceSteps([]);setAcknowledge(false);setOpeningResult(undefined);setResultError(undefined);setBranchName(editor?.baseline?`${editor.baseline.name} branch`:"");setSourceExecutionId("");setBranchExecutionId("");},[workspace,study?.id,state.selectedKey,editor?.baseline?.revision]);
  useEffect(()=>{if(editor?.baseline?.parentBranch)void store.getState().loadBranchSource();},[store,workspace,study?.id,state.selectedKey,editor?.baseline?.parentBranch?.workflowId,editor?.baseline?.parentBranch?.revision]);
  useEffect(()=>{if(state.branchSource?.executions.length&&!state.branchSource.executions.some(item=>item.id===sourceExecutionId))setSourceExecutionId(state.branchSource.executions[0].id);},[state.branchSource,sourceExecutionId]);
  useEffect(()=>{if(state.executions.length&&!state.executions.some(item=>item.id===branchExecutionId))setBranchExecutionId(state.executions[0].id);},[state.executions,branchExecutionId]);
  useEffect(()=>{setAcknowledge(false);},[state.execution?.id,state.execution?.recoveryAvailable]);
  useEffect(()=>{if(!workflowExecutionActive(state.execution))return;const timer=setInterval(()=>{void store.getState().refreshExecution();},1500);return()=>clearInterval(timer);},[store,workspace,study?.id,state.execution?.id,state.execution?.status]);
  if(!study)return null;
  if(!workflowScopeReady(state,workspace,study))return <section className="research-workflows" aria-label="Research workflows" aria-busy="true"><h2>Reusable analysis workflows</h2><p role="status">Opening workflows for this project…</p><button type="button" className="quiet-button" disabled>New workflow</button></section>;
  const disabled=!!state.busy||state.opening,history=state.historical,draft=history?workflowDraft(history):editor?.draft,active=workflowExecutionActive(state.execution),editable=!disabled&&!history;
  const selectedForceSteps=[...new Set(forceSteps)].sort(),preview=state.preview;
  const previewCurrent=!history&&!!editor?.baseline&&!!preview&&preview.workflowId===editor.baseline.id&&preview.workflowRevision===editor.baseline.revision&&preview.requestedForceSteps.join("\0")===selectedForceSteps.join("\0");
  const branchOrigin=editor?.baseline?.parentBranch,branchSource=state.branchSource;
  const comparison=state.comparison&&branchOrigin&&editor?.baseline&&state.comparison.left.workflowId===branchOrigin.workflowId&&state.comparison.right.workflowId===editor.baseline.id&&state.comparison.left.executionId===sourceExecutionId&&state.comparison.right.executionId===branchExecutionId?state.comparison:undefined;
  const updateBinding=(step:WorkflowStep,index:number,change:Partial<WorkflowBinding>)=>state.editStep(step.id,{bindings:step.bindings.map((binding,i)=>i===index?{...binding,...change}:binding)});
  const openResult=async(step:WorkflowStepExecution)=>{const generation=++openGeneration.current;setOpeningResult(step.stepId);setResultError(undefined);try{await onOpenResult(step);}catch(error){if(generation===openGeneration.current)setResultError(error instanceof Error?error.message:String(error));}finally{if(generation===openGeneration.current)setOpeningResult(undefined);}};
  return <section className="research-workflows" aria-label="Research workflows">
    <div className="research-study-heading"><div><p className="research-workflow-eyebrow">Saved analysis plans</p><h2>Reusable analysis workflows</h2></div><div className="research-study-actions"><button type="button" className="quiet-button" disabled={disabled} onClick={()=>{state.create();if(!store.getState().catalog)void store.getState().loadCatalog();}}><Plus size={15}/> New workflow</button><button type="button" className="quiet-button" disabled={state.listBusy} onClick={()=>void state.list()}><RefreshCw size={14}/> Refresh workflows</button></div></div>
    <p className="research-study-muted">Compose fixed Compute methods, bind later arguments to saved results, and retain every execution. The host checks data, parameter and runtime identities before reusing a result.</p>
    <div className="research-workflow-list" aria-label="Saved workflows">{state.workflows.map(workflow=><button type="button" key={workflow.id} className={`research-workflow-choice ${state.selectedKey===workflow.id?"is-selected":""}`} disabled={!!state.busy} onClick={()=>void state.select(workflow.id)}><strong>{workflow.name}</strong><small>{workflow.stepCount} steps · revision {workflow.revision}{workflow.parentBranch?` · branch of ${workflow.parentBranch.workflowId.slice(0,8)} r${workflow.parentBranch.revision}`:""}{state.editors.find(item=>item.key===workflow.id)?.dirty?" · local edits retained":""}</small></button>)}{state.editors.filter(item=>!item.baseline||!state.workflows.some(workflow=>workflow.id===item.key)).map(item=><button type="button" key={item.key} className={`research-workflow-choice ${state.selectedKey===item.key?"is-selected":""}`} disabled={!!state.busy} onClick={()=>void state.select(item.key)}><strong>{item.draft.name||"Untitled draft"}</strong><small>{item.baseline?`Saved revision ${item.baseline.revision}`:"Unsaved draft"} · retained in this workspace session</small></button>)}</div>
    {!state.workflows.length&&!state.editors.length&&!state.listBusy&&<p className="research-workflow-empty">No workflows have been created in this project.</p>}
    {state.error&&<p role="alert" className="analysis-error">{state.error}</p>}{state.notice&&<p role="status" className="research-study-notice">{state.notice}</p>}{state.opening&&<p role="status">Opening saved workflow…</p>}
    {editor&&draft&&<>
      {editor.baseline&&<div className="research-workflow-version"><label>Saved version<select value={history?.revision??"draft"} disabled={disabled} onChange={event=>void state.viewVersion(event.target.value==="draft"?undefined:Number(event.target.value))}><option value="draft">Current draft · baseline {editor.baseline.revision}</option>{state.versions.map(version=><option key={version.revision} value={version.revision}>Revision {version.revision} · {version.name} · {time(version.createdAt)}</option>)}</select></label><button type="button" className="quiet-button" disabled={disabled} onClick={()=>void state.reload()}>Discard draft and reload latest</button>{history&&<button type="button" className="quiet-button" disabled={disabled} onClick={()=>void state.useHistorical()}>Replace draft with revision {history.revision}</button>}</div>}
      {editor.baseline&&<div className="research-workflow-branch"><label>New branch name<input maxLength={120} value={branchName} disabled={disabled||editor.dirty||!!editor.remoteRevision||active} onChange={event=>setBranchName(event.target.value)}/></label><button type="button" className="quiet-button" disabled={disabled||!branchName.trim()||editor.dirty||!!editor.remoteRevision||active} onClick={()=>void state.forkVersion(branchName.trim())}>Fork {history?`revision ${history.revision}`:`revision ${editor.baseline.revision}`} as an independent workflow</button><p className="research-workflow-description">The fork records its immutable source revision under a new workflow identity. Existing runs stay on their source workflow; no run result, conversation, or active goal is copied.</p></div>}
      {history&&<p className="research-workflow-conflict">Viewing immutable saved revision {history.revision}. To edit or run it as a new version, explicitly replace the current draft above, then save. Your current draft is retained until that action.</p>}
      {editor.remoteRevision&&<div className="research-workflow-conflict" role="status"><p>A newer saved revision {editor.remoteRevision} exists. Your draft began at revision {editor.baseline?.revision} and remains unchanged.</p><button type="button" className="quiet-button" disabled={disabled} onClick={()=>void state.reload()}>Discard draft and reload latest revision</button></div>}
      <form className="research-workflow-editor" aria-label="Workflow editor" onSubmit={event=>{event.preventDefault();void state.save();}}><fieldset disabled={!editable}><legend>Workflow definition</legend><div className="research-workflow-fields"><label>Workflow name<input required maxLength={120} value={draft.name} onChange={event=>state.edit({name:event.target.value})}/></label><label>Description<textarea maxLength={8000} rows={2} value={draft.description} onChange={event=>state.edit({description:event.target.value})}/></label></div>
        <p className="research-workflow-dag-note">Cards are shown in your chosen order. Dependency bindings determine execution order; moving a card does not create, remove or change an edge. Each binding reads an explicit JSON pointer from that upstream step’s saved result.</p>
        {draft.steps.map((step,index)=>{const tool=state.toolDetails[step.tool]??state.catalog?.tools.find(item=>item.id===step.tool),raw=history?JSON.stringify(step.arguments,null,2):editor.argumentsText[step.id]??JSON.stringify(step.arguments,null,2),known=state.catalog?.tools.some(item=>item.id===step.tool);return <fieldset className="research-workflow-step" key={step.id}><legend>Step {index+1} · {step.id}</legend><div className="research-study-actions"><button type="button" className="quiet-button" aria-label={`Move workflow step ${index+1} earlier`} disabled={index===0} onClick={()=>state.moveStep(step.id,-1)}><ArrowUp size={14}/></button><button type="button" className="quiet-button" aria-label={`Move workflow step ${index+1} later`} disabled={index===draft.steps.length-1} onClick={()=>state.moveStep(step.id,1)}><ArrowDown size={14}/></button><button type="button" className="quiet-button" onClick={()=>state.removeStep(step.id)}><Trash2 size={14}/> Remove step {index+1}</button></div><div className="research-workflow-fields"><label>Step title<input required maxLength={120} value={step.title} onChange={event=>state.editStep(step.id,{title:event.target.value})}/></label><label>Fixed Compute method<select value={step.tool} onChange={event=>{state.editStep(step.id,{tool:event.target.value});void state.loadTool(event.target.value);}}>{!known&&<option value={step.tool}>{step.tool} · unavailable in current catalog</option>}{state.catalog?.tools.map(item=><option key={item.id} value={item.id}>{item.title} · {item.id}</option>)}</select></label></div><p className="research-workflow-description">{tool?.description??"Current method metadata is unavailable. Saved method IDs remain visible."}{tool&&!tool.available?` Missing dependencies: ${tool.missing_dependencies.join(", ")||"not reported"}.`:""}</p>
          <label>Literal arguments · JSON object<textarea className="research-workflow-arguments" spellCheck={false} rows={7} value={raw} onChange={event=>state.editArguments(step.id,event.target.value)}/></label><p className="research-workflow-description">Only data values are accepted. Remove a bound argument from this object; its value comes from the binding below. Example values require review before use with your data. The complete workflow is limited to 2 MiB.</p>
          {tool?.input_schema?<details><summary>Authoritative method parameter schema</summary><pre className="analysis-json">{JSON.stringify(tool.input_schema,null,2)}</pre></details>:<button type="button" className="quiet-button" disabled={!!state.toolBusy} onClick={()=>void state.loadTool(step.tool)}>{state.toolBusy===step.tool?"Loading schema…":"Load method schema"}</button>}
          <h3>Result bindings</h3>{step.bindings.length===0&&<p className="research-workflow-description">No upstream arguments are bound for this step.</p>}{step.bindings.map((binding,bindingIndex)=>{const upstream=draft.steps.find(item=>item.id===binding.fromStep);return <div className="research-workflow-binding" key={bindingIndex}><label>Target argument<input aria-label={`Step ${step.id} binding ${bindingIndex+1} target argument`} maxLength={100} value={binding.argument} onChange={event=>updateBinding(step,bindingIndex,{argument:event.target.value})}/></label><label>Upstream step<select aria-label={`Step ${step.id} binding ${bindingIndex+1} upstream step`} value={binding.fromStep} onChange={event=>updateBinding(step,bindingIndex,{fromStep:event.target.value})}><option value="">Choose a step</option>{binding.fromStep&&!upstream&&<option value={binding.fromStep}>{binding.fromStep} · missing step</option>}{draft.steps.filter(item=>item.id!==step.id).map(item=><option key={item.id} value={item.id}>{item.id} · {item.title}</option>)}</select></label><label>Saved result JSON pointer<input aria-label={`Step ${step.id} binding ${bindingIndex+1} result pointer`} maxLength={512} value={binding.pointer} placeholder="/mean · empty selects the result root" onChange={event=>updateBinding(step,bindingIndex,{pointer:event.target.value})}/></label><label>Declared value type<select aria-label={`Step ${step.id} binding ${bindingIndex+1} value type`} value={binding.type} onChange={event=>updateBinding(step,bindingIndex,{type:event.target.value as WorkflowValueType})}>{types.map(type=><option key={type} value={type}>{type}</option>)}</select></label><div className="research-workflow-binding-actions"><button type="button" className="quiet-button" onClick={()=>state.editStep(step.id,{bindings:step.bindings.filter((_,i)=>i!==bindingIndex)})}>Remove binding {bindingIndex+1}</button></div></div>;})}<button type="button" className="quiet-button" disabled={step.bindings.length>=40||draft.steps.length<2} onClick={()=>state.editStep(step.id,{bindings:[...step.bindings,{argument:"",fromStep:"",pointer:"",type:"number"}]})}><Plus size={14}/> Add result binding</button>
        </fieldset>;})}
        <div className="research-workflow-add"><label>Add a method step<select value={newTool} disabled={state.catalogBusy||draft.steps.length>=16} onChange={event=>setNewTool(event.target.value)}><option value="">Choose from the local catalog</option>{state.catalog?.tools.map(tool=><option key={tool.id} value={tool.id}>{tool.title} · {tool.id}</option>)}</select></label><button type="button" className="quiet-button" disabled={!newTool||!!state.toolBusy||draft.steps.length>=16} onClick={()=>void state.addStep(newTool)}><Plus size={15}/> Add step ({draft.steps.length}/{RESEARCH_WORKFLOW_LIMITS.steps})</button></div>
        {state.catalogBusy&&<p role="status">Loading the authoritative method catalog…</p>}<button type="button" className="quiet-button" disabled={state.catalogBusy} onClick={()=>void state.loadCatalog()}>Refresh method catalog</button>
        <div className="research-study-actions"><button type="button" className="quiet-button" disabled={!draft.steps.length} onClick={()=>void state.validate()}>Validate draft</button><button type="submit" className="quiet-button" disabled={!draft.steps.length||!!editor.remoteRevision}>Save workflow revision</button><span className="research-study-muted">{editor.dirty?"Unsaved edits retained in this session":`Saved revision ${editor.baseline?.revision}`}</span></div>
      </fieldset></form>
      {state.validation&&<section aria-label="Workflow validation"><h3>{state.validation.ok?"Definition validated":"Definition needs attention"}</h3>{state.validation.order.length>0&&<p className="research-workflow-description">Host execution order: {state.validation.order.join(" → ")}</p>}<ul>{state.validation.diagnostics.map((diagnostic,index)=><li key={index}><code>{diagnostic.code}</code>{diagnostic.stepId?` · ${diagnostic.stepId}`:""}{diagnostic.argument?` · ${diagnostic.argument}`:""}: {diagnostic.message}</li>)}</ul><p className="research-study-muted">Validation checks the definition. It does not mean the methods have executed or produced scientific evidence.</p></section>}
      {editor.baseline&&<section className="research-workflow-run-controls" aria-label="Workflow execution controls"><h3>Execute saved revision {editor.baseline.revision}</h3><p className="research-workflow-description">Preview which steps can reuse verified results, which will recompute, and which depend on results not available until execution. Selecting a step forces it and every descendant that depends on it.</p><div className="research-workflow-force">{editor.baseline.steps.map(step=><label key={step.id}><input type="checkbox" checked={forceSteps.includes(step.id)} disabled={disabled||editor.dirty||!!editor.remoteRevision||!!history||active} onChange={event=>setForceSteps(previous=>event.target.checked?[...previous,step.id]:previous.filter(id=>id!==step.id))}/>{step.id} · {step.title}</label>)}</div><div className="research-study-actions"><button type="button" className="quiet-button" disabled={disabled||editor.dirty||!!editor.remoteRevision||!!history||active} onClick={()=>void state.previewPlan(forceSteps)}><RefreshCw size={14}/>{state.busy==="preview"?"Building run-impact preview…":"Preview rerun impact"}</button><button type="button" className="quiet-button" disabled={disabled||!previewCurrent||!preview?.canStart||editor.dirty||!!editor.remoteRevision||!!history||active} onClick={()=>void state.start(forceSteps)}><Play size={15}/> {forceSteps.length?"Run with selected steps forced":"Run saved workflow"}</button></div>{editor.dirty&&<p className="research-study-muted">Save the current draft before previewing or executing it.</p>}
        {previewCurrent&&preview&&<section className="research-workflow-preview" aria-label="Workflow run-impact preview"><h4>Run-impact preview · revision {preview.workflowRevision}</h4><p className="research-workflow-description">Forced closure: {preview.forcedClosure.length?preview.forcedClosure.join(", "):"none"}. Resource estimate: unknown. {preview.resourceEstimate.reason}</p><ol className="research-workflow-node-results">{preview.steps.map(step=><li className="research-workflow-node-result" key={step.stepId}><div className="research-workflow-node-title"><strong>{step.stepId} · {step.title}</strong><span className="research-workflow-status">{step.state}</span></div><p><code>{step.tool}</code>{step.dependencies.length?` · depends on ${step.dependencies.join(", ")}`:" · no upstream result bindings"}</p><p>{step.reason}</p><p className="research-workflow-description">Changed fingerprint inputs: {step.changedMaterials.length?step.changedMaterials.join(", "):"none detected"}</p>{step.previousRunId&&<p>Comparison receipt <code>{step.previousRunId}</code></p>}</li>)}</ol>{preview.comparisonWarnings.length>0&&<details><summary>Prior execution records excluded from comparison ({preview.comparisonWarnings.length})</summary><ul>{preview.comparisonWarnings.map((warning,index)=><li key={index}>{warning}</li>)}</ul></details>}<p className="research-study-muted">Plan SHA-256 <code>{preview.planSha256}</code>. The host recomputes this plan at submit time and rejects source or cache drift.</p></section>}
      </section>}
    </>}
    {state.executions.length>0&&<section aria-label="Workflow execution history"><h3>Execution history</h3><div className="research-workflow-execution-list">{state.executions.map(execution=><button type="button" key={execution.id} className={`research-workflow-choice ${state.execution?.id===execution.id?"is-selected":""}`} disabled={!!state.busy} onClick={()=>void state.selectExecution(execution.id)}><strong>Revision {execution.workflowRevision} · {execution.status}</strong><small>{time(execution.createdAt)}</small><small>{execution.id}</small></button>)}</div></section>}
    {branchOrigin&&editor?.baseline&&<section className="research-workflow-branch-compare" aria-label="Research branch comparison"><h3>Compare source and branch executions</h3><p className="research-workflow-description">Source: workflow <code>{branchOrigin.workflowId}</code>, revision {branchOrigin.revision}, definition SHA-256 <code>{branchOrigin.definitionSha256}</code>. This comparison checks saved software inputs and result bytes; it does not establish scientific equivalence or causality.</p>{state.branchSourceBusy&&<p role="status">Loading immutable source execution history…</p>}{branchSource&&<div className="research-workflow-compare-controls"><label>Source execution<select value={sourceExecutionId} disabled={state.comparisonBusy||!branchSource.executions.length} onChange={event=>setSourceExecutionId(event.target.value)}><option value="">Choose a source execution</option>{branchSource.executions.map(item=><option key={item.id} value={item.id}>Revision {item.workflowRevision} · {item.status} · {time(item.createdAt)}</option>)}</select></label><label>Branch execution<select value={branchExecutionId} disabled={state.comparisonBusy||!state.executions.length} onChange={event=>setBranchExecutionId(event.target.value)}><option value="">Choose a branch execution</option>{state.executions.map(item=><option key={item.id} value={item.id}>Revision {item.workflowRevision} · {item.status} · {time(item.createdAt)}</option>)}</select></label><button type="button" className="quiet-button" disabled={state.comparisonBusy||!sourceExecutionId||!branchExecutionId} onClick={()=>void state.compareExecutions(branchOrigin.workflowId,sourceExecutionId,editor.baseline!.id,branchExecutionId)}>{state.comparisonBusy?"Comparing saved runs…":"Compare selected runs"}</button></div>}{comparison&&<div className="research-workflow-preview"><h4>Saved execution comparison</h4><ul className="research-workflow-node-results">{comparison.steps.map(step=><li className="research-workflow-node-result" key={step.stepId}><div className="research-workflow-node-title"><strong>{step.stepId}</strong><span className="research-workflow-status">{step.state}</span></div><p>{step.leftTool??"No source method"} → {step.rightTool??"No branch method"}</p>{step.changedArgumentNames.length>0&&<p>Changed top-level arguments: {step.changedArgumentNames.join(", ")}</p>}<p>Changed fingerprint materials: {step.changedMaterials.length?step.changedMaterials.join(", "):"none reported"} · result bytes: {step.resultBytes} · source freshness: {step.sourceFreshness}</p>{step.leftRunId&&<p>Source run <code>{step.leftRunId}</code></p>}{step.rightRunId&&<p>Branch run <code>{step.rightRunId}</code></p>}</li>)}</ul>{comparison.limits.map((limit,index)=><p className="research-study-muted" key={index}>{limit}</p>)}<p className="research-study-muted">Comparison SHA-256 <code>{comparison.comparisonSha256}</code></p></div>}</section>}
    {state.execution&&<section className="research-workflow-execution" aria-label="Workflow execution"><div className="research-study-heading"><h3>{state.execution.name} · revision {state.execution.workflowRevision}</h3><span className="research-workflow-status">{state.execution.status}</span></div><div className="research-workflow-execution-meta"><code>{state.execution.id}</code><span>Updated {time(state.execution.updatedAt)}</span>{state.execution.finishedAt&&<span>Finished {time(state.execution.finishedAt)}</span>}</div><div className="research-study-actions"><button type="button" className="quiet-button" disabled={state.executionBusy||!!state.busy} onClick={()=>void state.refreshExecution()}><RefreshCw size={14}/> Refresh execution</button>{active&&<button type="button" className="quiet-button" disabled={!!state.busy||state.execution.cancelRequested} onClick={()=>void state.cancel()}><Square size={14}/>{state.execution.cancelRequested?"Cancellation requested":"Cancel execution"}</button>}</div>{active&&<p className="research-study-muted">Status is refreshed from the host for this selected execution. Waiting and completion are reported by the executing service.</p>}{state.execution.recoveryReason&&<p className="research-workflow-description">{state.execution.recoveryReason}</p>}{state.execution.recoveryAvailable&&<div className="research-workflow-conflict"><label className="research-study-checkbox"><input type="checkbox" checked={acknowledge} onChange={event=>setAcknowledge(event.target.checked)}/> I have reviewed the previous attempt and want to recover it.</label><p>Recovery retains earlier attempts. Review any uncertain effects recorded for stopped steps before retrying.</p><button type="button" className="quiet-button" disabled={!acknowledge||!!state.busy} onClick={()=>void state.recover(acknowledge)}>Recover stopped execution</button></div>}{state.execution.parentExecutionId&&<p className="research-workflow-description">Continues execution <code>{state.execution.parentExecutionId}</code>.</p>}
      <ol className="research-workflow-node-results">{state.execution.steps.map(step=><li className="research-workflow-node-result" key={step.stepId}><div className="research-workflow-node-title"><strong>{step.stepId} · {step.title}</strong><span className="research-workflow-status">{stepStatus(step.status)}</span></div><p><code>{step.tool}</code></p>{step.cacheReason&&<p>{step.cacheReason}</p>}{step.error&&<p role="alert"><code>{step.error.code}</code>: {step.error.message}</p>}{!!step.blockedBy?.length&&<p>Blocked by: {step.blockedBy.join(", ")}</p>}{step.runId&&<p>Saved run <code>{step.runId}</code></p>}{step.reusedFromExecutionId&&<p>Reused from execution <code>{step.reusedFromExecutionId}</code></p>}{step.runId&&step.binding&&["succeeded","reused"].includes(step.status)&&<button type="button" className="quiet-button" disabled={!!openingResult} onClick={()=>void openResult(step)}>{openingResult===step.stepId?"Verifying saved result…":"Open result"}</button>}<details><summary>Recorded step identity & inputs</summary><pre>{JSON.stringify({startedAt:step.startedAt,finishedAt:step.finishedAt,request:step.request,binding:step.binding,cacheKey:step.cacheKey,fingerprint:step.fingerprint},null,2)}</pre></details></li>)}</ol>{resultError&&<p role="alert" className="analysis-error">{resultError}</p>}
    </section>}
  </section>;
}
