import {useEffect,useMemo,useRef,useState} from "react";
import type {ComputeRun,ComputeTool} from "../shared/compute.ts";
import {ComputeField} from "./ComputeField.tsx";
import {rnaSeqDisplayValue as value,rnaSeqGenePage,rnaSeqGenePlot,validateRnaSeqStudy,type RnaSeqDifferentialRow,type RnaSeqPlotPoint,type RnaSeqStudy} from "./rnaseq-study.ts";
import "./rnaseq-study.css";

const groups=[
  {title:"Raw counts & sample identities",fields:["counts_path","samples_path"],help:"Counts CSV: unique gene IDs in the first column, then one named sample per column. Supply raw, nonnegative integer counts. Sample CSV must identify every sample and its condition; batch or subject is required when selected below. TPM, CPM and log-transformed counts are not raw counts."},
  {title:"Design & explicit comparison",fields:["analysis_mode","design","reference_level","comparison_level"],help:"Validate checks the supplied files and design without fitting DESeq2. Fit runs the local DESeq2 engine. The reported contrast is comparison / reference; a positive log2 fold change means higher expression in the comparison level. Batch and subject designs use the corresponding supplied metadata; no arbitrary formula is executed."},
  {title:"Filtering & fitted analysis",fields:["min_count","min_samples","alpha","pca_top_genes","size_factor_type","gene_sets_path"],help:"Retain a gene only when at least the specified number of samples meet the minimum count. These are explicit analysis choices, not an automatic assessment of study quality. Optional local gene sets are tested against genes with an available adjusted p-value in this contrast."},
];

export function RnaSeqStudyFields({tool,fields,busy,error,onChange}:{tool:ComputeTool;fields:Record<string,string>;busy:boolean;error?:{field:string;message:string};onChange:(name:string,value:string)=>void}) {
  const properties=Object.keys(tool.input_schema?.properties??{}),known=new Set(groups.flatMap(group=>group.fields));
  const render=(name:string)=><ComputeField key={`${tool.id}-${name}`} tool={tool} name={name} value={fields[name]??""} busy={busy} error={error?.field===name?error.message:undefined} onChange={value=>onChange(name,value)}/>;
  return <div className="rnaseq-input-groups">{groups.map(group=><fieldset key={group.title}><legend>{group.title}</legend><p>{group.help}</p>{group.fields.filter(name=>properties.includes(name)).map(render)}</fieldset>)}{properties.filter(name=>!known.has(name)).map(render)}</div>;
}

export function RnaSeqStudyResults({result,requested,receipt}:{result:unknown;requested:Record<string,unknown>;receipt:ComputeRun}) {
  const study=useMemo(()=>validateRnaSeqStudy(result,requested,receipt),[result,requested,receipt]);
  const fitted=study.analysis.status==="complete",de=study.differential_expression;
  return <article className="rnaseq-study" aria-label="RNA-seq study results">
    <header><p className="rnaseq-eyebrow">SAVED RNA-SEQ STUDY</p><h2>{fitted?"Differential expression, with its evidence.":"Input validation complete."}</h2><p>{fitted?"Review the fitted contrast, sample diagnostics and retained gene results. These outputs do not establish biological validity.":"Counts, sample identities, filtering and the design matrix were checked. No DESeq2 model, PCA or differential-expression test was fitted."}</p></header>
    <div className="rnaseq-summary"><Summary label="Samples" value={study.qc.sample_count}/><Summary label="Input genes" value={study.qc.gene_count}/><Summary label="Retained after filtering" value={study.filter.kept_genes}/><Summary label="Excluded by filtering" value={study.filter.excluded_genes.length}/></div>
    <section aria-label="RNA-seq design and contrast"><h3>Design & contrast</h3><dl className="rnaseq-facts"><dt>Recorded formula</dt><dd><code>{study.design.formula}</code></dd><dt>Comparison / reference</dt><dd>{study.design.contrast.numerator} / {study.design.contrast.denominator}</dd><dt>Design rank / columns</dt><dd>{study.design.rank} / {study.design.columns.length}</dd><dt>Residual degrees of freedom</dt><dd>{study.design.residual_df}</dd><dt>Count filtering</dt><dd>At least {study.filter.min_count} counts in at least {study.filter.min_samples} samples</dd></dl><p className="rnaseq-note">A positive log2 fold change means higher expression in {study.design.contrast.numerator} relative to {study.design.contrast.denominator}. Statistical association does not establish a causal effect.</p><details><summary>Recorded design columns & factor levels</summary><pre>{JSON.stringify({columns:study.design.columns,factor_levels:study.design.factor_levels},null,2)}</pre></details></section>
    <section aria-label="RNA-seq sample quality control"><h3>Sample quality control</h3><p>{study.qc.metadata_reordered?"The sample metadata was explicitly aligned to count-column order. The table retains that analyzed order.":"Samples are shown in their analyzed count-column order."} Library sizes and detected genes below describe the supplied raw matrix.</p><div className="rnaseq-table-scroll" role="region" tabIndex={0} aria-label="Sample QC table"><table><thead><tr><th>Sample</th><th>Condition</th><th>Batch</th><th>Subject</th><th>Library size</th><th>Detected genes</th><th>Zero fraction</th><th>Size factor</th></tr></thead><tbody>{study.qc.samples.map(row=><tr key={row.sample}><th>{row.sample}</th><td>{row.condition}</td><td>{row.batch??"Not supplied"}</td><td>{row.subject??"Not supplied"}</td><td>{row.library_size.toLocaleString()}</td><td>{row.detected_genes.toLocaleString()}</td><td>{value(row.zero_fraction)}</td><td>{value(row.size_factor)}</td></tr>)}</tbody></table></div><p className="rnaseq-note">{study.qc.all_zero_genes.length.toLocaleString()} genes have zero counts in every supplied sample. Full gene identities and exclusion lists remain in the saved result JSON.</p></section>
    {study.pca?<PcaPanel study={study}/>:<section className="rnaseq-unavailable"><h3>PCA</h3><p>Not fitted in validation mode. No sample coordinates or explained variance are inferred.</p></section>}
    {de?<><section aria-label="Differential-expression summary"><h3>Differential expression</h3><div className="rnaseq-summary"><Summary label="Modeled genes" value={de.summary.modeled}/><Summary label="Adjusted p available" value={de.summary.padj_available}/><Summary label={`Higher · adjusted p < ${de.alpha}`} value={de.summary.significant_up}/><Summary label={`Lower · adjusted p < ${de.alpha}`} value={de.summary.significant_down}/></div><p className="rnaseq-note">{de.summary.modeled-de.summary.pvalue_available} p-values and {de.summary.modeled-de.summary.padj_available} adjusted p-values are unavailable. Null values remain unavailable. {de.summary.significant_zero} genes meet the adjusted p threshold with exactly zero recorded fold change. The threshold classifies recorded statistical results; it does not certify biological relevance.</p></section><div className="rnaseq-chart-grid"><GeneChart rows={de.rows} alpha={de.alpha} kind="volcano"/><GeneChart rows={de.rows} alpha={de.alpha} kind="ma"/></div><DifferentialTable key={`${receipt.run_id??"preview"}-${receipt.result_sha256??"recorded"}`} rows={de.rows}/></>:<section className="rnaseq-unavailable"><h3>Differential expression</h3><p>Not fitted in validation mode. No p-values, fold changes or significant-gene counts were calculated.</p></section>}
    <EnrichmentPanel enrichment={study.enrichment}/>
    {!!study.warnings.length&&<section className="rnaseq-notices" aria-label="RNA-seq warnings"><h3>Review notes</h3><ul>{study.warnings.map((warning,index)=><li key={index}>{warning}</li>)}</ul></section>}
    <details className="rnaseq-sources"><summary>Sources & saved analysis identity</summary><p>These identifiers describe the recorded local bytes. Use the research project’s source checks to inspect whether the original files have changed.</p><dl>{Object.entries(study.sources).map(([name,file])=><div key={name}><dt>{name}</dt><dd><code>{file.path}</code><br/>{file.bytes.toLocaleString()} bytes<br/><code>{file.sha256}</code></dd></div>)}</dl><pre>{JSON.stringify(study.analysis,null,2)}</pre></details>
    <details className="rnaseq-notices" open><summary>Scope & limitations</summary><ul>{study.limitations.map((limitation,index)=><li key={index}>{limitation}</li>)}</ul><p>The JSON download contains the full saved result. Charts use only recorded finite values; exclusions are shown below each chart.</p></details>
  </article>;
}

function Summary({label,value:amount}:{label:string;value:number}){return <div><span>{label}</span><strong>{amount.toLocaleString()}</strong></div>;}
function PcaPanel({study}:{study:RnaSeqStudy}){const pca=study.pca!,points=useMemo(()=>pca.samples.map(row=>({id:row.sample,x:row.pc1,y:row.pc2,group:row.condition})),[pca]);return <section aria-label="RNA-seq PCA"><h3>Sample PCA</h3><p>{pca.transform}; centered, without variance scaling. {pca.genes.length.toLocaleString()} recorded genes were used.</p><ScatterPlot points={points} label="PCA sample coordinates" xLabel={`PC1 · ${value(pca.variance_fraction[0]*100)}% variance`} yLabel={`PC2 · ${value(pca.variance_fraction[1]*100)}% variance`}/><details><summary>Exact sample coordinates</summary><div className="rnaseq-table-scroll"><table><thead><tr><th>Sample</th><th>Condition</th><th>PC1</th><th>PC2</th></tr></thead><tbody>{pca.samples.map(row=><tr key={row.sample}><th>{row.sample}</th><td>{row.condition}</td><td>{String(row.pc1)}</td><td>{String(row.pc2)}</td></tr>)}</tbody></table></div></details></section>;}
function GeneChart({rows,alpha,kind}:{rows:RnaSeqDifferentialRow[];alpha:number;kind:"volcano"|"ma"}){const plot=useMemo(()=>rnaSeqGenePlot(rows,kind,alpha),[rows,kind,alpha]);return <section aria-label={kind==="volcano"?"RNA-seq volcano plot":"RNA-seq MA plot"}><h3>{kind==="volcano"?"Volcano plot":"MA plot"}</h3><ScatterPlot points={plot.points} label={kind==="volcano"?"Recorded fold change and adjusted p-values":"Recorded base mean and fold change"} xLabel={kind==="volcano"?"log2 fold change":"log10 base mean"} yLabel={kind==="volcano"?"−log10 adjusted p":"log2 fold change"}/><p className="rnaseq-note">Plotted {plot.points.length.toLocaleString()} / {plot.total.toLocaleString()} modeled genes. {plot.excluded.missing.toLocaleString()} lack a required value. {kind==="volcano"?`${plot.excluded.zeroAdjustedP.toLocaleString()} have adjusted p = 0 and no finite logarithmic coordinate; they remain in the table. No numerical floor was substituted.`:`${plot.excluded.zeroBaseMean.toLocaleString()} have base mean = 0 and no finite logarithmic coordinate; they remain in the table.`}</p></section>;}

const palette=["#427a9b","#a46b91","#699078","#bc874e","#7e78ad","#729794"];
function ScatterPlot({points,label,xLabel,yLabel}:{points:RnaSeqPlotPoint[];label:string;xLabel:string;yLabel:string}){
  const canvas=useRef<HTMLCanvasElement>(null),[nearest,setNearest]=useState<RnaSeqPlotPoint>(),layout=useRef<{left:number;right:number;top:number;bottom:number;minX:number;maxX:number;minY:number;maxY:number}|undefined>(undefined);
  const categories=useMemo(()=>[...new Set(points.map(point=>point.group))],[points]);
  useEffect(()=>{setNearest(undefined);const element=canvas.current;if(!element)return;const draw=()=>{const width=Math.max(240,element.clientWidth),height=300,dpr=window.devicePixelRatio||1;element.width=Math.round(width*dpr);element.height=Math.round(height*dpr);const context=element.getContext("2d");if(!context)return;context.scale(dpr,dpr);const style=getComputedStyle(element),ink=style.color,line=style.getPropertyValue("--line").trim()||"#aaa",left=64,right=width-20,top=22,bottom=242;let minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity;for(const point of points){minX=Math.min(minX,point.x);maxX=Math.max(maxX,point.x);minY=Math.min(minY,point.y);maxY=Math.max(maxY,point.y);}if(!points.length){minX=minY=0;maxX=maxY=1;}const padX=(maxX-minX||Math.max(Math.abs(minX),1))*.06,padY=(maxY-minY||Math.max(Math.abs(minY),1))*.06;minX-=padX;maxX+=padX;minY-=padY;maxY+=padY;layout.current={left,right,top,bottom,minX,maxX,minY,maxY};context.font='10px "Proto Mono", monospace';context.strokeStyle=line;context.lineWidth=.5;context.fillStyle=ink;for(let i=0;i<5;i++){const fraction=i/4,x=left+(right-left)*fraction,y=bottom-(bottom-top)*fraction;context.beginPath();context.moveTo(left,y);context.lineTo(right,y);context.stroke();context.textAlign="right";context.fillText(Number((minY+(maxY-minY)*fraction).toPrecision(3)).toString(),left-7,y+3);context.textAlign="center";context.fillText(Number((minX+(maxX-minX)*fraction).toPrecision(3)).toString(),x,bottom+17);}context.globalAlpha=points.length>1000?.45:.85;for(const point of points){context.fillStyle=palette[categories.indexOf(point.group)%palette.length];context.beginPath();context.arc(left+(point.x-minX)/(maxX-minX)*(right-left),bottom-(point.y-minY)/(maxY-minY)*(bottom-top),points.length>1000?1.5:3.5,0,Math.PI*2);context.fill();}context.globalAlpha=1;context.fillStyle=ink;context.font='11px "Proto Sans Text", sans-serif';context.textAlign="center";context.fillText(xLabel,(left+right)/2,286);context.save();context.translate(14,(top+bottom)/2);context.rotate(-Math.PI/2);context.fillText(yLabel,0,0);context.restore();};draw();const resize=new ResizeObserver(draw);resize.observe(element);const theme=new MutationObserver(draw);theme.observe(document.documentElement,{attributes:true,attributeFilter:["data-theme"]});return()=>{resize.disconnect();theme.disconnect();};},[points,categories,xLabel,yLabel]);
  return <figure className="rnaseq-scatter"><canvas ref={canvas} role="img" aria-label={`${label}. ${points.length.toLocaleString()} recorded points. Exact values are available in the tables or saved JSON.`} onPointerMove={event=>{const frame=layout.current;if(!frame)return;const rect=event.currentTarget.getBoundingClientRect(),x=event.clientX-rect.left,y=event.clientY-rect.top;let best:RnaSeqPlotPoint|undefined,dist=100;for(const point of points){const px=frame.left+(point.x-frame.minX)/(frame.maxX-frame.minX)*(frame.right-frame.left),py=frame.bottom-(point.y-frame.minY)/(frame.maxY-frame.minY)*(frame.bottom-frame.top),d=(x-px)**2+(y-py)**2;if(d<dist){dist=d;best=point;}}setNearest(best);}} onPointerLeave={()=>setNearest(undefined)}/>{!points.length&&<p>No finite points are available for this chart.</p>}<figcaption><div className="rnaseq-legend">{categories.map((category,index)=><span key={category}><i style={{backgroundColor:palette[index%palette.length]}}/>{category}</span>)}</div><p className="rnaseq-point-readout">{nearest?`${nearest.id} · ${nearest.group} · x ${String(nearest.x)} · y ${String(nearest.y)}`:"Move over a point to inspect its identity. Tables provide keyboard-accessible values."}</p></figcaption></figure>;
}

function DifferentialTable({rows}:{rows:RnaSeqDifferentialRow[]}){const [query,setQuery]=useState(""),[page,setPage]=useState(0),selection=useMemo(()=>rnaSeqGenePage(rows,query,page),[rows,query,page]);return <section aria-label="Differential-expression gene results"><h3>Gene results</h3><div className="rnaseq-table-toolbar"><label>Find gene ID<input value={query} onChange={event=>{setQuery(event.target.value);setPage(0);}} placeholder="Search the retained gene identifiers"/></label><span role="status">{selection.matching.toLocaleString()} / {selection.total.toLocaleString()} genes match</span></div><p className="rnaseq-note">Original result order; 50 rows per page. Values are rounded for display. Unavailable values remain explicit, and complete precision remains in the saved JSON.</p><div className="rnaseq-table-scroll" role="region" aria-label="Differential-expression table" tabIndex={0}><table><thead><tr><th>Gene ID</th><th>Base mean</th><th>log2 fold change</th><th>Fold-change SE</th><th>Statistic</th><th>p-value</th><th>Adjusted p</th><th>Status</th></tr></thead><tbody>{selection.rows.map(row=><tr key={row.gene_id}><th>{row.gene_id}</th><td>{value(row.baseMean)}</td><td>{value(row.log2FoldChange)}</td><td>{value(row.lfcSE)}</td><td>{value(row.stat)}</td><td>{value(row.pvalue)}</td><td>{value(row.padj)}</td><td>{row.status}</td></tr>)}</tbody></table></div>{!selection.rows.length&&<p>No gene IDs match this search.</p>}<div className="rnaseq-pagination"><button type="button" className="quiet-button" disabled={selection.page===0} onClick={()=>setPage(selection.page-1)}>Previous genes</button><span>Page {selection.page+1} / {selection.totalPages}</span><button type="button" className="quiet-button" disabled={selection.page+1>=selection.totalPages} onClick={()=>setPage(selection.page+1)}>Next genes</button></div></section>;}
function EnrichmentPanel({enrichment}:{enrichment:RnaSeqStudy["enrichment"]}){return <section aria-label="RNA-seq gene-set enrichment"><h3>Gene-set over-representation</h3><p>Status: <strong>{enrichment.status.replaceAll("-"," ")}</strong>{enrichment.reason?` · ${enrichment.reason}`:""}</p><p className="rnaseq-note">{enrichment.method}. Background: {enrichment.background_rule}. Selection: {enrichment.selection_rule}. Both expression directions are combined; this does not determine pathway activation.</p>{enrichment.gene_set_source&&<p>Namespace: {enrichment.gene_set_source.namespace} · Source: {enrichment.gene_set_source.source}</p>}{enrichment.background_genes&&<p>{enrichment.selected_genes?.length??0} selected genes / {enrichment.background_genes.length} background genes; {enrichment.tested_gene_sets??0} tested sets.</p>}{enrichment.rows&&<div className="rnaseq-table-scroll" role="region" aria-label="Gene-set results table" tabIndex={0}><table><thead><tr><th>Gene set</th><th>Set in background</th><th>Members outside background</th><th>Overlap</th><th>Expected overlap</th><th>Fold enrichment</th><th>p-value</th><th>Adjusted p</th></tr></thead><tbody>{enrichment.rows.map(row=><tr key={row.name}><th>{row.name}</th><td>{row.set_size_in_background}</td><td>{row.excluded_members_outside_background}</td><td><details><summary>{row.overlap_count} genes</summary>{row.overlap_genes.join(", ")||"No overlap"}</details></td><td>{value(row.expected_overlap)}</td><td>{value(row.fold_enrichment)}</td><td>{value(row.p_value)}</td><td>{value(row.adjusted_p_value)}</td></tr>)}</tbody></table></div>}</section>;}
