"""Explicit quantity exemptions; new tools must be deliberately classified."""
QUANTITY_EXEMPT = {
    'adjust_pvalues': 'Inference, intervals and effect sizes require reviewed per-field entity and unit mappings.',
    'align_sequences': 'Sequence coordinates and design scores require reviewed quantity entity and coordinate-to-unit mappings.',
    'analyze_abr_waveform_p1_metrics': 'Assay signals, calibrations and derived values require per-field quantity bindings.',
    'analyze_accelerated_stability_of_pharmaceutical_formulations': 'Assay signals, calibrations and derived values require per-field quantity bindings.',
    'analyze_aortic_diameter_and_geometry': 'Morphology measurements require pixel calibration and region entity bindings.',
    'analyze_arsenic_speciation_hplc_icpms': 'Assay signals, calibrations and derived values require per-field quantity bindings.',
    'analyze_atp_luminescence_assay': 'Assay signals, calibrations and derived values require per-field quantity bindings.',
    'analyze_bacterial_growth_curve': 'Assay signals, calibrations and derived values require per-field quantity bindings.',
    'analyze_bacterial_growth_rate': 'Assay signals, calibrations and derived values require per-field quantity bindings.',
    'analyze_barcode_sequencing_data': 'Assay signals, calibrations and derived values require per-field quantity bindings.',
    'analyze_bifurcation_diagram': 'State and parameter units require per-model quantity profiles.',
    'analyze_bone_microct_morphometry': 'Morphology measurements require pixel calibration and region entity bindings.',
    'analyze_calcium_imaging_data': 'Morphology measurements require pixel calibration and region entity bindings.',
    'analyze_cas9_mutation_outcomes': 'Population/network scores and genomic coordinates require entity/unit profiles.',
    'analyze_cell_migration_metrics': 'Morphology measurements require pixel calibration and region entity bindings.',
    'analyze_cell_morphology_and_cytoskeleton': 'Morphology measurements require pixel calibration and region entity bindings.',
    'analyze_cell_senescence_and_apoptosis': 'Instrument signals and populations require calibration/entity profiles.',
    'analyze_cfse_cell_proliferation': 'Instrument signals and populations require calibration/entity profiles.',
    'analyze_chromatin_interactions': 'Population/network scores and genomic coordinates require entity/unit profiles.',
    'analyze_ciliary_beat_frequency': 'Morphology measurements require pixel calibration and region entity bindings.',
    'analyze_circular_dichroism_spectra': 'Assay signals, calibrations and derived values require per-field quantity bindings.',
    'analyze_cns_lesion_histology': 'Morphology measurements require pixel calibration and region entity bindings.',
    'analyze_crispr_genome_editing': 'Population/network scores and genomic coordinates require entity/unit profiles.',
    'analyze_cytokine_production_in_cd4_tcells': 'Instrument signals and populations require calibration/entity profiles.',
    'analyze_ddr_network_in_cancer': 'Population/network scores and genomic coordinates require entity/unit profiles.',
    'analyze_ebv_antibody_titers': 'Assay signals, calibrations and derived values require per-field quantity bindings.',
    'analyze_ecological_diversity': 'Composite summary tables require reviewed per-field entity and unit bindings.',
    'analyze_endolysosomal_calcium_dynamics': 'Assay signals, calibrations and derived values require per-field quantity bindings.',
    'analyze_fatty_acid_composition_by_gc': 'Assay signals, calibrations and derived values require per-field quantity bindings.',
    'analyze_flow_cytometry_immunophenotyping': 'Instrument signals and populations require calibration/entity profiles.',
    'analyze_genomic_region_overlap': 'Genomic and expression tables require per-field quantity and coordinate bindings.',
    'analyze_hemodynamic_data': 'Assay signals, calibrations and derived values require per-field quantity bindings.',
    'analyze_immunohistochemistry_image': 'Morphology measurements require pixel calibration and region entity bindings.',
    'analyze_in_vitro_drug_release_kinetics': 'Assay signals, calibrations and derived values require per-field quantity bindings.',
    'analyze_intracellular_calcium_with_rhod2': 'Morphology measurements require pixel calibration and region entity bindings.',
    'analyze_itc_binding_thermodynamics': 'Assay signals, calibrations and derived values require per-field quantity bindings.',
    'analyze_mitochondrial_morphology_and_potential': 'Morphology measurements require pixel calibration and region entity bindings.',
    'analyze_myofiber_morphology': 'Morphology measurements require pixel calibration and region entity bindings.',
    'analyze_pixel_distribution': 'Image measurements require pixel calibration and region entity bindings.',
    'analyze_protein_colocalization': 'Morphology measurements require pixel calibration and region entity bindings.',
    'analyze_protein_comparison': 'Comparative metrics and alignment coordinates require quantity/entity bindings.',
    'analyze_protein_conservation': 'Sequence-derived predictions require reviewed measurement-entity and unit bindings.',
    'analyze_protein_phylogeny': 'Coordinates and derived scores require bound coordinate frames and units.',
    'analyze_protein_physicochemistry': 'Composite summary tables require reviewed per-field entity and unit bindings.',
    'analyze_qpcr_relative_expression': 'Composite summary tables require reviewed per-field entity and unit bindings.',
    'analyze_radiolabeled_antibody_biodistribution': 'Clinical model outputs require per-field units and population/entity bindings.',
    'analyze_rna_secondary_structure_features': 'Sequence-derived predictions require reviewed measurement-entity and unit bindings.',
    'analyze_rnaseq_study': 'Contrasts and transformed counts require separate profiles; the external fit is not run for this census.',
    'analyze_sequence_composition': 'Composite summary tables require reviewed per-field entity and unit bindings.',
    'analyze_thrombus_histology': 'Morphology measurements require pixel calibration and region entity bindings.',
    'analyze_tissue_deformation_flow': 'Morphology measurements require pixel calibration and region entity bindings.',
    'analyze_western_blot': 'Image measurements require pixel calibration and region entity bindings.',
    'analyze_xenograft_tumor_growth_inhibition': 'Clinical model outputs require per-field units and population/entity bindings.',
    'annotate_open_reading_frames': 'Sequence coordinates and design scores require reviewed quantity entity and coordinate-to-unit mappings.',
    'batch_register_images': 'Image-derived measurements require spatial calibration and entity bindings.',
    'bayesian_finemapping_with_deep_vi': 'Latent features, scores and coefficients require unit/entity profiles.',
    'calculate_brain_adc_map': 'Image-derived measurements require spatial calibration and entity bindings.',
    'calculate_physicochemical_properties': 'Descriptors and predicted structures require per-field entity/unit profiles.',
    'calculate_similarity_metrics': 'Image-derived measurements require spatial calibration and entity bindings.',
    'compare_protein_structures': 'Coordinates and derived scores require bound coordinate frames and units.',
    'compare_two_groups': 'Inference, intervals and effect sizes require reviewed per-field entity and unit mappings.',
    'contingency_test': 'Inference, intervals and effect sizes require reviewed per-field entity and unit mappings.',
    'correlation': 'Inference, intervals and effect sizes require reviewed per-field entity and unit mappings.',
    'count_bacterial_colonies': 'Image measurements require pixel calibration and region entity bindings.',
    'create_biochemical_network_sbml_model': 'Coordinates and derived scores require bound coordinate frames and units.',
    'create_segmentation_visualization': 'Image-derived measurements require spatial calibration and entity bindings.',
    'decode_behavior_from_neural_trajectories': 'Latent features, scores and coefficients require unit/entity profiles.',
    'design_golden_gate_oligos': 'Sequence coordinates and design scores require reviewed quantity entity and coordinate-to-unit mappings.',
    'design_primer': 'Sequence coordinates and design scores require reviewed quantity entity and coordinate-to-unit mappings.',
    'design_sgrna_spacers': 'Sequence coordinates and design scores require reviewed quantity entity and coordinate-to-unit mappings.',
    'design_verification_primers': 'Sequence coordinates and design scores require reviewed quantity entity and coordinate-to-unit mappings.',
    'digest_sequence': 'Sequence coordinates and design scores require reviewed quantity entity and coordinate-to-unit mappings.',
    'enumerate_bacterial_cfu_by_serial_dilution': 'Assay signals, calibrations and derived values require per-field quantity bindings.',
    'estimate_alpha_particle_radiotherapy_dosimetry': 'Clinical model outputs require per-field units and population/entity bindings.',
    'estimate_cell_cycle_phase_durations': 'Assay signals, calibrations and derived values require per-field quantity bindings.',
    'find_n_glycosylation_motifs': 'Sequence-derived predictions require reviewed measurement-entity and unit bindings.',
    'find_restriction_enzymes': 'Sequence coordinates and design scores require reviewed quantity entity and coordinate-to-unit mappings.',
    'find_restriction_sites': 'Sequence coordinates and design scores require reviewed quantity entity and coordinate-to-unit mappings.',
    'find_roi_from_image': 'Morphology measurements require pixel calibration and region entity bindings.',
    'find_sequence_mutations': 'Sequence coordinates and design scores require reviewed quantity entity and coordinate-to-unit mappings.',
    'fit_genomic_prediction_model': 'Genomic and expression tables require per-field quantity and coordinate bindings.',
    'fit_michaelis_menten': 'Sequence-derived predictions require reviewed measurement-entity and unit bindings.',
    'gene_set_enrichment_analysis': 'Sequence-derived predictions require reviewed measurement-entity and unit bindings.',
    'golden_gate_assembly': 'Sequence coordinates and design scores require reviewed quantity entity and coordinate-to-unit mappings.',
    'grade_adverse_events_using_vcog_ctcae': 'Clinical model outputs require per-field units and population/entity bindings.',
    'import_colabfold_result': 'Imported metrics and coordinates require quantity/frame bindings.',
    'liftover_coordinates': 'Coordinates and derived scores require bound coordinate frames and units.',
    'linear_regression': 'Inference, intervals and effect sizes require reviewed per-field entity and unit mappings.',
    'model_bacterial_growth_dynamics': 'State and parameter units require per-model quantity profiles.',
    'model_protein_dimerization_network': 'State and parameter units require per-model quantity profiles.',
    'one_way_anova': 'Inference, intervals and effect sizes require reviewed per-field entity and unit mappings.',
    'optimize_anaerobic_digestion_process': 'State and parameter units require per-model quantity profiles.',
    'optimize_codons_for_heterologous_expression': 'Sequence coordinates and design scores require reviewed quantity entity and coordinate-to-unit mappings.',
    'pcr_simple': 'Sequence coordinates and design scores require reviewed quantity entity and coordinate-to-unit mappings.',
    'perform_cosinor_analysis': 'Sequence-derived predictions require reviewed measurement-entity and unit bindings.',
    'perform_flux_balance_analysis': 'State and parameter units require per-model quantity profiles.',
    'perform_gene_expression_nmf_analysis': 'Genomic and expression tables require per-field quantity and coordinate bindings.',
    'perform_mwas_cyp2c19_metabolizer_status': 'Clinical model outputs require per-field units and population/entity bindings.',
    'predict_o_glycosylation_hotspots': 'Sequence-derived predictions require reviewed measurement-entity and unit bindings.',
    'predict_rna_secondary_structure': 'Descriptors and predicted structures require per-field entity/unit profiles.',
    'prepare_input_for_nnunet': 'Image-derived measurements require spatial calibration and entity bindings.',
    'preprocess_image': 'Image-derived measurements require spatial calibration and entity bindings.',
    'principal_component_analysis': 'Inference, intervals and effect sizes require reviewed per-field entity and unit mappings.',
    'quantify_amyloid_beta_plaques': 'Morphology measurements require pixel calibration and region entity bindings.',
    'quantify_and_cluster_cell_motility': 'Morphology measurements require pixel calibration and region entity bindings.',
    'quantify_biofilm_biomass_crystal_violet': 'Assay signals, calibrations and derived values require per-field quantity bindings.',
    'quantify_cell_cycle_phases_from_microscopy': 'Morphology measurements require pixel calibration and region entity bindings.',
    'quantify_corneal_nerve_fibers': 'Morphology measurements require pixel calibration and region entity bindings.',
    'quick_affine_registration': 'Image-derived measurements require spatial calibration and entity bindings.',
    'quick_deformable_registration': 'Image-derived measurements require spatial calibration and entity bindings.',
    'quick_rigid_registration': 'Image-derived measurements require spatial calibration and entity bindings.',
    'reconstruct_3d_face_from_mri': 'Image-derived measurements require spatial calibration and entity bindings.',
    'segment_and_analyze_microbial_cells': 'Morphology measurements require pixel calibration and region entity bindings.',
    'segment_and_quantify_cells_in_multiplexed_images': 'Morphology measurements require pixel calibration and region entity bindings.',
    'simulate_demographic_history': 'Population/network scores and genomic coordinates require entity/unit profiles.',
    'simulate_gene_circuit_with_growth_feedback': 'State and parameter units require per-model quantity profiles.',
    'simulate_generalized_lotka_volterra_dynamics': 'State and parameter units require per-model quantity profiles.',
    'simulate_metabolic_network_perturbation': 'Population/network scores and genomic coordinates require entity/unit profiles.',
    'simulate_microbial_population_dynamics': 'State and parameter units require per-model quantity profiles.',
    'simulate_protein_signaling_network': 'State and parameter units require per-model quantity profiles.',
    'simulate_renin_angiotensin_system_dynamics': 'State and parameter units require per-model quantity profiles.',
    'simulate_thyroid_hormone_pharmacokinetics': 'State and parameter units require per-model quantity profiles.',
    'simulate_whole_cell_ode_model': 'State and parameter units require per-model quantity profiles.',
    'split_modalities': 'Image-derived measurements require spatial calibration and entity bindings.',
    'track_immune_cells_under_flow': 'Morphology measurements require pixel calibration and region entity bindings.',
}
