from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from .security import MAX_TEXT_FILE_BYTES, read_text_bounded
from .dna_placement import DNA_IR_V2, reverse_complement, validate_v2_construct


ROLE_URIS = {
    "promoter": "https://identifiers.org/SO:0000167",
    "rbs": "https://identifiers.org/SO:0000139",
    "cds": "https://identifiers.org/SO:0000316",
    "terminator": "https://identifiers.org/SO:0000141",
}

DNA_TYPE = "https://identifiers.org/SBO:0000251"
IUPAC_DNA_ENCODING = "https://identifiers.org/edam:format_1207"
BASE_URI = "https://example.org/proto-agent/sbol/"


def export_sbol3_turtle(ir: dict[str, Any]) -> str:
    is_v2 = ir.get("schema_version") == DNA_IR_V2
    design_id = _identifier(ir["design_id"])
    lines = [
        "# Minimal SBOL3 Turtle export generated by proto-agent.",
        "# Intended for local exchange previews; verify with pySBOL3/SBOL-utilities before interoperability claims.",
        "@prefix sbol: <http://sbols.org/v3#> .",
        "@prefix dcterms: <http://purl.org/dc/terms/> .",
        "@prefix prov: <http://www.w3.org/ns/prov#> .",
        "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .",
        f"@prefix pa: <{BASE_URI}> .",
        "",
        f"pa:{design_id} a sbol:Collection ;",
        f"  dcterms:title \"{_literal(ir['design_id'])}\" ;",
        f"  dcterms:description \"Proto Agent design for chassis {_literal(ir['chassis'])}\" ;",
        "  prov:wasGeneratedBy \"proto-agent\" .",
        "",
    ]

    construct_ids = []
    for construct in ir.get("constructs", []):
        if is_v2:
            validate_v2_construct(construct)
        construct_id = _identifier(construct["name"])
        construct_ids.append(construct_id)
        sequence_id = f"{construct_id}_sequence"
        sequence = _construct_sequence(construct)
        lines.extend(
            [
                f"pa:{construct_id} a sbol:Component ;",
                f"  dcterms:title \"{_literal(construct['name'])}\" ;",
                f"  sbol:type <{DNA_TYPE}> ;",
                f"  sbol:hasSequence pa:{sequence_id} ;",
                "  sbol:hasFeature " + ", ".join(f"pa:{construct_id}_{index + 1}_{_identifier(part['id'])}" for index, part in enumerate(construct.get("parts", []))) + " .",
                "",
                f"pa:{sequence_id} a sbol:Sequence ;",
                f"  sbol:encoding <{IUPAC_DNA_ENCODING}> ;",
                f"  sbol:elements \"{sequence}\" .",
                "",
            ]
        )
        position = 1
        for index, part in enumerate(construct.get("parts", []), start=1):
            part_id = _identifier(part["id"])
            feature_id = f"{construct_id}_{index}_{part_id}"
            part_component_id = f"part_{part_id}"
            part_sequence_id = f"{part_component_id}_sequence"
            part_sequence = part.get("sequence", "").upper()
            end = position + len(part_sequence) - 1
            if is_v2 and part["placement"]["orientation"] == "reverse":
                part_sequence = reverse_complement(part_sequence)
            role_uri = ROLE_URIS.get(part.get("type", ""), "https://identifiers.org/SO:0000110")
            lines.extend(
                [
                    f"pa:{part_component_id} a sbol:Component ;",
                    f"  dcterms:title \"{_literal(part.get('name') or part['id'])}\" ;",
                    f"  sbol:type <{DNA_TYPE}> ;",
                    f"  sbol:role <{role_uri}> ;",
                    f"  sbol:hasSequence pa:{part_sequence_id} .",
                    "",
                    f"pa:{part_sequence_id} a sbol:Sequence ;",
                    f"  sbol:encoding <{IUPAC_DNA_ENCODING}> ;",
                    f"  sbol:elements \"{part_sequence}\" .",
                    "",
                    f"pa:{feature_id} a sbol:SubComponent ;",
                    f"  sbol:instanceOf pa:{part_component_id} ;",
                    f"  sbol:hasLocation pa:{feature_id}_range .",
                    "",
                    f"pa:{feature_id}_range a sbol:Range ;",
                    f"  sbol:start {position} ;",
                    f"  sbol:end {end} .",
                    "",
                ]
            )
            if is_v2:
                orientation = "reverseComplement" if part["placement"]["orientation"] == "reverse" else "inline"
                lines.extend([
                    f"pa:{feature_id}_range sbol:orientation sbol:{orientation} .",
                    f'pa:{feature_id} dcterms:description "instance={_literal(part["instance_id"])}; placement={part["placement"]["orientation"]}; biological_direction={part["direction"]}; source_sha256={part["source_sequence_sha256"]}" .',
                    "",
                ])
            position = end + 1
        for annotation in construct.get("annotations", []) if is_v2 else []:
            annotation_id = f"{construct_id}_annotation_{_identifier(annotation['id'])}"
            ranges = [f"{annotation_id}_{index}" for index in range(len(annotation["locations"]))]
            lines.extend([
                f"pa:{construct_id} sbol:hasFeature pa:{annotation_id} .",
                f"pa:{annotation_id} a sbol:SequenceFeature ;",
                f'  dcterms:title "{_literal(annotation["name"])}" ;',
                f'  dcterms:description "User annotation {_literal(annotation["id"])}; source anchored; human review required" ;',
                "  sbol:hasLocation " + ", ".join(f"pa:{value}" for value in ranges) + " .",
            ])
            for location_id, location in zip(ranges, annotation["locations"]):
                lines.extend([f"pa:{location_id} a sbol:Range ;", f"  sbol:start {location['start'] + 1} ;", f"  sbol:end {location['end']} ."])
                if location["direction"]:
                    orientation = "reverseComplement" if location["direction"] == -1 else "inline"
                    lines.append(f"pa:{location_id} sbol:orientation sbol:{orientation} .")
            lines.append("")

    if construct_ids:
        lines.append(
            f"pa:{design_id} sbol:member " + ", ".join(f"pa:{construct_id}" for construct_id in construct_ids) + " ."
        )
        lines.append("")

    return "\n".join(lines)


def validate_sbol_turtle(path: str | Path) -> dict[str, Any]:
    source = Path(path)
    text = read_text_bounded(source, MAX_TEXT_FILE_BYTES)
    diagnostics: list[dict[str, Any]] = []
    required_patterns = {
        "SBOL_PREFIX_MISSING": "@prefix sbol:",
        "SBOL_COMPONENT_MISSING": "a sbol:Component",
        "SBOL_SEQUENCE_MISSING": "a sbol:Sequence",
        "SBOL_SEQUENCE_ELEMENTS_MISSING": "sbol:elements",
        "SBOL_COLLECTION_MISSING": "a sbol:Collection",
    }
    for code, pattern in required_patterns.items():
        if pattern not in text:
            diagnostics.append(
                {
                    "severity": "error",
                    "file": str(source),
                    "line": 0,
                    "code": code,
                    "message": f"SBOL Turtle export is missing required pattern: {pattern}",
                }
            )

    component_count = text.count("a sbol:Component")
    sequence_count = text.count("a sbol:Sequence")
    feature_count = text.count("a sbol:SubComponent")
    return {
        "ok": not diagnostics,
        "file": str(source),
        "component_count": component_count,
        "sequence_count": sequence_count,
        "feature_count": feature_count,
        "diagnostics": diagnostics,
        "summary": "SBOL Turtle structure looks valid for the local minimal profile."
        if not diagnostics
        else "SBOL Turtle structure failed local minimal-profile validation.",
    }


def _construct_sequence(construct: dict[str, Any]) -> str:
    return "".join(part.get("sequence", "") for part in construct.get("parts", [])).upper()


def _identifier(value: str) -> str:
    sanitized = re.sub(r"[^A-Za-z0-9_]", "_", value)
    if not sanitized:
        return "unnamed"
    if sanitized[0].isdigit():
        return f"_{sanitized}"
    return sanitized


def _literal(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')
