import test from "node:test";
import assert from "node:assert/strict";
import {rnaSeqDisplayValue,rnaSeqGenePage,rnaSeqGenePlot,validateRnaSeqStudy,RNASEQ_VIEW_LIMITS} from "../src/renderer/rnaseq-study.ts";

const source=(path)=>({path,sha256:"a".repeat(64),bytes:200});
const args={counts_path:"build/rna-counts.csv",samples_path:"build/rna-samples.csv",reference_level:"control",comparison_level:"treated",design:"condition",analysis_mode:"fit",alpha:.05,min_count:10,min_samples:2,pca_top_genes:500,size_factor_type:"ratio"};
const enrichmentBase={method:"hypergeometric ORA with Benjamini-Hochberg correction",background_rule:"genes with finite adjusted p-value in this contrast",selection_rule:"padj < alpha; both directions"};
function fixture(){return {
  schema_version:"proto-agent.rnaseq-study.v1",analysis:{mode:"fit",status:"complete",engine_run_id:"b".repeat(32),manifest_path:"build/bioinformatics/test/manifest.json"},sources:{counts_path:source(args.counts_path),samples_path:source(args.samples_path)},
  design:{id:"condition",formula:"~ condition",columns:["Intercept","conditiontreated"],rank:2,residual_df:2,contrast:{factor:"condition",numerator:"treated",denominator:"control"},factor_levels:{condition:["control","treated"]}},
  qc:{samples:["A","B","C","D"].map((sample,index)=>({sample,condition:index<2?"control":"treated",library_size:1000+index,detected_genes:5,zero_fraction:1/6})),gene_count:6,sample_count:4,all_zero_genes:["g6"],metadata_reordered:true,condition_counts:{control:2,treated:2}},
  filter:{min_count:10,min_samples:2,input_genes:6,kept_genes:4,excluded_genes:["g5","g6"]},
  pca:{samples:["A","B","C","D"].map((sample,index)=>({sample,condition:index<2?"control":"treated",pc1:index-2,pc2:2-index})),variance_fraction:[.7,.2],genes:["g1","g2"],transform:"DESeq2 varianceStabilizingTransformation blind=FALSE",center:true,scale:false},
  differential_expression:{rows:[
    {gene_id:"g1",baseMean:100,log2FoldChange:2,lfcSE:.5,stat:4,pvalue:.005,padj:.01,status:"available"},
    {gene_id:"g2",baseMean:80,log2FoldChange:-1,lfcSE:.2,stat:-5,pvalue:0,padj:0,status:"available"},
    {gene_id:"g3",baseMean:25,log2FoldChange:null,lfcSE:null,stat:null,pvalue:null,padj:null,status:"p_value_unavailable"},
    {gene_id:"g4",baseMean:50,log2FoldChange:0,lfcSE:.3,stat:0,pvalue:1,padj:1,status:"available"}],alpha:.05,contrast:{numerator:"treated",denominator:"control"},summary:{modeled:4,pvalue_available:3,padj_available:3,significant_up:1,significant_down:1,significant_zero:0}},
  enrichment:{...enrichmentBase,status:"not-requested"},warnings:["Synthetic software acceptance fixture, not biological evidence."],limitations:["No biological validation."]};}
function receipt(result){return{ok:true,tool:"analyze_rnaseq_study",run_id:"c".repeat(32),result_sha256:"d".repeat(64),inputs:Object.fromEntries(Object.entries(result.sources).map(([name,file])=>[`file:${name}`,{path:file.path,sha256:file.sha256}]))};}
function valid(result=fixture(),request=args,run=receipt(result)){return validateRnaSeqStudy(result,request,run);}

test("fitted study retains exact ordered identities, nulls, zero probabilities and annotations",()=>{const raw=fixture(),copy=structuredClone(raw),result=valid(raw);assert.deepEqual(raw,copy);assert.deepEqual(result.qc.samples.map(row=>row.sample),["A","B","C","D"]);assert.equal(result.differential_expression.rows[1].padj,0);assert.equal(result.differential_expression.rows[2].padj,null);assert.notEqual(result,raw);assert.equal(RNASEQ_VIEW_LIMITS.samples,100);});
test("validation-only state has no fitted output and honors default optional inputs",()=>{const raw=fixture();raw.analysis={mode:"validate",status:"validated"};raw.pca=null;raw.differential_expression=null;assert.equal(valid(raw,{counts_path:args.counts_path,samples_path:args.samples_path,reference_level:"control",comparison_level:"treated",analysis_mode:"validate"}).analysis.status,"validated");raw.pca=fixture().pca;assert.throws(()=>valid(raw,{...args,analysis_mode:"validate"}),/validation-only/);});
test("source paths, SHA256, source presence and live receipt identities fail closed",()=>{for(const field of ["counts_path","samples_path"]){const raw=fixture(),run=receipt(raw);run.inputs[`file:${field}`].sha256="f".repeat(64);assert.throws(()=>valid(raw,args,run),/source identities/);assert.throws(()=>valid(raw,{...args,[field]:"build/other.csv"}),/source paths/);}for(const patch of[{run_id:undefined},{result_sha256:undefined},{ok:false},{tool:"other"}]){const raw=fixture();assert.throws(()=>valid(raw,args,{...receipt(raw),...patch}));}const raw=fixture();raw.sources.gene_sets_path=source("build/sets.json");assert.throws(()=>valid(raw),/source paths/);});
test("recorded examples cannot claim a live identity",()=>{const raw=fixture(),preview={ok:true,tool:"analyze_rnaseq_study",preview:true,result:raw};assert.equal(valid(raw,args,preview).analysis.status,"complete");for(const patch of[{run_id:"a".repeat(32)},{result_sha256:"b".repeat(64)},{inputs:receipt(raw).inputs}])assert.throws(()=>valid(raw,args,{...preview,...patch}),/malformed contract/);});
test("malformed, nonfinite and oversized statistics never render",()=>{for(const bad of[NaN,Infinity,-1,1.1,"0.5",true]){const raw=fixture();raw.differential_expression.rows[0].padj=bad;assert.throws(()=>valid(raw));}for(const bad of[NaN,Infinity,"2",true]){const raw=fixture();raw.pca.samples[0].pc1=bad;assert.throws(()=>valid(raw));}const raw=fixture();raw.sources.counts_path.bytes=32*1024*1024+1;assert.throws(()=>valid(raw));});
test("duplicate genes and sample identities reject the whole result",()=>{for(const mutate of[raw=>raw.qc.samples[1].sample="A",raw=>raw.pca.samples[1].sample="A",raw=>raw.differential_expression.rows[1].gene_id="g1",raw=>raw.filter.excluded_genes=["g5","g5"],raw=>raw.pca.genes=["g1","g1"]]){const raw=fixture();mutate(raw);assert.throws(()=>valid(raw),/duplicate/);}});
test("design contrast, formula, rank and filtering must match the actual request",()=>{for(const mutate of[raw=>raw.design.contrast.numerator="control",raw=>raw.design.formula="~ batch + condition",raw=>raw.design.rank=1,raw=>raw.design.residual_df=1,raw=>raw.filter.min_count=11,raw=>raw.filter.kept_genes=3,raw=>raw.analysis.mode="validate"]){const raw=fixture();mutate(raw);assert.throws(()=>valid(raw));}});
test("QC count denominators and declared factor levels are checked",()=>{for(const mutate of[raw=>raw.qc.samples[0].zero_fraction=0,raw=>raw.qc.sample_count=3,raw=>raw.qc.condition_counts.control=3,raw=>raw.design.factor_levels.condition=["control","missing"]]){const raw=fixture();mutate(raw);assert.throws(()=>valid(raw));}});
test("subject-aware design preserves supplied sample metadata without inferring subjects",()=>{const raw=fixture();raw.design={...raw.design,id:"subject_condition",formula:"~ subject + condition",columns:["Intercept","subject2","conditiontreated"],rank:3,residual_df:1,factor_levels:{condition:["control","treated"],subject:["1","2"]}};for(const rows of[raw.qc.samples,raw.pca.samples])rows.forEach((row,index)=>row.subject=String(index%2+1));assert.equal(valid(raw,{...args,design:"subject_condition"}).design.rank,3);delete raw.qc.samples[0].subject;assert.throws(()=>valid(raw,{...args,design:"subject_condition"}),/subject identity/);});
test("PCA order, gene membership and variance explainability cannot contradict the fit",()=>{for(const mutate of[raw=>raw.pca.samples.reverse(),raw=>raw.pca.genes=["g6"],raw=>raw.pca.variance_fraction=[.8,.5],raw=>raw.pca.samples.pop()]){const raw=fixture();mutate(raw);assert.throws(()=>valid(raw));}});
test("fitted output summaries are checked against retained rows, including zero adjusted p",()=>{for(const mutate of[raw=>raw.differential_expression.summary.significant_down=0,raw=>raw.differential_expression.summary.padj_available=4,raw=>raw.differential_expression.rows.pop(),raw=>raw.differential_expression.contrast.numerator="control",raw=>raw.differential_expression.alpha=.1]){const raw=fixture();mutate(raw);assert.throws(()=>valid(raw));}});
test("volcano and MA projections account for every row without imputation or p-value floors",()=>{const rows=fixture().differential_expression.rows;const volcano=rnaSeqGenePlot(rows,"volcano",.05);assert.equal(volcano.total,4);assert.deepEqual(volcano.points.map(row=>row.id),["g1","g4"]);assert.deepEqual(volcano.excluded,{missing:1,zeroAdjustedP:1,zeroBaseMean:0});assert.deepEqual(volcano.points[0],{id:"g1",x:2,y:2,group:"Higher"});const ma=rnaSeqGenePlot(rows,"ma",.05);assert.equal(ma.points.length,3);assert.equal(ma.points[1].group,"Lower");const zero=structuredClone(rows);zero[0].baseMean=0;assert.equal(rnaSeqGenePlot(zero,"ma",.05).excluded.zeroBaseMean,1);assert.equal(rows[1].padj,0);});
test("gene table search and pagination preserve original order and never omit matching pages",()=>{const rows=Array.from({length:123},(_,index)=>({...fixture().differential_expression.rows[0],gene_id:`gene-${String(index).padStart(3,"0")}`}));const page0=rnaSeqGenePage(rows,"",0),page1=rnaSeqGenePage(rows,"",1),page2=rnaSeqGenePage(rows,"",999);assert.equal(page0.rows.length,50);assert.equal(page1.rows[0].gene_id,"gene-050");assert.equal(page2.rows.length,23);assert.equal(page2.page,2);assert.equal(rnaSeqGenePage(rows," GENE-12 ",4).matching,3);assert.equal(rnaSeqGenePage(rows,"absent",5).page,0);assert.equal(rnaSeqGenePage(rows,"",NaN).page,0);});
test("enrichment source and complete background/selection identities remain bound to DE rows",()=>{const raw=fixture();raw.sources.gene_sets_path=source("build/sets.json");raw.enrichment={...enrichmentBase,status:"completed",gene_set_source:{namespace:"synthetic",source:"hand-authored test fixture"},selected_genes:["g1","g2"],background_genes:["g1","g2","g4"],tested_gene_sets:1,rows:[{name:"set-a",set_size_in_background:1,excluded_members_outside_background:0,overlap_count:1,overlap_genes:["g1"],expected_overlap:2/3,fold_enrichment:1.5,p_value:2/3,adjusted_p_value:2/3}]};const request={...args,gene_sets_path:"build/sets.json"};assert.equal(valid(raw,request).enrichment.tested_gene_sets,1);for(const mutate of[r=>r.enrichment.selected_genes=["g1"],r=>r.enrichment.background_genes.push("g3"),r=>r.enrichment.rows[0].overlap_genes=["g4"],r=>r.enrichment.tested_gene_sets=2]){const wrong=structuredClone(raw);mutate(wrong);assert.throws(()=>valid(wrong,request),/enrichment/);}});
test("requested gene sets in validation mode stay explicitly unrun",()=>{const raw=fixture();raw.analysis={mode:"validate",status:"validated"};raw.pca=null;raw.differential_expression=null;raw.sources.gene_sets_path=source("build/sets.json");raw.enrichment={...enrichmentBase,status:"not-run",reason:"Input validation only."};assert.equal(valid(raw,{...args,analysis_mode:"validate",gene_sets_path:"build/sets.json"}).enrichment.status,"not-run");raw.enrichment.status="completed";assert.throws(()=>valid(raw,{...args,analysis_mode:"validate",gene_sets_path:"build/sets.json"}),/validation-only/);});
test("current engine receipt extensions and source snapshots remain bounded and visible",()=>{const raw=fixture();raw.analysis={...raw.analysis,manifest_sha256:"e".repeat(64),runtime:{versions:{R:"test-only",DESeq2:"test-only"}},engine_artifacts:[{path:"build/bioinformatics/test/outputs/metadata.csv",bytes:80,sha256:"f".repeat(64)}],engine_metadata:{schema:"proto-agent.deseq2-analysis.v1",test:"Wald"}};for(const[name,file]of Object.entries(raw.sources))file.snapshot=`build/rnaseq-inputs/${"e".repeat(32)}/${name}.csv`;raw.qc.samples.forEach(row=>row.size_factor=1);assert.equal(valid(raw).qc.samples[0].size_factor,1);raw.sources.counts_path.snapshot="build/another.csv";assert.throws(()=>valid(raw),/snapshot/);});
test("gene status cannot conceal unavailable or contradictory probabilities",()=>{for(const mutate of[raw=>raw.differential_expression.rows[0].status="p_value_unavailable",raw=>raw.differential_expression.rows[0].pvalue=null]){const raw=fixture();mutate(raw);assert.throws(()=>valid(raw),/availability status/);}});
test("omitted mode uses the backend default fit, rather than claiming validation only",()=>{const request={...args};delete request.analysis_mode;assert.equal(valid(fixture(),request).analysis.mode,"fit");});
test("observed nonzero adjusted p is never rounded to zero by locale formatting",()=>{const observed=.000118615761136;assert.equal(rnaSeqDisplayValue(observed,"en-US"),"0.000118616");assert.equal(rnaSeqDisplayValue(observed,"de-DE"),"0,000118616");assert.equal(rnaSeqDisplayValue(-observed,"en-US"),"-0.000118616");assert.equal(rnaSeqDisplayValue(.0004999,"en-US"),"0.0004999");});
test("display preserves signed small values, actual zero and unavailable values distinctly",()=>{assert.equal(rnaSeqDisplayValue(3.9e-8,"en-US"),"3.90000e-8");assert.equal(rnaSeqDisplayValue(-3.9e-8,"en-US"),"-3.90000e-8");assert.equal(rnaSeqDisplayValue(0,"en-US"),"0");assert.equal(rnaSeqDisplayValue(null,"en-US"),"Unavailable");assert.equal(rnaSeqDisplayValue(undefined,"en-US"),"Unavailable");assert.throws(()=>rnaSeqDisplayValue(NaN,"en-US"),/finite/);assert.throws(()=>rnaSeqDisplayValue(Infinity,"en-US"),/finite/);});
